### PR TITLE
[Layout] Add view large button for zooming

### PR DESCRIPTION
**Pull request by larkin**
@charlesh88 opening this one so you can look at this from a styling point of view. This adds a button to objects in a layout that allows them to be opened in a modal dialog.  It's helpful when you have a small object in a layout and you want to see more detail on the object.  I know we have a VISTA request for this functionality, and we have a help wanted for similar functionality (preview object before adding to layout) though I couldn't find an issue for exactly this functionality.

Note that this allows access to the "control bar" which would usually be hidden in a layout-- allowing a user to export the plot as an image if they would like.  Additionally, interactions with the view persist after you close the modal.  You can see in the example below that plot zoom and pan persist after the modal is closed.

Here's a quick example of it in use:

view_large

TODO:
* [x] Write test for MCTTriggerModal

### CODE REVIEW

**Comment by charlesh88** [comment]
Working on this in branch `view-large`.

**Comment by charlesh88** [comment]
Seeing some weirdness with enlarging plots and historical table (that never loads...) spawned off of a SWG in a layout. Will see if I can figure out what's causing this.

Original, crisp and clear:
screen shot 2017-02-14 at 4 10 05 pm

Enlarged RT table, looks good:
screen shot 2017-02-14 at 4 10 26 pm


Enlarged plot and historical table, fuzzy and blurry:
screen shot 2017-02-14 at 4 10 12 pm

**Comment by charlesh88** [comment]
@larkin Just pushed some WIP changes up to `view-large` that address the button in the layout frame, pull in if you like but please don't merge yet. I'll hit this running tomorrow AM.

**Comment by larkin** [comment]
@charlesh88 I think the fuzziness is based on reduced contrast between between the background in a layout and the background in an overlay.  Try with the snow theme and it seems a lot better.

**Comment by charlesh88** [comment]
@larkin Think you're partially right about contrast, but that's not all there is to it - if that was, then we'd be seeing the problem with the RT table view as well.

I think it may be some combo of reduced font sizes, font weight, canvas and subpixel anti-aliasing.

**Comment by charlesh88** [comment]
@larkin Just pushed a significant update for this. Please take a look at MCTTriggerModal.js and make sure I'm not doing anything I shouldn't.

**Comment by larkin** [comment]
Create menu box is quite a lot wider now than previously.  Not a blocker, but just seems... extra wide?

Now:
screen shot 2017-02-21 at 3 57 30 pm

Previous:
screen shot 2017-02-21 at 4 01 03 pm

**Comment by charlesh88** [comment]
@larkin Just pushed some fixes:
- Cleaned up anim CSS in _overlay.scss;
- Restored max-width for dialogs, addresses "dialog obesity".
- Bunch of small overlay-related fixes for mobile.

I think you're right about fuzziness being connected with use of `transform(translate...)` to center objects. Seems to be connected with usage of that when a canvas element is on screen at the same time.

**Comment by charlesh88** [comment]
@larkin Just pushed timing fixes: zoom-expand is now 250ms and is defined in theme constants files.

**Comment by larkin** [comment]
Rebased, cleaned up, and added a failing test so that this doesn't get merged until I get that completed, added TODOs to OP.

**Comment by charlesh88** [comment]
@larkin Go ahead and reassign to me if needed when this is ready.

**Comment by larkin** [comment]
I rebased this, squashed it, added tests, and handled some conflicts.  It's good to go now.

@VWoeltjen sending your way for review of JS. 

# Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y!
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

**Comment by VWoeltjen** [comment]
Neat new feature! Looks good to me.

### Review Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
