### PR TITLE
mct4269 - disallowing overlay plots for bar charts

### LINKED ISSUE #4269: Better handling of Overlay Plots added to Bar Graphs
#### Summary
Users can create an Overlay Plot directly into a Bar Graph

Screen Shot 2021-09-28 at 4 42 30 PM

or can drag an Overlay Plot onto a Bar Graph, adding it. Either action results in the Bar Graph failing to display anything.

#### Expected vs Current Behavior
Either treat the Overlay Plot as an aggregate data source and display its constituents as such (preferred) or disallow Overlay Plots as part of a Bar Graph's composition.

#### Impact Check List

- [x] Data loss or misrepresented data? _@charlesh88 says: if a user does this, data is not being displayed when there's an expectation that it would be._
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Create a Bar Graph and an Overlay Plot.
2. Drag the plot onto the Bar Graph.
3. Observe: the plot is added, but nothing is displayed.

#### Environment
* Open MCT Version: 1.7.8
* Deployment Type: localhost
* OS:
* Browser:

### PR DESCRIPTION
**Pull request by scottbell**
Resolves #4269 

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? Will users need to change how they are calling the API, or how they've extended core plugins such as Tables or Plots?

### Author Checklist

* [X] Changes address original issue?
* [X] Unit tests included and/or updated with changes?
* [X] Command line build passes?
* [X] Has this been smoke tested?
* [X] Testing instructions included in associated issue?

### CODE REVIEW

**Comment by scottbell** [comment]
For 1.7.8, I was thinking we should do the easy thing and just disallow overlay plots in the composition policy. For the other option (treating the Overlay Plot as an aggregate data source and display its constituents as such), should we have a separate ticket?

**Comment by shefalijoshi** [comment]
> For 1.7.8, I was thinking we should do the easy thing and just disallow overlay plots in the composition policy. For the other option (treating the Overlay Plot as an aggregate data source and display its constituents as such), should we have a separate ticket?

No, I think it's sufficient to disallow. If the requirement to include overlay plots in a bar graph comes up, we can implement it later.

**Comment by scottbell** [comment]
> Hmm, I thought you added the child.type condition before because it was causing issues with other plots?

That's a good point. Let me dig up why I originally added it. Hopefully it's been OBE

**Comment by scottbell** [comment]
> > Hmm, I thought you added the child.type condition before because it was causing issues with other plots?
> 
> That's a good point. Let me dig up why I originally added it. Hopefully it's been OBE

Looks like just some cargo-cult pasting from Stacked Plot's composition policy:
https://github.com/nasa/openmct/blob/1.7.8/src/plugins/plot/stackedPlot/StackedPlotCompositionPolicy.js#L22

**Comment by scottbell** [comment]
> > > Hmm, I thought you added the child.type condition before because it was causing issues with other plots?
> > 
> > 
> > That's a good point. Let me dig up why I originally added it. Hopefully it's been OBE
> 
> Looks like just some cargo-cult pasting from Stacked Plot's composition policy: https://github.com/nasa/openmct/blob/1.7.8/src/plugins/plot/stackedPlot/StackedPlotCompositionPolicy.js#L22

And it looks like everything is working through some cursory testing

**Review by shefalijoshi — APPROVED** [review]
### Reviewer Checklist

* [x] Changes appear to address issue?
* [ ] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled `bug`? (only applicable if this PR is for a bug fix)
* [ ] List of Acceptance Tests Performed.

**Pull request merged**
