### PR TITLE
Fix to [Display Layout] Right click on item acts as sticky move #3343

### PR DESCRIPTION
**Pull request by Quintis1212**
Hello everyone ) This is fix for bug - https://github.com/nasa/openmct/issues/3343 .
 As I found out  @click.capture and v-on:click not listening for right mouse key down , so I applyed  @mousedown.right and  @mouseup.right attributes. This attributes call function that change variable this.mouseRightKeyCatch to true or false .This variable is used in move function , and  mouseRightKeyCatch variable stops it when right key mouse button clicked.

### CODE REVIEW

**Comment by akhenry** [comment]
@Quintis1212 Thanks for pushing a PR for this! We really appreciate your contribution.

I wonder if we might be able to fix this in an even simpler way. What if we just added a `.left` modifier to [the mousedown event handler that initiates the move](https://github.com/nasa/openmct/blob/3571004f5c83eb12c9e72991cbf5fd03e8ba2433/src/plugins/displayLayout/components/LayoutFrame.vue#L36)? That way we just filter out all right clicks, so a right click will never trigger the move behavior?

Just a point of housekeeping: we will need a Contributor License Agreement signed by you before we can merge your code - https://nasa.github.io/openmct/static/files/ind-cla-open-mct.pdf Once signed, please send it to arc-dl-openmct@mail.nasa.gov

Thank you!

**Comment by Quintis1212** [comment]
Hello !) thank you for response ) @move="move" directive is listening left and right mouse keys, and left modifier also not help:
`
    @dragover.left="handleDragOver"
    @click.left="bypassSelection"
    @drop.left="handleDrop"

`
It means that we must listen right click of mouse to prevent this bug )

**Comment by akhenry** [comment]
@Quintis1212 I tried the code change I suggested in https://github.com/nasa/openmct/pull/3717#issuecomment-788141538 and it appears to work for me. Did you have problems when you tried this? Maybe you found a bug that I didn't?

**Comment by akhenry** [comment]
@Quintis1212 Hi, we're hoping to close out this PR. Did you have any thoughts on my previous comment?

**Review by akhenry — CHANGES_REQUESTED** [review]
Comments in https://github.com/nasa/openmct/pull/3717#issuecomment-895367044 need to be addressed.

**Comment by jvigliotta** [comment]
Hi @Quintis1212 thank you so much for the contribution, we're going to take this one over in the PR #4126, as we're looking to get this in pretty soon.

**Pull request closed without merging**
