### PR TITLE
Plots underlays

### PR DESCRIPTION
**Pull request by shefalijoshi**
### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

### CODE REVIEW

**Comment by shefalijoshi** [comment]
Sample json:
[Underlay.json.zip](https://github.com/nasa/openmct/files/7791024/Underlay.json.zip)

**Comment by shefalijoshi** [comment]
@akhenry Please review this draft when you get a chance. I do need Charles' input on how to add this underlay to a scatter plot.

**Comment by charlesh88** [comment]
> 

Per our recent discussion, the approach should be additions to the properties inteface:
- Add a "Select File..." button that lets the user select a valid JSON file.
- Add min/max Y and min/max X value inputs, necessary to register the underlay within the value-space of the plot. These are not required, and if left blank, the underlay displays at 100% size within the plot area.

**Comment by shefalijoshi** [comment]
@akhenry Can you please review this even though it's a draft? Thanks!

**Comment by shefalijoshi** [comment]
Covered by https://github.com/nasa/openmct/pull/4881

**Comment by charlesh88** [comment]
Still don't know how to test the plot underlay add/remove capability locally.

**Pull request closed without merging**
