### PR TITLE
[Roots] Support async root registration, with My Items

### PR DESCRIPTION
**Pull request by VWoeltjen**
Restores changes from #1252 and registers any legacy-added roots (such as My Items from the `my-items` bundle) with the new API to address #1264.

For review purposes, here's [the diff realtive to the previous PR](https://github.com/nasa/openmct/compare/64ff4632009d22f9cd7a49c446443f5c4a8ba180...my-items-1264)

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Hm, so I think the changes to object-utils may have been the only thing that needed to be done here (they'd fallen out of sync with the documentation for identifiers). This changeset works, but the new `runs` extension might be totally unnecessary.

Investigating; would like to get root registration working reliably to unblock other issues.

**Comment by VWoeltjen** [comment]
Reassigning to self based on the above. In particular, want to make sure the following works:

```
            openmct.objects.addRoot({ namespace: 'foo', key: 'bar' });

            openmct.objects.addProvider('foo', {
                get: function (key) {
                    return key !== 'bar' ?
                        Promise.resolve({
                            identifier: { namespace: 'foo', key: key },
                            type: "generator",
                            period: 44,
                            name: 'swg ' + key
                        }) :
                        Promise.resolve({
                            identifier: { namespace: 'foo', key: key },
                            type: "folder",
                            name: "This is a test!",
                            composition: ['a', 'b', 'c'].map(function (k) {
                                return {
                                    namespace: 'foo',
                                    key: k
                                };
                            })
                        });
                }
            });
```

...as this is needed by https://developer.nasa.gov/ResourceProspector/warp/issues/236

**Comment by VWoeltjen** [comment]
### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y (some removed, changes covered by #1218) 
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

**Comment by VWoeltjen** [comment]
There's some logging I added to the legacy framework layer to help debug a problem (that ended up being a dead-end approach anyway.) I've left that logging in place because it should be useful for however long that framework layer remains in use, but would be just as happy to remove it to simplify the diff. Let me know what you think.

**Comment by larkin** [comment]
Logging is nice during the transition period, this looks good.

# Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
