### PR TITLE
Save and Finish blocking modal dialog Refactor and Styles #2500

### PR DESCRIPTION
**Pull request by nikhilmandlik**
TODOs:
- [x] **Refactor**: Modify ProgressDialog to use DialogComponent and ProgressBar
- [x] **Check for regression**: `this.openmct.overlays.progressDialog` is also used in `NotificationBanner.vue` (2nd image)
- [x] **Styles**: Add correct styles to modal

Screen Shot 2019-09-19 at 3 17 59 PM

Screen Shot 2019-10-31 at 3 20 41 PM

### CODE REVIEW

**Comment by deeptailor** [comment]
@nikhilmandlik - What's the status of this pr?

**Comment by nikhilmandlik** [comment]
@deeptailor Need help from @charlesh88 for styles.
Also not sure about use of `progressDialog` in `NotificationBanner` file and how this change affects it.

**Comment by charlesh88** [comment]
@nikhilmandlik How do I get the dialog to appear when running locally?

**Comment by nikhilmandlik** [comment]
> @nikhilmandlik How do I get the dialog to appear when running locally?
@charlesh88 
1. Open BrowseBar.vue
1. Navigate to `saveAndFinishEditing` function
1. Wrap following code with `setTimeout` (or replace with code from next step)
`dialog.dismiss();`
`this.openmct.notifications.info('Save successful');`
1. You Increase time from `5000` (3 secs) to desired amount
`setTimeout(()=>{
                            dialog.dismiss();
                            this.openmct.notifications.info('Save successful');
                        }, 5000);`

**Comment by deeptailor** [comment]
## Reviewer Checklist
Changes appear to address issue? Y
Appropriate unit tests included? Y
Code style and in-line documentation are appropriate? Y
Commit messages meet standards? Y

**Comment by nikhilmandlik** [comment]
**Testathon:** 
to reproduce locally:

1. Open BrowseBar.vue
2. Navigate to saveAndFinishEditing function
3. Wrap following code with setTimeout (or replace with code from next step)
4. dialog.dismiss();
5. this.openmct.notifications.info('Save successful');
6. setTimeout(()=>{ dialog.dismiss(); this.openmct.notifications.info('Save successful'); }, 5000);
7. You Increase time from 5000 (5 secs) to desired amount

**Comment by charlesh88** [comment]
Testathon 12-06-19: verified fixed.

**Pull request merged**
