### PR TITLE
Search fix identifier

### LINKED ISSUE #4946: In Memory Search performance and namespacing issues
#### Summary
* in memory search re-indexes on every tree expansion (even same node)
* in memory search does not work for namespaces

#### Expected vs Current Behavior
Each object should be indexed once on load. Objects should be re-indexed only on name change or composition change.

#### Steps to Reproduce
Over-indexing
1. Load Open MCT
2. Open console browser and open source file `inMemorySearchProvider.js`
3. Set a break point in the index function definition
4. expand a node in the object tree
5. Expect code does not stop at set breakpoint

No Namespacing
1. Gain access to deployment with namespaces
2. Test search

#### Environment

* Open MCT Version: 2.0.1
* Deployment Type: VISTA to test namespacing
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [] Is there a workaround available?
- [] Does this impact a critical component?
- [] Is this just a visual bug with no functional impact?

### PR DESCRIPTION
**Pull request by davetsay**
Closes #4946

### Describe your changes:
Watch on name and composition independently because * observer triggers when not supposed to.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Review by scottbell — DISMISSED** [review]
Looks good!

**Comment by scottbell** [comment]
> Looks good!

Though we'll need to fix the tests...

**Comment by scottbell** [comment]
> > Looks good!
> 
> Though we'll need to fix the tests...

Did that!

**Review by nikhilmandlik — APPROVED** [review]
LGTM

**Review by scottbell — APPROVED** [review]

**Comment by akhenry** [comment]
@davetsay Should this still be in draft?

**Pull request merged**
