### PR TITLE
[Imagery] Brightness/contrast controls

### PR DESCRIPTION
**Pull request by VWoeltjen**
Work-in-progress for #1324. 

Sliders are currently below the image and have no labels (assigning to @charlesh88 to handle markup/UX.) The minimum is at right and maximum is at left for these sliders, which is backwards from what I'd expect (wonder if some surrounding CSS could be influencing this?)

screen shot 2016-11-14 at 12 21 03 pm

Todos:

- [x] Sketch in functionality
- [x] Get markup revisions from @charlesh88 (on this branch is fine)
- [x] Fix the reversed left-right behavior of range sliders (if that's still necessary)
- [x] Units tests
- [x] Code style
- [x] JSDoc

### CODE REVIEW

**Comment by charlesh88** [comment]
Reversing is probably occurring from the RTL CSS statement used for the timestamp to make it truncate from right to left. I'll look into it.

**Comment by charlesh88** [comment]
Jay mentioned just now that he thinks we really need a histogram as well and has asked us to look into this. The histogram would need to update as the user manipulates the slider controls. This changes the interaction model - the histogram shouldn't be shown until the user indicates they want to manipulate the brightness or contrast, which means this action should be modal. This could happen in an overlay context, or we introduce a modal wrapper for the controls and histogram as a new type of overlay.

@VWoeltjen Let's chat about a solution here - Jay would like to know what the incremental impact would be.

**Comment by VWoeltjen** [comment]
Once we cross over from things that have built-in browser support (like brightness/contrast) we'll need to look at libraries, because the image handling/processing code becomes much more complicated. In terms of difference, I'd estimate this becomes someone's primary focus for a sprint instead of for part of a week.

**Comment by charlesh88** [comment]
I am no longer seeing pan and zoom controls in imagery - did this get disabled?

**Comment by larkin** [comment]
I don't believe imagery ever supported pan and zoom.

**Comment by VWoeltjen** [comment]
Yes, I saw markup for the controls in there, but I don't recall this ever being implemented

**Comment by charlesh88** [comment]
Ah, in my universe we did implement that. No prob, I'll remove those elements.

**Comment by akhenry** [comment]
> Ah, in my universe we did implement that. 

ie. "I reject your reality, and substitute my own!"

In all seriousness, I have a vague recollection of an intern working on imagery pan/zoom last year, no?

**Comment by charlesh88** [comment]
@VWoeltjen My work has been pushed to the branch, see notes in #1324.

**Comment by VWoeltjen** [comment]
Ready for review! A couple of notes:

* Added `filters` as an attribute that goes through `mct-background-image` because simply adding it as a `style` or `ng-style` on the relevant element results in the background image style being overwritten (or vice versa)
* I reverted the change to example images because some weren't loading for me, and they're also on various non-NASA sites (so who knows what those links will point to tomorrow.)

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

**Comment by larkin** [comment]
# Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
