### PR TITLE
[CLA on File] Update README.md

### PR DESCRIPTION
**Pull request by SimonWaldherr**
remove LGTM-Badge - Sadly, LGTM.com is no longer available

### Describe your changes:
remove LGTM-Badge

https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

```
16th of December: LGTM.com will be shut down

From the 16th of December, LGTM.com will no longer be available. This includes but is not limited to:

[LGTM.com code quality badges](https://lgtm.com/help/lgtm/adding-badges-to-project-readme-files)
The LGTM query console (including historical results)
The LGTM documentation
All LGTM.com APIs
```

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by ozyx** [comment]
Thank you so much for your contribution! If you haven't already, please complete and submit a [Contributor License Agreement (CLA)](https://github.com/nasa/openmct/discussions/3821). This is required before we can approve/merge your code.  Thanks again, we will be taking a look at this shortly!

**Comment by davetsay** [comment]
@SimonWaldherr , have you been able to submit a CLA yet? see @ozyx 's previous comment. Thanks!

**Comment by SimonWaldherr** [comment]
Hello @davetsay,
I sent it in December. I received the following response from Kimberly Minafra:
"Thank you - we will work to process this and inform the developers."
If I did something wrong or something is still missing, please just contact me again.
Thank you very much

**Comment by jvigliotta** [comment]
@SimonWaldherr I'm double checking your CLA. I'll let you know once I get a status. Thanks!

**Comment by jvigliotta** [comment]
@SimonWaldherr we have your CLA on file now, thank you for your submission!

**Review by ozyx — APPROVED** [review]
LGTM! (ha)

Apologies for the delay. Thanks again for this contribution!

**Pull request merged**
