### PR TITLE
[Clocks / Timers] adds stop, pause, resume functionality. Fixes #623

### LINKED ISSUE #623: Timers need a stop button
<p>Once I start a timer, there doesn't seem to be a way to ever stop it, only restart it.  Would be nice to be able to stop it when I don't need it anymore.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1326
Originally created: Tue, 23 Jun 2015 10:15:50 -0700
Updated: Thu, 21 Jan 2016 14:51:53 -0800

### PR DESCRIPTION
**Pull request by DocJava**
Added ability to stop, pause and resume the Timer. 

## Author Checklist

Changes address original issue? Y
Unit tests included and/or updated with changes? Y
Command line build passes? Y
Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by akhenry** [comment]
@DocJava Thanks for looking at this! The approach looks good, going to make some specific suggestions inline.

**Comment by akhenry** [comment]
@charlesh88 Could you point your peepers at the style and icon changes here?

**Comment by charlesh88** [comment]
I've pulled and will run this locally now.

**Comment by charlesh88** [comment]
Big props to you @DocJava  - great work! Here are my comments on reviewing a local build, in order of priority:
- The Timer properties dialog displays two elements that need to be removed, as there's no user action for them: `PauseCheck` and `TimeOfPause`.
screen shot 2017-01-17 at 3 00 00 pm

- A paused timer really needs to articulate its state. Timers are shared amongst users, so a user must be able to clearly see if a Timer is paused or not when glancing at it. We need the ability to discern the current state of the Timer, whether it's paused or playing. The best way to do this would be to dynamically define that by adding `paused`, `playing` and `stopped` to the outermost div's class definition in timer.html, line 22. As the designer, I can then come in and play around with the best CSS to apply to whichever elements to visually articulate that.
- It'd be really great if we could replace the "Restart at 0" button in the display itself with a toggled Play/Pause button. The stuff in the context menu is fine as is. 

@akhenry Please add any additional detail or clarification needed.

**Comment by DocJava** [comment]
Should we switch out the plus/minus sign for a red /green letters that way we can save real estate, then we can use that space for the play/pause/stop peek?

**Comment by charlesh88** [comment]
Not a bad idea, but nope: that conflicts with some operations standards that we're in line with. Red and green have real meaning in this world, and we need the + and - to quickly see which direction the timer is going. Restart at 0 is fine in the context menu and would be better replaces with pause/play.

On the icons, forgot to mention: we already have a box icon (think it's `icon-box`) so I'd like to roll back the CSS changes (if I'm not missing something) in favor of avoiding duplication.

- Charles

On Jan 17, 2017, at 4:23 PM, DJ Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Should we switch out the plus/minus sign for a red /green letters that way we can save real estate, then we can use that space for the play/pause/stop peek?

**Comment by akhenry** [comment]
@DocJava 
> The Timer properties dialog displays two elements that need to be removed

This is because they are defined as `properties` of the `timer` type in `bundle.js`. `properties` is intended for describing user-editable model properties. Not sure whether the intention was to make these user-editable, but they don't need to be. I think [the docs](https://nasa.github.io/openmct/docs/guide/#types-category) could be clearer here.

> A paused timer really needs to articulate its state

Propose we explicitly record current state in a model property. @charlesh88s' suggestions for states are good, ie. `paused`, `playing` and `stopped`. Should replace the `paused` boolean if we use this approach. This state could then be added to the outer div with something like
``` html
<div class="l-time-display l-digital l-timer s-timer s-timer-{{model.state}}" ng-controller="TimerController as timer">
```
Note the `s-timer-{{model.state}}`

> It'd be really great if we could replace the "Restart at 0" button in the display itself with a toggled Play/Pause button.

We need to change how the relevant action is selected to do this. The [actionKey used to retrieve the relevant action](https://github.com/DocJava/openmct/blob/165bd4f6389686c46eb9ecf6680035686eb9cbe6/platform/features/clock/src/controllers/TimerController.js#L76) in `TimerController.updateObject` would need to be changed to `timer.pause`.

Once again though, really nice work so far!

**Comment by DocJava** [comment]
Thank you both for your comments and feedback.

@charlesh88 
I will roll-back the new stop icon thank you. I see that I was using it actually and just did not realize it, strange.

to clarify - we want to see the +- indicator along with a Playing, Paused, or Stopped indicator, along with a play or pause button?

Stopping the timer turns the text back to --:--:-- Which should be a good indication that the timer is not going. And if we persist the alternating play/pause buttons (instead of hiding it like is currently done with the restart button) then that would help to indicate its state? Like a music player, if you see the play button, you know it's paused, if you see the pause button, you know it's playing.

We can then replace the hidden restart button with a hidden stop button. 

Thoughts from either of you would be appreciated 

@akhenry 
> The Timer properties dialog displays two elements that need to be removed
I did this because I thought it was how you created a variable with data that you wanted to persist across browser closing. I think I see how to create global variables properly now. 

> Propose we explicitly record current state in a model property. 
Can do. Thank you!

**Comment by DocJava** [comment]
So far I have: 
- Removed the empty timer properties (thank you again for that)
- Swapped the "Restart at 0" button for a Play/Pause button (that always shows, hopefully indicating state that way)
- Swapped the model.paused variable for a model.timerState variable options are 'play', 'paused',  or undefined.

As for the suggestion for the timer.html class, the only changes I needed to make was making the Play/Pause button persist which involved removing "control" from the class field on line 26 . the rest of the changes happened in the TimerController class. The logic was all there I just swapped out restart for pause. (not exactly true, currently everything is a bit clumped together, will get to that last)
image

I left the stop button out of the view, not hidden or anything. It is only in the context menu, thoughts?

I am currently adding / revising the tests.

**Comment by charlesh88** [comment]
Hi @DocJava great progress. Some requests:
- We don't want pause/play button to persist; it should maintain the same peek behavior as the restart button did.
- If it's easy to add the Stop button as well to the peek, that'd be great; otherwise, as is in the context menu is fine. 
- Still need to have a current state (paused, playing, stopped) added to the outer wrapper as previously described. This is probably the most important element for me.

Again, big thanks for the great work!

**Comment by DocJava** [comment]
Hey Everyone, THank Thank you for everything so far and I apologize if I have been going against the grain on what is common there. This is my first time dealing with angular and I have not fiddled with javascript in years. 

- Play pause button no longer persists, but peeks instead
- Stop button also peeks
- Current state displays as greyed Play / Pause / Stop(by default) icon
I currently have the state icon to the left of the sign icon. Were there any preferences on where it was supposed to be placed?
Current layout: 
image

image

Were there any preferences on what icon should go where? 

Most important question: I have realized that my tests are NOT running. According to https://nasa.github.io/openmct/docs/tutorials/ "npm install" should run the tests when building. but that command should only need to run once. I am using Webstorm to dev  on a Windows PC for this. How do I run overall tests and also how do I run individual tests? Thank you.

**Comment by charlesh88** [comment]
@DocJava Awesome, and thanks so much for the hard work. I'll move the icons around a bit, I want to play with layout myself a bit. Were you able to insert a state class (paused, playing, etc.) into the outer wrapper? That's the last important ask I'd throw into the mix here.

@akhenry Can you help with @DocJava 's question about testing?

**Comment by DocJava** [comment]
@charlesh88 Tis an honor! Thank you for all for being patient with me. The changes have not been committed yet, I am currently working on the unit tests.

> Were you able to insert a state class (paused, playing, etc.) into the outer wrapper? 

I am not sure what you are requesting here. I have a timerState variable setup to indicate what state the timer is in ('playing', 'paused', 'stopped'). Instead of writing a class for it I just added it to the model that was already there, not sure if that was the right call. I will have changes posted tomorrow night hopefully. Almost done writing the new tests. 

@akhenry I figured out the testing, information was in the README

**Comment by charlesh88** [comment]
@DocJava Fantastic! I'll grab timerState and throw that into the markup where I want it. This is really cool - thanks so much for responsiveness. Looking forward to your push when you're done with unit tests.

**Comment by charlesh88** [comment]
@DocJava I just did a pull, and saw that a Paused timer displays both Pause and Play "play actions" in its context menu. Pause should be suppressed in that case, with other options shown. A stopped timer displays only Start, which is correct. So:

Timer State | Play Actions in Context Menu
---- |----
Stopped | Play
Playing | Pause, Stop, Restart at 0
Paused | Play, Stop, Restart at 0

Again, thanks!

**Comment by DocJava** [comment]
@charlesh88 Thank you for the heads up! Just now seeing your last comment. Luckily those were addressed in most recent push.

**Comment by charlesh88** [comment]
@DocJava You da man, awesome.

**Comment by charlesh88** [comment]
@DocJava I've forked your stuff into a topic branch, did my design-thing, and put 
#1416 in for our combined efforts to get merged into master. This was great work and adds a really nice feature to Timers. Thanks so much! Cheers, and looking forward to more hopefully.

Note that we'll close this PR after #1416 gets merged.

**Comment by akhenry** [comment]
@DocJava Thanks again for all of your work on this.

This still needs a code review before we can merge it. I'm going to do the code review in #1416 so I am looking at the right code. 

Since this might require some code changes to address any review issues, the best bet might be to branch off charlesh88-open623 and create a new PR with the code changes that has charlesh88-open623 as the merge target.

**Comment by akhenry** [comment]
Closing this PR. work is continuing in #1416

**Pull request closed without merging**
