### PR TITLE
Add modelService compatibility adapater

### PR DESCRIPTION
**Pull request by larkin**
Implements an adapter to ensure that objects registered via the new API can be fetched via the model service.  Resolves a bug where objects provided via the new API would not be included in search results.

The changes here to the ObjectProvider `get` signature bring us back in line with API docs, but I need to look at the WARP code and see if this will cause a regression with the new provider.

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Think the ObjectAPI change will cause a regression in WARP, but should be trivial to fix. Passing `namespace` in to `get` is a little redundant but there are some benefits (you could reuse the same provider instance for multiple namespaces, I guess) and it does make the interfaces more uniform, too.

**Comment by larkin** [comment]
@VWoeltjen I have a PR for the WARP regression incoming.

In addition to consistency, passing the `identifier` is necessary for the fallback provider to do it's job correctly.  Otherwise it's incapable of dealing with old style model providers.

**Comment by larkin** [comment]
# Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

Sending to @VWoeltjen for R&I, as it has to be merged in concert with https://developer.nasa.gov/ResourceProspector/warp/pull/245.

**Comment by VWoeltjen** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? No, but in the scope of #1218 
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
