### PR TITLE
[Documentation] Fixed module reference

### PR DESCRIPTION
**Pull request by bolkhovsky**
`ExampleTelemetryProvider` references `ExampleTelemetrySeries` module. It is actually located in the same src folder.

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Thanks for pointing that out and submitting a PR! Before we can merge, we need a signed [Contributor License Agreement](http://nasa.github.io/openmct/contributing/#contributor-license-agreement) (follow the link for instructions on completing and submitting this)

**Comment by bolkhovsky** [comment]
@VWoeltjen hi, the License Agreement should be signed and sent this week! btw, have no idea why ci failed to build...

**Comment by VWoeltjen** [comment]
I think the CI failures are due to #1214, which has been fixed on master. If you merge from master to this branch, I would expect the checks to pass.

One more small note - could you amend the latest commit here with an "addresses #1206" comment? It provides some traceability between changes and issues.

**Comment by akhenry** [comment]
@bolkhovsky Thanks again for your contribution. Have you had a chance to review and sign the CLA? Once we have that (the email address to send it to is at the bottom of the form), we can review and merge this PR.

**Comment by bolkhovsky** [comment]
@akhenry Hi Andrew, it's waiting to be signed by our CEO. Will try to force it.

**Comment by akhenry** [comment]
@bolkhovsky No problem at all. Are you using the [corporate CLA](https://nasa.github.io/openmct/contributing/corp-cla-open-mct.pdf)? We can also be contacted at arc-dl-openmct@mail.nasa.gov if you have any questions about the CLA. Also, if you're able to discuss your project we'd love to hear about it.

**Comment by VWoeltjen** [comment]
CLA received - thanks!

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A (changes in examples only)
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
