### PR TITLE
Suppress commented code on the github repository

### PR DESCRIPTION
**Pull request by medinae**
Code quality conventions

### CODE REVIEW

**Comment by akhenry** [comment]
@medinae Hi, thanks for your contribution! Before we can merge it, we need a contributor license agreement to be signed. Could you please complete [this form](https://nasa.github.io/openmct/contributing/ind-cla-open-mct.pdf), and follow the instructions at the bottom of it. When emailing it back, could you please also cc [arc-dl-openmct@mail.nasa.gov](mailto:arc-dl-openmct@mail.nasa.gov)

**Comment by medinae** [comment]
I'll read it tonight. Thanks @akhenry

**Comment by medinae** [comment]
@akhenry Done 👍

**Comment by akhenry** [comment]
@medinae good stuff, thanks for that. Typically we would also require an author checklist [as per the "contributing" guide](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md#check-lists), but as there are no changes to active code I'll forgo it in this case.

Thanks again for your contribution.

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? NA - removed commented code
3. Code style and in-line documentation are appropriate? NA
4. Commit messages meet standards? Y

**Pull request merged**
