### PR TITLE
Make Tabs eager loading configurable but default to false

### LINKED ISSUE #7198: tabs should default to not load eagerly
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by davetsay**
Closes #7198 

### Describe your changes:
* make tabs eager load configurable
* default is eager load false changed from eager load true
* change dropdown to toggle

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Is this a breaking change to be called out in the release notes?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@davetsay let's sync with @scottbell next week to talk about this change

**Review by unlikelyzero — CHANGES_REQUESTED** [review]
This needs a test in Open MCT YAMCS and should be called out in the release notes

**Comment by davetsay** [comment]
> This needs a test in Open MCT YAMCS and should be called out in the release notes

@unlikelyzero ,
It has a unit test to test the only change, which is what type of tab the form defaults to. Why would this need a test in Open MCT YAMCS?

It does not change the behavior of the tabs object what so ever. Why is it a breaking change?

**Review by scottbell — APPROVED** [review]
Good work @davetsay! It does what it says on the tin. Here's before:
before

Here's after without setting the options installing the tab plugin (defaulting eager loading to false):
after-default-true

And here's with the option in the plugin with `eagerLoad` set to `true`:

after-default-true

@davetsay I didn't see any testing notes on the ticket, so I [put together a draft](https://github.com/nasa/openmct/issues/7198#issuecomment-1886613198). Let me know if it looks good to you.

**Review by unlikelyzero — APPROVED** [review]

**Pull request merged**
