### PR TITLE
Fix visible toolbar overflow

### LINKED ISSUE #7036: Display Layout editing tools overlaps inspector
#### Summary
display layout editing tools are overlapping the inspector area

#### Expected vs Current Behavior
display layout editing tools should not overlap the inspector area

#### Steps to Reproduce

1. create a display layout
2. click + and add any layout object to the layout
3. select the object if necessary and verify you see the editing tools in the toolbar
4. make the inspector and tools in the main view overlap (zoom the window, reduce the size of the window, drag the inspector left)
5. observe tools and inspector text overlaps

#### Environment

* Open MCT Version: latest
* Deployment Type: 
* OS:
* Browser: chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
image

### PR DESCRIPTION
**Pull request by charlesh88**
Closes #7036.
- CSS fix to prevent toolbar overrun of main view area.
- Added `overflow: hidden` to __pane-main > .l-pane__contents.
- Added visual test for toolbar overflow

Closes 

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [X] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [X] Command line build passes?
* [X] Has this been smoke tested?
* [X] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Review by davetsay — APPROVED** [review]
LGTM

**Review by unlikelyzero — CHANGES_REQUESTED** [review]
needs test

**Comment by charlesh88** [comment]
@unlikelyzero How do I create a test for this? Is this critical now for a purely visual element that we're trying to get under the limbo bar?

**Comment by davetsay** [comment]
> needs test

Created ticket to address needing visual test. #7178

**Comment by ozyx** [comment]
> needs test

visual test added

**Review by unlikelyzero — APPROVED** [review]

**Pull request merged**
