### PR TITLE
Have in-memory search indexer use composition API

### LINKED ISSUE #5549: The in-memory search indexer is observing mutation of the composition property.
https://github.com/nasa/openmct/blob/2fa053e80ca7013aeb7ff94b57ac81e47c6197d6/src/api/objects/InMemorySearchProvider.js#L315

This is an unreliable method of detecting composition changes as not all objects will use the composition property to define their composition.

Instead, the Composition API should be used. It provides observers for composition changes that are agnostic of the underlying data structure.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #5549 

### Describe your changes:
Used composition API to detect changes in children.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@scottbell we already have test coverage for your testing notes. Can you figure out why this bug was not caught and what we can do to fix our coverage gap?

**Comment by scottbell** [comment]
> @scottbell we already have test coverage for your testing notes. Can you figure out why this bug was not caught and what we can do to fix our coverage gap?

It’s not really a bug that a user is going to see, it’s just we’d rather use the composition API than directly using the composition attribute. The testing notes are basically just to make sure search works like it used to.

**Comment by unlikelyzero** [comment]
In that case, would you mind adding some coverage for this?

**Comment by scottbell** [comment]
> In that case, would you mind adding some coverage for this?

I guess that’s what I’m saying - it’s not something we can really capture in a test per se.

**Comment by unlikelyzero** [comment]
Okay got it! Part of the reason I'm saying this is I just rewrote your test in the visual suite because it's using a clock object. Would you mind ensuring that we have coverage for this in the functional test suite?

**Comment by scottbell** [comment]
> Okay got it! Part of the reason I'm saying this is I just rewrote your test in the visual suite because it's using a clock object. Would you mind ensuring that we have coverage for this in the functional test suite?

We do! The clock object isn’t really pertinent, but having objects in folders is. The existing e2e tests ensured my refactoring was working properly.

**Comment by unlikelyzero** [comment]
Okay awesome. I need to write some more documentation about visual testing. We should avoid using any clock or timer objects as those would visually change between snapshots

**Comment by scottbell** [comment]
Investigating test failures related to `timelist`. Apparently the way the test adds compositions in causing issues with the `InMemorySearch`.

**Comment by scottbell** [comment]
> Investigating test failures related to `timelist`. Apparently the way the test adds compositions in causing issues with the `InMemorySearch`.

Fixed. The `timelist` test as firing an `add` composition event inside of its stubbed `load` composition function. This was causing the `InMemorySearch` indexer to constantly re-index the object. I moved these `add` emissions to the individual tests instead, and that fixed the test.

**Review by akhenry — APPROVED** [review]
Looks good, thanks!

**Comment by scottbell** [comment]
This PR was reverted.

**Pull request merged**
