### PR TITLE
URL validation Removed

### PR DESCRIPTION
**Pull request by aayusharora**
Issue #2168

 - Removed the validation of regex for creating Hyperlink.
 - Make the field only required

### CODE REVIEW

**Comment by aayusharora** [comment]
@larkin Can you please check this now?
Thanks for the help :)

**Comment by larkin** [comment]
@aayusharora Great! needs author checklist before I can approve and merge.

**Comment by aayusharora** [comment]
Author Checklist @larkin @akhenry 

- [x] Changes address original issue? 
Addressing Issue #2168
- [x] Unit tests included and/or updated with changes? 
All test passing 
- [x] Command line build passes? 
Build passing 
- [x] Changes have been smoke-tested?
Yes

**Comment by aayusharora** [comment]
Hi @larkin @akhenry 
Can you please check this once?

**Comment by larkin** [comment]
# Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/a
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
