### PR TITLE
[Views] Update ViewProvider API

### PR DESCRIPTION
**Pull request by VWoeltjen**
Expect contexts, not simple objects, for view api. First step of refactors for selection-based inspection, #1126 and #1307

See https://github.com/nasa/openmct/issues/1126#issuecomment-248127507
for rationale.

### Author Checklist

1. Changes address original issue? Partially
2. Unit tests included and/or updated with changes? See #1218 
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by VWoeltjen** [comment]
First of a few PRs related to #1307. This just updates the APIs to use contexts instead of domainObjects. I've favored consistency over specificity here, but that does add some interface depth to SPIs when they are not universally needed.

**Comment by VWoeltjen** [comment]
Note mostly-to-self, used the following snippet to check the `mainViews` extension point after the change:

```js
            openmct.mainViews.addProvider({
                canView: function (context) {
                    return context.item.type === 'folder';
                },
                view: function (context) {
                    return {
                        show: function (element) {
                            var span = document.createElement('span');
                            span.textContent = context.item.name;
                            element.appendChild(span);
                        },
                        destroy: function () {}
                    };
                },
                metadata: function (context) {
                    return {
                        name: "Name view",
                        description: "It shows you the name of a folder.",
                        key: "best-view-ever"
                    };
                }
            });
```

**Comment by larkin** [comment]
Given the potential depth of the selection API, I'd prefer not to make pre-emptive changes to other parts of the API until we get to the point where selection is well defined and we are able to talk about concrete commonalities and differences with the other registries.  Otherwise, I'm afraid the continued evolution of the selection API may lead to an excessive number of breaking changes in the `mainView`.

Do you have any concerns with only implementing the `context` object for the selection registries at this time?

**Comment by VWoeltjen** [comment]
Closing for now; we've deferred View APIs a bit and this may not be along a useful direction there. Can reopen if needed.

**Pull request closed without merging**
