### PR TITLE
[BUILD] Replace Prepublish with Prepare

### PR DESCRIPTION
**Pull request by ev1stensberg**
* https://docs.npmjs.com/misc/scripts#prepublish-and-prepare 

# Rationale 
This PR removes one less warning in the console, which is better for developer experience.

### Changes address original issue? 
N/A
### Unit tests included and/or updated with changes? 
N/A
### Command line build passes? 
Y
### Changes have been smoke-tested? 
Y

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Thanks! I've been watching npm/npm#3055 and wanting to do this because it would make some of our dependent projects simpler. I see the build on CircleCI is failing with this change. It looks like bower dependencies are never collected; is `prepare` not invoked during a local `npm install`?

**Comment by VWoeltjen** [comment]
Looks like the problem here is that CircleCI is using npm 2.14.12, whereas `prepare` is only supported in 4.0.0+. If you add some [engines](https://docs.npmjs.com/files/package.json#engines) configuration to package.json along with this PR, I believe CircleCI should pick up on that and use a more recent npm

**Comment by ev1stensberg** [comment]
Done @VWoeltjen . Tried some workarounds before it works. CircleCI v1 is much easier than v2 😆 Do you want me to update `package.json` with engines too?

**Comment by VWoeltjen** [comment]
Let's leave `package.json` alone if CircleCI isn't picking up on it. Thanks for working through that CircleCI configuration, it definitely saved some time for us (and this change is going to make some of our downstream builds simpler, too). Much appreciated!

### Reviewer Checklist

1. Changes appear to address issue? PR is self-documenting (rationale in initial PR and above)
2. Appropriate unit tests included? N/A (changes to build configuration only)
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
