### PR TITLE
Context menu actions

### PR DESCRIPTION
**Pull request by akhenry**
This PR relates to the changeset in https://github.com/nasa/openmct/compare/74faf1bd48d26f425fb12bd0d02c1f9d16efc35c...9ae4e66c91bd29f256f777bbd39fdde35f3c8018 + the deltas in this PR

Todo:
* [x] Finish jsdoc
* [x] Launch context menu from arrow menu
* [x] Update objects in `objectPath` on mutation.

### CODE REVIEW

**Comment by larkin** [comment]
In general, use-before-define is a deviation from our [code guidelines](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md#code-guidelines) and should be used sparingly.

@akhenry notes on the diff: 
* https://github.com/nasa/openmct/compare/74faf1bd48d26f425fb12bd0d02c1f9d16efc35c...9ae4e66c91bd29f256f777bbd39fdde35f3c8018#diff-cdcc4ca73e7d67d752918d2db4dd9ac6R2 don't use before define
* https://github.com/nasa/openmct/compare/74faf1bd48d26f425fb12bd0d02c1f9d16efc35c...9ae4e66c91bd29f256f777bbd39fdde35f3c8018#diff-99bf719c45547a2a6e959e529854b8a0R279 don't use before define.
* https://github.com/nasa/openmct/compare/74faf1bd48d26f425fb12bd0d02c1f9d16efc35c...9ae4e66c91bd29f256f777bbd39fdde35f3c8018#diff-caf4d9b056212f9cd09a8587c57f2770R88 It's a little hard to understand what this code is doing from reading it.  is it possible that these variables could be renamed, or add a clarifying comment?

Otherwise looks good, let me know when you've wrapped up this PR and I'll review it's contents.

**Comment by akhenry** [comment]
Links to diffs don't work :(

**Comment by larkin** [comment]
@akhenry i fixed the diff links, check now.

**Comment by larkin** [comment]
Looks good!

**Pull request merged**
