### PR TITLE
[Inspector] Display notes in the inspector if there are notes found on the domainObject

### LINKED ISSUE #4430: Domain object properties Notes don't appear in Inspector, but should
#### Summary
This is raised in importance to solve a functional ask to allow users to add authorship and a version number to composed displays in Open MCT.

#### Expected vs Current Behavior
This used to function, filing this as a regression bug.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Edit properties on any composed view and add any content in the Notes field. Save and exit that dialog.
2. Observe: the Notes content is not shown in the Inspector, but should be.

#### Environment
* Open MCT Version: 1.7.8
* Deployment Type: any
* OS: any
* Browser: any

#### Additional Information
image

image

### PR DESCRIPTION
**Pull request by khalidadil**
Fixes #4430 

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [X] Changes address original issue?
* [X] Unit tests included and/or updated with changes?
* [X] Command line build passes?
* [X] Has this been smoke tested?
* [X] Testing instructions included in associated issue?

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@khalidadil  would you mind linking to the github issue?

**Comment by khalidadil** [comment]
> @khalidadil would you mind linking to the github issue?

yup, should be linked now!

**Comment by khalidadil** [comment]
Here's a screenshot of the inspector after the change:
Screen Shot 2021-12-06 at 1 55 48 PM

**Comment by akhenry** [comment]
@charlesh88 Does this look ok to you?

**Review by davetsay — APPROVED** [review]
LGTM

## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | Y |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |
| Has associated issue been labelled `unverified`? | Y |

**Review by charlesh88 — APPROVED** [review]
I made a very small CSS change to remove the break-anywhere text breaks in the Inspector, so now the Notes in the Inspector are more readable. With that, LGTM.

**Comment by khalidadil** [comment]
> I made a very small CSS change to remove the break-anywhere text breaks in the Inspector, so now the Notes in the Inspector are more readable. With that, LGTM.

Thanks @charlesh88!

**Review by davetsay — APPROVED** [review]

**Pull request merged**
