### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by jfcg**
Add Github CodeQL security checks for Javascript.

In my fork under `/security/code-scanning` I see:

openmct

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@jfcg Thank you for this contribution. In reviewing the PR, we came to this article that explains some previous use cases at NASA. https://semmle.com/case-studies/semmle-nasa-landing-curiosity-safely-mars

Do you have previous experience and success with the javascript codeQL analysis? Would this be something that would need to run every commit or something better suited to run per-merge, pre-release, or ad-hoc?

**Comment by jfcg** [comment]
Yes, codeql did find JS bugs on other open-source projects. It could be set to run on every push to master. Some projects prefer only on release branches.
I also simplified the file and added default permissions from github's default template.

**Comment by unlikelyzero** [comment]
@jfcg that is great to hear. For now, we can run this ad-hoc as we have time to analyze the results. Would you mind changing the event type to `workflow_dispatch`?

**Review by unlikelyzero — APPROVED** [review]
Thank you for this contribution!

**Comment by jvigliotta** [comment]
HI @jfcg ! Before we can merge in your code, we will need you to follow the steps here: https://github.com/nasa/openmct/discussions/3821 once we have your CLA on file, we can merge this in. Thanks!

**Comment by jfcg** [comment]
filled the cla and sent it. cheers..

**Comment by akhenry** [comment]
@jvigliotta @unlikelyzero I am happy for this to be merged provided we have a signed CLA and this is initially only run ad-hoc.

**Comment by jvigliotta** [comment]
> filled the cla and sent it. cheers..

Hey @jfcg can you send that in again? I'm not seeing you on the list and we'd love to get this merged in.

**Comment by jvigliotta** [comment]
@jfcg I'm enquiring if we have your CLA on record with our legal folks, were able to send another one in?

**Comment by jfcg** [comment]
i did fill/email it, but im told i needed to print/sign/scan/email back so did not have time to do that

**Comment by akhenry** [comment]
@jvigliotta to verify that what the CLA we have on file for @jfcg is sufficient to merge.

**Comment by jvigliotta** [comment]
@akhenry I've checked, we do not have one on file.

**Comment by jvigliotta** [comment]
@jfcg would you have time to send another signed one in? We would love to get this merged in.

**Comment by jfcg** [comment]
- i don't have time to print/sign/scan/email your cla
- the planet does not have resources to waste for stuff like this

so closing..

**Pull request closed without merging**
