### PR TITLE
[Notifications] Fix and harden the NotificationService

### PR DESCRIPTION
**Pull request by BogdanAlexandru**
This already fixes https://github.com/nasa/openmct/issues/1221, but it's still WIP until I pass through it some more (it's gotten way late) and get feedback from you.

Highlights:
- The bug mentioned in #1221 got fixed.
- Info notifications now get special treatment as discussed in the issue.
- New tests for the `NotificationService`: [pic](http://i.imgur.com/9SNhXjt.png)

These cover the common use cases and have helped me spot bugs like the service using the custom timeout value properly for errors and alerts, but not for infos, while making info act special. I'll go through them again to see if I missed anything relevant, and if the multiple notification tests can also get some cleanup.

I found that embedding auto closing info in the `notification` object (see `NotificationService.notify.notification`) was pretty clean but the object is also what is given back from the service and what callers are expected to work with. I don't know how much of a big deal this is, being noise & implementation details in a public object. I think we can find workarounds if needed, like moving the info somewhere else (inside the model? I'd keep the info attached directly to the notification somehow and avoid mapping notifications to info in other ways)

Thoughts?

### CODE REVIEW

**Comment by BogdanAlexandru** [comment]
@akhenry There was a bunch of confusion and difficulty coming from the fact that `autoDismiss` can be either a bool or a number at different points in time so moving all the decision logic in one place where I could make the fewest assumption about `autoDismiss` felt like the way to go. I agree with your comments though; now that the tests are in better shape, making `autoDismiss` be less confusing should be less bug prone 👍

**Comment by akhenry** [comment]
@BogdanAlexandru No worries. Let me know when you're happy for me to take another look.

**Comment by BogdanAlexandru** [comment]
I think the essential stuff is covered. Let me know if you see any issues.

## Author Checklist
- Changes address original issue? Y
- Unit tests included and/or updated with changes? Y
- Command line build passes? Y
- Changes have been smoke-tested? Y

**Comment by akhenry** [comment]
@BogdanAlexandru This looks great, thanks. We are in a code chill at the moment and we have a lot of ground to cover already in testing this sprint, so I'm going to defer merging this until next sprint.  It's good to go though.

Supporting custom timeout periods in the `NotificationService` adds complexity with very little benefit. I don't imagine anyone will ever use it, and I'd like to remove it as it simplifies the code. The default timeout period is configurable, so it can be customized on a per-mission basis if need be. Moreover, if someone desperately needs a custom timeout period, it could be achieved by setting `autoDismiss` to `false` and creating an external timeout that invokes `.dismiss()`

@BogdanAlexandru In brief, if you want to remove custom timeouts to simplify this a little, feel free to do it in this PR. Otherwise I'll create an issue for someone to take a look at it in the future. No big deal either way. Thanks again!

**Comment by BogdanAlexandru** [comment]
@akhenry I'll do it in this PR, removing code and complexity is my favoritest thing ever.

**Comment by BogdanAlexandru** [comment]
Done & done.

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Comment by akhenry** [comment]
Merged. Thanks @BogdanAlexandru

**Pull request merged**
