### PR TITLE
Review SCSS refactoring for to-be-deprecated Bourbon functions

### PR DESCRIPTION
**Pull request by charlesh88**
Details of change and testing notes in #1891. This should be thoroughly Testathoned for regressions before releasing.

### Author Checklist

1. Changes address original issue? Y
1. Unit tests included and/or updated with changes? N/A
1. Command line build passes? Y
1. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by charlesh88** [comment]
@charlesh88 to rebase this over latest master.

**Comment by larkin** [comment]
@charlesh88 I'm considering deferring this until after the current release.  We have a few large refactors going on and rushing to complete this depreciation may make merging other pull requests harder.

**Comment by charlesh88** [comment]
Copy that. I still need to rebase against current master as well.

**Comment by larkin** [comment]
# Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/a style only
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
