### PR TITLE
Enable listening to clearData action for Imagery #3175

### LINKED ISSUE #3175: [Imagery] Should listen to Clear Data like plots and telemetry tables
Plots and Tables clear out data when the global data clear event is emitted. Imagery should do the same

### PR DESCRIPTION
**Pull request by michaelrogers**
Closes #3175 

Rebased upon work @scottbell did in #4304 to improve the clear data component tests. Note: Scott's PR needs to be merged before this PR.

The original PR for this ticket was closed due to merge conflicts from imagery plugin module restructuring. 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? Will users need to change how they are calling the API, or how they've extended core plugins such as Tables or Plots?

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

### CODE REVIEW

**Review by scottbell — APPROVED** [review]

**Comment by akhenry** [comment]
Originally based on 1.7.8 branch. @michaelrogers to clean up and prep for merge into Master

**Comment by michaelrogers** [comment]
Dependent on Scott's testing changes in #4374. Waiting for its merge into master before cherry-picking the commits.

**Comment by akhenry** [comment]
@jvigliotta @scottbell @michaelrogers to review whether this is now ready to merge.

**Comment by scottbell** [comment]
> Dependent on Scott's testing changes in #4374. Waiting for its merge into master before cherry-picking the commits.

@michaelrogers it's been merged, so we should cherry pick this into a new branch/PR

**Comment by michaelrogers** [comment]
Closing with relevant commits cherry-picked into #4733.

**Pull request closed without merging**
