### PR TITLE
remove WorkerService

### LINKED ISSUE #4482: WorkerService is no longer needed
## Overview
Refactor to remove AngularJS. No current benefit in tracking workers in api so removing altogether.

## Expected Behavior
Anything using WorkerService (using Web Workers) should still work.
* Bare Bones Search (fallback search not provided by objectProvider) should still work.

## Steps to Reproduce
1. Do a search for an object that isn't provided by an ObjectProvider and see that it returns a result

### PR DESCRIPTION
**Pull request by davetsay**
closes #4482 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots. (no but this is internal code)

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

**Comment by mariuszr** [comment]
Hi @davetsay, Does the PR address #4482 as there is no `Addresses`/`Closes` link contained?

**Comment by davetsay** [comment]
> Hi @davetsay, Does the PR address #4482 as there is no `Addresses`/`Closes` link contained?

Indeed, @mariuszr . Thanks. I've linked to correct issue.

**Comment by davetsay** [comment]
@akhenry , this is ready for review. removed worker service entirely. also removed generic search as I don't see it being used.

**Comment by davetsay** [comment]
@scottbell , can you also take a look since you're re-implementing search?

**Comment by scottbell** [comment]
@davetsay Yeah, these seems to jive with what I'm doing on:
https://github.com/nasa/openmct/pull/4527
although I've switched to just using a plain jane `SharedWorker`. I've also deleted all of search, though I like in this PR we've also deleted the execution service.
How do you want to resolve the differences? Should I merge your PR into mine? Or should I wait for yours to be merged and I resolve conflicts?

**Review by akhenry — APPROVED** [review]
Looks good to me, thanks!
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

**Comment by davetsay** [comment]
@scottbell , thanks for looking. @akhenry merged this in. I think your PR will deprecate the need for the bare bones search worker. Keep me posted. If your changes do deprecate bare bones search I'll want to test your changes in VISTA.

**Pull request merged**
