### PR TITLE
fix: typo spelling grammar

### LINKED ISSUE #4130: [Typo Fixes] Various typo fixes
There are various typos throughout the code.

## Testing
- nothing to test, this is all comment/documentation related updates

### PR DESCRIPTION
**Pull request by slowy07**
### All Submissions:

closes #4130

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist
deep testing not included because replace the typo with correct words

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

### CODE REVIEW

**Review by jatin837 — DISMISSED** [review]

**Comment by jvigliotta** [comment]
hi @slowy07 thanks for this! Do you have CLA on file with us? If not, can you checkout: https://github.com/nasa/openmct/discussions/3821 and send one in, we can't merge in any changes until we have that.

Thanks again!

**Comment by slowy07** [comment]
thanks sir @jvigliotta, i will send the signed CLA

**Comment by slowy07** [comment]
i was sending the CLA to ``kim.l.chrestenson@nasa.gov`` sir 

thanks !!

**Comment by slowy07** [comment]
okay, thank you sir @jvigliotta !

**Review by jvigliotta — APPROVED** [review]
Thanks @slowy07 ! LGTM

**Review by jvigliotta — CHANGES_REQUESTED** [review]
@slowy07 Looks like the "collapsable" to "collapsible" change is breaking some tests. Since both spellings are accepted, can you remove this change?

**Comment by slowy07** [comment]
okay sir ,change commits [7d350f0](https://github.com/nasa/openmct/pull/4095/commits/7d350f0732cc0f554133b7f9fa6b201b670fc5a0) on #4095

**Review by jvigliotta — APPROVED** [review]
Thanks for the changes, LGTM!

**Pull request merged**
