### PR TITLE
Add right click actions on imagery to allow high resolution download

### LINKED ISSUE #7356: Unable to save high resolution imagery
#### Summary
There are 2 issues:
1. In the imagery view, right-clicking on the main image does not save the image currently being displayed. (It appears to save a blank image, which could be the canvas).
2. Right-clicking an opening a thumbnail in the imagery thumbnail strip in a new tab opens the thumbnail and not the high resolution image.

#### Expected vs Current Behavior
Should be able to view/save high resolution imagery.

#### Steps to Reproduce
1. Right-click on an image in the imagery view
2. Try to Open image in a new Tab
3. Right-click on a thumbnail in the imagery thumbnail strip
4. Try to Open image in a new Tab

Observe that the high resolution image is not opened in the new tab.

#### Environment

* Open MCT Version: 3.2.0
* Deployment Type: dev
* OS: All
* Browser: All

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #7356 

### Describe your changes:

Add some actions ("Open in new tab" & "Save Image As") to the right context menu for the Image Viewer.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Is this a breaking change to be called out in the release notes?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

**Review by shefalijoshi — APPROVED** [review]
Looks good to me. Please merge after tests are written.

**Comment by scottbell** [comment]
Demo:

https://github.com/nasa/openmct/assets/9853862/fde05bf4-c779-49da-a7c8-ae010ee1560c

**Comment by rukmini-bose** [comment]
The icons look good to me. Nice work!

**Comment by charlesh88** [comment]
Looks great, thanks.

**Review by michaelrogers — APPROVED** [review]
These changes look good to me. 💾 🖼️

**Pull request merged**
