### PR TITLE
[Views] Repair view registry for mainViews

### PR DESCRIPTION
**Pull request by VWoeltjen**
Repairs incompletely-implemented view registries, #1307

### CODE REVIEW

**Comment by larkin** [comment]
@VWoeltjen can we segment this off as one fix (for main views) and do the other registries separately?  One reason being other regions have slightly different interfaces (e.g. inspectors and toolbars with selection/multiselection) and could drag this out, another reason being I need to start demoing main view functionality next week.

**Comment by VWoeltjen** [comment]
That works for me. Do you need the issue with view metadata fixed for next week or should I separate that out as well?

**Comment by larkin** [comment]
no need for metadata.

**Comment by VWoeltjen** [comment]
This should be ready to merge then; I'll go through checklist and reassign shortly, assuming everything looks good.

**Comment by VWoeltjen** [comment]
### Author Checklist

1. Changes address original issue? Y (partial)
2. Unit tests included and/or updated with changes? No (accounted for by #1218)
3. Command line build passes? Y
4. Changes have been smoke-tested?  Y

**Comment by larkin** [comment]
# Reviewer Checklist

1. Changes appear to address issue? Y, partial, issue will remain open for other parts.
2. Appropriate unit tests included? N/A (properly deferred)
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
