### PR TITLE
Eagerly lose WebGL context on `DrawWebGL.destroy()`

### LINKED ISSUE #7074: memory leaks in data visualization
#### Summary
memory leaks need to be addressed
* openmct.components creates a memory leak, is no longer used, and can be removed completely (it was a means to get openmct vue components into plugins developed outside of core openmct)
* plots are not being cleaned up properly (WARNING: Too many active WebGL contexts. Oldest context will be lost.)

#### Steps to Reproduce

1.
2.
3.
4.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### LINKED ISSUE #7081: "WebGL context lost" when loading plots
#### Summary

When re-rendering multiple plots (but fewer than 16), the warning can be seen in the console:
`WARNING: Too many active WebGL contexts. Oldest context will be lost.` 

Plots fall back to canvas2D and WebGL contexts don't seem to become immediately available, so this warning is seen multiple times.

#### Expected vs Current Behavior

If there are < 16 known active WebGL contexts on the page, we should not see this warning. Plots should not fall back to 2D.

#### Steps to Reproduce

1. Create a Flexible Layout with 4 SWGs
2. Clone it
3. Flip back and forth between the two flexible layouts with your console open
4. Navigate to some SWGs directly 
5. Notice the warning in the console and plots fall back to 2D

#### Environment

* Open MCT Version:  3.1.0-next
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

#### Additional Information

https://github.com/nasa/openmct/assets/9259993/a723a63f-5356-4d79-b6b2-69f18e3a49d6

### PR DESCRIPTION
**Pull request by davetsay**
Closes #7081

### Describe your changes:

Eagerly lose WebGL contexts on destroy by using the `WEBGL_lose_context` extension, [recommended as a WebGL best practice](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#lose_contexts_eagerly), in an attempt to free up WebGL contexts sooner after Plots are unmounted.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by unlikelyzero** [comment]
With this implementation, are you making the trade off that we will pay the penalty for creating the context on navigation to a complex display or map tool inspector?

If there are two complex plot displays with 16 plots each, in two separate chrome tabs, are we creating and destroying the WebGL contexts Every time a user uses a different tab?

**Comment by akhenry** [comment]
According to the documentation this Web GL extension will _simulate_ a loss of context. Are we sure it's actually losing the context? Does it fix the issues we were seeing? - https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_lose_context

**Comment by ozyx** [comment]
> According to the documentation this Web GL extension will _simulate_ a loss of context. Are we sure it's actually losing the context? Does it fix the issues we were seeing? - https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_lose_context

Yes, this does fix the issue with losing WebGL context. It looks like it's marking the context for deletion and being picked up by GC much quicker. Although it "simulates" losing context (confusing wording?), it is [recommended as a best practice](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#lose_contexts_eagerly).

**Review by jvigliotta — APPROVED** [review]
Looks good! Nice work!

**Review by scottbell — APPROVED** [review]
Had some difficulty checking out the branch due to numbers appearing as a commit hash to git, but was able to solve that using `git checkout --track origin/7074`.

Here's the behavior before, with the nasty warnings stating `Too many active WebGL contexts.`:
https://github.com/nasa/openmct/assets/9853862/a1cf5c95-699f-46bf-a95c-88c57608e7e6

Here's the behavior after, with WebGL contexts properly being trashed 🚮:

https://github.com/nasa/openmct/assets/9853862/8f1cd580-efd4-46ed-adfc-df029055f9ea

**Pull request merged**
