### PR TITLE
Review and integrate branch 700

### PR DESCRIPTION
**Pull request by charlesh88**
#700
Removed normalize.min.css; updated Licenses page
Removed CSS file as indicated; removed normalize
and modernizr from Licenses info;

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? N, N/A
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Changes look good, except I think we should add licensing info for reset.css. Also, LICENSES.md at the top-level needs to be updated to reflect this as well (both the addition and the removals)

**Comment by charlesh88** [comment]
Cool, I will make it happen.

**Comment by charlesh88** [comment]
Touching base with Pete about continuing to use normalize instead of replacing with reset, thread in #700.

**Comment by charlesh88** [comment]
Closing this PR and have filed new PR with #759.

**Pull request closed without merging**
