### PR TITLE
[Tree] [WIP] Auto-scroll to selected item in trees

### PR DESCRIPTION
**Pull request by BogdanAlexandru**
This is a WIP fix for #214 which blocks another PR of mine.

The code as-is won't do much, but I wanted to ask a question before proceeding. It's more or less about figuring out a way to fill in:

```js 
function findSelectedNodeView(rootView)
```

Based on the understanding I've got so far:

* MCTTree is the topmost Tree class (directive) in the hierarchy.
* Below MCTTree there's a recursive hierarchy of TreeViews and TreeNodeViews.
* MCTTree is the best spot to actually trigger the scrolling behavior, because it's at the top of the hierarchy, so the element that has the scrollbar is there.

`MCTTree` doesn't seem to have any knowledge of the currently selected `TreeNodeView`. 

Can we make `TreeNodeView.value()` return a value that indicates which `TreeNodeView` was selected in the hierarchy (so in the `TreeNodeView`'s `value()` there would be something like `if isSelected return self otherwise return children.value()`? Would this go against the currently chosen design (most likely missed many details)?

Or is there a simpler way to get from the currently `selectedObject` to its `TreeNodeView`, other than traveling through the hierarchy of views (i.e. a recursive function) inside `MCTTree`?

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Digging through the hierarchy seems like overkill, agreed.

Have you tried something like `this.li[0].scrollIntoView()` from TreeNodeView itself? I'm thinking it could be done [right where it sets the `selected` class](https://github.com/nasa/openmct/blob/185567cf2947baa9e7e1153771c7b20fc3510e0d/platform/commonUI/general/src/ui/TreeNodeView.js#L136)

**Comment by BogdanAlexandru** [comment]
@VWoeltjen That was my first attempt, a while ago. Well, not `scrollIntoView` itself, because the MDN says this:

> This is an experimental technology
Check the Browser compatibility table carefully before using this in production.

If the compatibility table looks good to you, I can give `scrollIntoView`  a shot.

Instead I compiled (read: googled) a function that traversed the DOM hierarchy up until it found the scrollable element, and scrolled that.

This was it:

```
        function getFirstScrollableParent(element) {
            var style = getComputedStyle(element);
            var excludeStaticParent = style.position === "absolute";
            var overflowRegex = /(auto|scroll)/;

            if (style.position === "fixed") return document.body;
            for (var parent = element; (parent = parent.parentElement);) {
                style = getComputedStyle(parent);
                if (excludeStaticParent && style.position === "static") {
                    continue;
                }
                if (overflowRegex.test(style.overflow + style.overflowY + style.overflowX)) return parent;
            }

            return document.body;
        }
```

The ugliness of which made me try to take the whole scrolling logic as high up in the hierarchy as possible.

Another thing that I think we'll encounter if we scroll in the TreeNodeView: the tree seems to do a select-then-immediately-unselect inside the selector in, for example, the Create dialog. So I'm trying to create a new folder, and I need to pick a parent. I have a folder already selected, but then try to select a display layout. This is normally an invalid choice, since a layout cannot have a folder child. The tree still considers it a selection, but then the old folder gets auto-selected and I get scrolled back to the old folder, instead of just cancelling the selection of the layout (or better: making the click on the layout a noop) and staying there.

But I'll try `scrollIntoView` first and see if the bug shows its face.

**Comment by BogdanAlexandru** [comment]
To make it clearer, this is the buggy behavior that I'm talking about (using `scrollIntoView` here):
Imgur

**Comment by VWoeltjen** [comment]
Thanks for the screenshots, that's helpful.

`scrollIntoView` still seems like it makes sense; I think the issue here is that the TreeView's validation is implemented in a way that does not make sense. Seems like it would be more appropriate to pass a validation function into MCTTreeView, and check that before ever making the selection change.

**Comment by BogdanAlexandru** [comment]
Indeed, the bug has its roots in `LocatorController` which does

```
if (!$scope.structure.validate(domainObject)) {
   setLocatingObject(priorObject, undefined);
   return;
}
```

There's still some issues with just adding `scrollIntoView`, in particular this thing happening when you start the app:

Imgur

It goes away when you click on anything in the tree.

And then there's the fact that it seems to trigger scrolling even if the element is in the view already.

I'll look into these issues and see what I can find.

**Comment by BogdanAlexandru** [comment]
So one thing where I think we can start is clean up the validation logic. So right now an invalid object looks like this:

Imgur

In the screenshot the cursor cannot be seen but it's hovering on the layout. Basically, it looks like something you can click and select, even though if you do it nothing happens.

I think a more user-friendly approach would be to simply grey-out the invalid items, and remove the hand cursor that indicates that they can be clicked. That way it's clear at a glance what is a valid choice and what isn't. Like this:

Imgur

Aside from user friendliness, this also clears our bug. 

I think this can be achieved by giving the `MCTTree` directive a `selectionValidator` attribute. When it's absent, it defaults to `fn (obj) { return true; }`. The Locator would pass its specified validator to the tree it uses to locate things.

The `selectionValidator` would be used in deciding when something gets selected and the style of the node views.

Thoughts on this approach?

**Pull request closed without merging**
