### PR TITLE
[Display Layout] Bug fix for object removal (#3117)

### PR DESCRIPTION
**Pull request by johnriedel**
* remove display layout objects that weren't being removed

To test:
    1. Add a display layout to "My Items" folder
    2. In Display Layout main window, click "Save and Finish Editing"
    3. Add a "State Generator" object to the Display Layout in the object tree
    4. Select the Dispay Layout in the object tree so it's active in the main window
    5. Note that you can see the State Generator in the display layout in the upper left corner of the main window
    6. Select the State Generator in the object tree so it's active in the main window
    7. Right-click the State Generator and select Remove from the drop-down menu
    8. Ensure that the State Generator is removed from the object tree
    9. Select the Display Layout in the object tree so it's active in the main window
    10. Ensure that the State Generator is removed from the display layout in the main window

Author Checklist:
    1. Changes address original issue? Yes
    2. Unit tests included and/or updated with changes? No
    3. Command line build passes? Yes
    4. Changes have been smoke-tested? Yes

### CODE REVIEW

**Comment by johnriedel** [comment]
Hi Deep. Many thanks for the review and for pointing me in the right direction. I'll revisit and investigate the display layout.

**Comment by deeptailor** [comment]
Hi @johnriedel - Take a look at PR #3130 - This fixes the issue in Display Layout, you could use this as a guide to fix it in Flexible Layout

**Comment by johnriedel** [comment]
Perfect! Thanks @deeptailor. Will do.

**Comment by johnriedel** [comment]
Hi @deeptailor ,
    Heads-up.....PR #3130  addresses issue #3118 , an issue that I already closed a few days back. This particular PR, however, addresses an issue that hasn't yet been resolved by any other PR.

**Pull request closed without merging**
