### PR TITLE
[Edit] Clear transactions on Save As

### LINKED ISSUE #1046: excessive persistence errors and failure to exit edit mode
This has been reported in VISTA and can be reproduced there; I do not yet have a openmct reproduction for this but I think it may be a conflict between multi-space persistence and VISTA.  It was first detected with a build of openmct 5 days ago, and is still present.

The basic reproduction steps in vista:

1. search for something basic (that gives you objects)
2. create new display layout
3. add some of your search results to the display layout
4. save the display layout to your user folder.

expected result: the layout should save successfully.
actual result: VISTA displays multiple persistence errors and the application does not leave edit mode.

This appears to be caused by an issue in the bleeding edge of OpenMCT, as targeting older versions of OpenMCT does not cause this to occur.

@akhenry @VWoeltjen can you try and reproduce this in the WARP CI environment?  I can't reproduce with scratchpad or localstorage and think it might require a certain amount of latency for it to occur.

I'll spend more time tomorrow trying to isolate the cause in the VISTA environment.

### PR DESCRIPTION
**Pull request by VWoeltjen**
...such that only persistence calls associated with the
saved clones are actually issued. Fixes #1046.

Still to-do:

- [x] Update tests
- [x] ~~Clean up (or file follow up)~~ #1059
- [x] Clarify JSDoc
- [x] Verify that build completes (code style etc)

### CODE REVIEW

**Comment by akhenry** [comment]
Concerns:
1. We're adding a function to `TransactionService` that has no utility outside this special case.
2. Clearing the transaction risks clearing other stuff that we don't want to (thinking in particular of deep nesting cases like Timelines). I'm not sure if this is a problem or not, but might be worth testing.

**Comment by akhenry** [comment]
What about if we could clear persists for a particular object. The `TransactionalPersistenceCapability` has references to onCommit and onCancel (currently scoped to the `persist` function, but could be moved to `this`).

We could then add two functions to TransactionService `clearOnCommit` and `clearOnCancel` (or even just combine them into one function) that accept function references and removes them from the persist/cancel queue.

Then we call `clear*`from `TransactionalPersistenceCapability.refresh()`. Then we simply call `refresh()` on the original object from `SaveAsAction`.

It probably sounds more complicated than it actually is :)

**Comment by VWoeltjen** [comment]
> 1. We're adding a function to `TransactionService` that has no utility outside this special case.

Yep, I think that should get cleaned up in a follow-up (looking at this more as a quick fix.) 

I do think we will need to add something broadly similar to TransactionService to resolve this; the root cause is that we're committing changes that really just aren't meant to be committed. We do need to be able to say "wait, no, never mind." Since we're just pushing functions into the TransactionService, we could put some smarts in there.

> 2. Clearing the transaction risks clearing other stuff that we don't want to (thinking in particular of deep nesting cases like Timelines). I'm not sure if this is a problem or not, but might be worth testing.

That's a good point. Clearing the whole transaction discards changes to things that _weren't_ cloned, too. I believe the only practical case we have of this currently is in Timelines (Create Timeline, drag in an existing activity from the tree to add a link, change the Activity's name, save... the change to the Activity's name gets lost.)

**Comment by akhenry** [comment]
Semantically, it makes sense to 'undirty' an object when you refresh it, so there's no weird repurposing there.

**Comment by akhenry** [comment]
Actually, now that I think about it, refresh() *should* be undirtying anyway...

**Comment by larkin** [comment]
This fixes #1046 in the VISTA environment.  Will investigate further.

**Comment by akhenry** [comment]
@larkin @VWoeltjen I'd like to pursue 1051 if we can, I prefer that approach. Because #1050 is working and #1051 is not, it suggests to me that something is not being undirtied that should be. They both work on the same principle of clearing the transaction, #1051 is just more selective.

**Comment by VWoeltjen** [comment]
Also still able to reproduce #1046 in VISTA with #1051 (albeit after five consecutive successes.) Ran through reproduction steps 10 times on this branch without reproducing.

Agree that #1051 is more like the solution we want, but think there is still some subtle timing issue in that solution which is not present. Think the sensible course of action would be to merge this for today's testathon, and work on getting the approach from #1051 nailed down next sprint.

The [issue with timelines](https://github.com/nasa/openmct/pull/1050#issuecomment-227893782) that this fix introduces is fairly obscure (adding linked activities to timelines is not normal use) and has a workaround (redo any changes that were lost)

**Comment by VWoeltjen** [comment]
Closing in favor of the squashed edition, #1060

**Pull request closed without merging**
