### PR TITLE
Fix code scanning alert - Client-side URL redirect #4757

### LINKED ISSUE #4757: Fix code scanning alert - Client-side URL redirect
Tracking issue for:
- [ ] https://github.com/nasa/openmct/security/code-scanning/5

### PR DESCRIPTION
**Pull request by nikhilmandlik**
Closes #4757

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by nikhilmandlik** [comment]
here we go again

**Comment by unlikelyzero** [comment]
@nikhilmandlik i'm going to update the original issue to target 1.8.5

**Review by unlikelyzero — APPROVED** [review]
This passes the security check. Will defer to @shefalijoshi for implications

**Comment by unlikelyzero** [comment]
@nikhilmandlik needs testing notes

**Comment by unlikelyzero** [comment]
@nikhilmandlik note: this is where this regression was introduced https://github.com/nasa/openmct/commit/d0c5731287aa3470399fdede57f0a2570b32f3f3

**Comment by akhenry** [comment]
@shefalijoshi This just needs a quick review and merge, thanks!

**Review by shefalijoshi — APPROVED** [review]

**Pull request merged**
