### PR TITLE
actionCollection update event looping when open View Large in Display layout

### PR DESCRIPTION
**Pull request by nikhilmandlik**
### Resolves: 
resolves: #3959

### Notes: 
NA

### All Submissions:
* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A - small contained change
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

**Review by akhenry — APPROVED** [review]

**Review by akhenry — CHANGES_REQUESTED** [review]
Blocked pending confirmation of the correct branch for CDA

**Comment by akhenry** [comment]
@nikhilmandlik  Can you please base this on the 1.7.4 branch?

**Comment by nikhilmandlik** [comment]
> @nikhilmandlik Can you please base this on the 1.7.4 branch?

1.7.4 vs 1.7.4.-stable?

**Comment by akhenry** [comment]
@nikhilmandlik unconfirmed. Am waiting to hear from @shefalijoshi

**Review by akhenry — APPROVED** [review]

**Pull request merged**
