### PR TITLE
3788 - Re-implement DeviceClassifier in vanilla JS

### PR DESCRIPTION
**Pull request by mariuszr**
## Overview
Addresses #3788 

## Changes
- Created and installed a new `DeviceClassifier` plugin
- Removed the `DeviceClassifier`, `AgentService` and `DeviceMatchers` from Angular in itself
- Moved and reimplemented the `AgentService` and `DeviceMatchers` to the plugin level
- Linked to the moved [`AgentService`](https://github.com/mariuszr/openmct/blob/openmct-3788/platform/commonUI/mobile/src/AgentService.js#L23) and [`DeviceMatchers`](https://github.com/mariuszr/openmct/blob/openmct-3788/platform/commonUI/mobile/src/MCTDevice.js#L24) as they still in use by Angular

## Author Checklist
- Changes address the original issue? Y
- Unit tests included and/or updated with changes? N/A
- Command line build passes? Y
- Changes have been smoke-tested? Y
- Testing instructions included? N

### CODE REVIEW

**Comment by mariuszr** [comment]
Hi @davetsay. Please review.

**Comment by davetsay** [comment]
Hi @mariuszr on first glance this is looking really good. I'll need some time to review. Thanks again for contributing.

**Comment by mariuszr** [comment]
Hi @davetsay, FYI I was signed the CLA on April 21, 2021, so you can feel free to use the contributing when it is correct :)

**Review by davetsay — CHANGES_REQUESTED** [review]
@mariuszr looking good. A couple things.

It looks like AgentService and MCTDevice might still be used by our angular services? This might be out of scope for this issue. If AgentService is being used outside of DeviceClassifier I wouldn't put it in the DeviceClassifier plugin folder.

The src/test folder structure is not used in this project. See 17 in https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md#code-guidelines

I'm seeing linting issues when I run `npm run lint`. Likewise I'm seeing errors when I run `npm run test`.

**Comment by mariuszr** [comment]
@davetsay, For this issue, the additional objects ([AgentService.js](https://github.com/nasa/openmct/blob/master/indexTest.js#L1) and [DeviceMatchers.js](https://github.com/mariuszr/openmct/blob/openmct-3788/src/plugins/DeviceClassifier/src/DeviceMatchers.js#L35)) have been also reimplemented as they were a part of the [DeviceClassifier.js](https://github.com/mariuszr/openmct/blob/openmct-3788/src/plugins/DeviceClassifier/src/DeviceClassifier.js#L43). As you also noticed, the [AgentService.js](https://github.com/mariuszr/openmct/blob/openmct-3788/platform/commonUI/mobile/bundle.js#L46) is still in used by Angular and for this reason it has been created a [Agent Service Wrapper](https://github.com/mariuszr/openmct/blob/openmct-3788/platform/commonUI/mobile/src/AgentService.js#L24)  that uses the newly implemented [Agent Service](https://github.com/mariuszr/openmct/blob/openmct-3788/platform/commonUI/mobile/src/AgentService.js#L27)

As to the location of the test files, it is my bad as I thought that the practices which we can see in the current code have precedence over the documentation :)

Please let me know whether I have to put the Agent Service (as a new Device Agent plugin?) out of the Device Classifier as a part of the issue. 

### Changes
* [lint error] removed a space in [/platform/commonUI/mobile/src/AgnetService.js](https://github.com/nasa/openmct/pull/3837/commits/755ccf0c9c517c4391761f5bb18e6130d702c787#diff-7f55a29af1ecd19b087187c287e11b84fe1e5607e3a2e4d11b5f26c25ad71c2bR23) (0 space)
* [test error] removed a `new` statement in [/src/plugins/DeviceClassifier/src/DeviceClassifierSpec.js](https://github.com/nasa/openmct/pull/3837/commits/755ccf0c9c517c4391761f5bb18e6130d702c787#diff-6e5e8ccb728f0c54fc99645f93020fb12d31991a1f854310d52137846787297dL79) (no constructor)
* [test location] moved test files from the `test` directory to the source code location that they test
* [supplement to the test] used the same test `AgentServiceSpec.js` for testing the wrapper of [AgentService.js](https://github.com/mariuszr/openmct/blob/openmct-3788/platform/commonUI/mobile/src/AgentService.js#L23) for Angular

### Lint
* use `eslint src/plugins/DeviceClassifier platform/commonUI/mobile --ext .js` to check correctness of the changed files

### Test
* use `const testsContext = require.context('.', true, /\/(src|platform)\/(AgentService|DeviceClassifier|DeviceMatch).*Spec.js$/);` in [indexTest.js](https://github.com/nasa/openmct/blob/master/indexTest.js#L1) to test added unit tests

**Comment by davetsay** [comment]
@mariuszr , sorry for the delay in response. I went back and looked at this some more. I can see how AgentService is in being included by use for several angular services. In reality, I think only the DeviceClassifier is still in use. I think the correct path forward would be to replicate the functionality of the AgentService and expose it as utils. We can then create another issue to remove these deprecated UI tools, and if other services do indeed depend on AgentService then they can be changed to use the non-angular dependent user agent utils.

**Comment by davetsay** [comment]
@mariuszr , just checking in. Hopefully we can get your contribution merged soon. I think we can either rewrite and expose `AgentService` as utils. Or, you can just inject (using `openmct.$injector`) the angular service where needed for now. We can convert `AgentService` in another PR.

**Comment by mariuszr** [comment]
Hi @davetsay, I will rewrite and expose `AgentService` as utils.

**Comment by mariuszr** [comment]
@davetsay, Please check it. Please also see the [Agent Service Wrapper](https://github.com/mariuszr/openmct/blob/openmct-3788/platform/commonUI/mobile/src/AgentService.js#L24) has been implemented to do not spend time on unnecessary changes in angular.

**Review by davetsay — CHANGES_REQUESTED** [review]
@mariuszr , thanks so much this is great. Now we only have to fix some broken tests and were good to go. I didn't see what exactly they were but it was in `MCTDeviceSpec.sj`.

**Comment by davetsay** [comment]
@mariuszr , I think actually `MCTDevice` can be removed completely as its not in use. I think we had discussed removing it in a separate PR but its fine if you remove it here as well. Up to you how you want to address these failing tests.

**Comment by mariuszr** [comment]
@davetsay, Yes, you're right, seems like the MCTDevice is not used anymore. I have removed it, however, I cannot find the issue that says that the MCTDevice should be refactored/removed.

**Review by davetsay — APPROVED** [review]
LGTM. Thanks so much for your contribution @mariuszr ! Great work!

## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | Y |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |
| Has associated issue been labelled `unverified`? | Y |

**Pull request merged**
