### PR TITLE
[Display Layout] User should be able to toggle grid lines

### PR DESCRIPTION
**Pull request by davetsay**
## Overview
Addresses #3315 

## Testing Instructions 
see #3315

## Author Checklist
| | |
| --- | :---: |
| Changes address original issue? | Y |
| Unit tests included and/or updated with changes? | N/A |
| Command line build passes? | Y |
| Changes have been smoke-tested? | Y |
| Testing instructions included? | Y |

* Requires glyphs `icon-grid-on` and `icon-grid-off` from branch `add-glyphs-082020`

### CODE REVIEW

**Comment by davetsay** [comment]
@deeptailor , trashed the other PR and created a new one. I'm merging into master directly instead of the topic branch. I addressed your comment about reordering the toggle method and the toggle icon.

**Comment by davetsay** [comment]
@charlesh88 , this requires the glyphs. Not sure if you want to add them to this branch or just get them all into master at the same time separate from this.

**Comment by davetsay** [comment]
@charlesh88 , gotta call you in on this one. I'm not sure how you want the outer dimensions displayed, but right now its an ugly red right and bottom border...
image

**Comment by davetsay** [comment]
Glyphs merged in #3365. Ready to go.

**Review by charlesh88 — APPROVED** [review]
Awesome, LGTM.

**Review by deeptailor — APPROVED** [review]

**Comment by deeptailor** [comment]
## Reviewer Checklist
Changes appear to address issue? Yes
Appropriate unit tests included? N/A - needs backfill
Code style and in-line documentation are appropriate? Yes
Commit messages meet standards? Yes
Has associated issue been labelled unverified? (only applicable if this PR closes the issue) Yes

**Review by deeptailor — APPROVED** [review]

**Pull request merged**
