### PR TITLE
[conductor] Prevent zoom cancel on time input click

### LINKED ISSUE #4017: [Time Conductor] zoom/pan in realtime plot removed on time conductor input click
## Overview
Zoom/Pan state is lost when clicking on time conductor inputs in realtime mode.

## Expected Behavior
Zoom/Pan state should only be reset if start end values are saved

## Steps to Reproduce
1. Navigate to a plot
2. Go to realtime mode if not already
3. Zoom or pan plot
4. Click on start or end input and see that zoom/pan state is lost
5. For comparison go to fixed time mode and repeat steps 3-4. zoom/pan state is not lost.

### PR DESCRIPTION
**Pull request by jvigliotta**
closes #4017

This is a pull from @khalidadil 's work.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

**Review by shefalijoshi — APPROVED** [review]
OK! Nice!

**Comment by shefalijoshi** [comment]
Closing this as it is covered by https://github.com/nasa/openmct/pull/4033

**Comment by khalidadil** [comment]
thanks @jvigliotta! I figured out how to get it into 1.7.5 a minute before you put this in! The help is super appreciated! 🙌🏽

**Comment by jvigliotta** [comment]
No worries @khalidadil, we got yours in, in time! Nice work!

**Pull request closed without merging**
