### PR TITLE
Styles for telemetry are stored on their container domain objects

### LINKED ISSUE #2779: Styling applied to non-composable domain objects should be saved as properties of the layout.
Styles on non-composable domain objects (like telemetry) should be saved in the current layout only, and not to the domain objects themselves. Currently, styling on a non-composable domain object in a layout styles the domain object, and all aliases of that domain object.

Editing styles on a composable domain object will apply and persist those styles as part of the domain object - consistent with our approach to sub-object editing.

So in short: non-composable domain object styles are treated like Layout drawing objects, and composable domain object styles are treated as sub-object editing.

### PR DESCRIPTION
**Pull request by shefalijoshi**
Resolves #2779 

Also addresses: Resizing and/or repositioning drawing objects and them immediately changing a style attribute in the Inspector causes the drawing object to reset to its previous pose. Main toolbar interactions for same don't exhibit this behavior. in #2796

### CODE REVIEW

**Comment by charlesh88** [comment]
One more thing: technically, non-creatable/non-composable domain objects shouldn't display the styles tab in the Inspector in their main view. Not a priority for v1, but if it's as not-difficult change we should make it.
Screen Shot 2020-04-06 at 3 05 30 PM

**Comment by shefalijoshi** [comment]
> Not high priority, but setting a drawing object like a Box to have a transparent background should set it to transparent, not the default gray. Same comment for the line object's border color. In the past, this was handled by disallowing a "None" selection from the background color palette for Boxes and border-color palette for Lines.
> 
> Text color gets a pass because that inherits the default text color from the app's theme.

Do you want to disallow none for the style inspector as well?

**Comment by charlesh88** [comment]
Seeing some issues with Conditional styling:
- Visibility disabled on a telem object isn't being applied:
Screen Shot 2020-04-06 at 3 30 03 PM
- Condition sets stop evaluating in a Layout at some point. In this example, note the current value of the SWG (-0.35) and what the output from the Condition set is: "Up" is shown, but it should be "Mid". Previewing the Condition set in the overlay causes it to display as expected.
Screen Shot 2020-04-06 at 3 41 57 PM

**Comment by shefalijoshi** [comment]
> Styles for an SWG aren't being applied on the right DOM element: they are begin applied to the `.c-telemetry-view__label` and the `.c-telemetry-view__value` elements, but instead should be just applied to `c-telemetry-view`.

Applying styles to c-telemetry-view will result in very odd behavior when alarmCss is active.

**Comment by charlesh88** [comment]
telemetry provider stops listening for events from the condition manager

> Applying styles to c-telemetry-view will result in very odd behavior when alarmCss is active.

Per our recent Hangout, your mod to the code for this is perfect, so we're good to go.

**Comment by shefalijoshi** [comment]
> One more thing: technically, non-creatable/non-composable domain objects shouldn't display the styles tab in the Inspector in their main view. Not a priority for v1, but if it's a not-difficult change we should make it.
> Screen Shot 2020-04-06 at 3 05 30 PM

I'll file an issue for this.

**Comment by charlesh88** [comment]
> Styles for an SWG aren't being applied on the right DOM element: they are begin applied to the `.c-telemetry-view__label` and the `.c-telemetry-view__value` elements, but instead should be just applied to `c-telemetry-view`.

This is fixed in `multiple-item-styles` so good to go here.

**Comment by charlesh88** [comment]
> > Not high priority, but setting a drawing object like a Box to have a transparent background should set it to transparent, not the default gray. Same comment for the line object's border color. In the past, this was handled by disallowing a "None" selection from the background color palette for Boxes and border-color palette for Lines.
> > Text color gets a pass because that inherits the default text color from the app's theme.
> 
> Do you want to disallow none for the style inspector as well?

This is fixed in `multiple-item-styles` so good to go here.

**Comment by shefalijoshi** [comment]
Merging as this is approved.

**Pull request merged**
