### PR TITLE
Conductor performance improvements

### PR DESCRIPTION
**Pull request by akhenry**
Some modest performance improvements to the time conductor. Throttles updates to both the clock animation, and the current time display. This results in a slightly less smooth experience for users.

### Author Checklist
1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? N/A
3. Command line build passes? Y
4. Changes have been smoke-tested? Y
5. Testing instructions included? Y

### CODE REVIEW

**Comment by akhenry** [comment]
@charlesh88 Would love for you to pull this down and take a look at it when you get a moment.

**Review by charlesh88 — APPROVED** [review]
I just pushed a tweak that changes the steps from 15 to 12. With that, LGTM.

**Comment by akhenry** [comment]
@charlesh88 Great! Thanks! Even more CPU cycles to play with.

**Comment by akhenry** [comment]
@davetsay  Can you give this the once over and merge if you're happy with it? Thanks!

**Review by deeptailor — APPROVED** [review]
LGTM

**Pull request merged**
