### PR TITLE
[Examples] Add Kerbal Space Program as telemetry source

### PR DESCRIPTION
**Pull request by hudsonfoo**
- [X] Changes address original issue?
- [X] Unit tests included and/or updated with changes?
- [X] Command line build passes?
- [X] Changes have been smoke-tested?

**Additional notes:**
Tested with Mac OS X 10.11.6, KSP v1.1.3.1289, Telemachus v1.5.
It's glorious.

### CODE REVIEW

**Comment by hudsonfoo** [comment]
Video of it in action: http://quick.as/9wZiOe5d

**Comment by hudsonfoo** [comment]
Almost forgot: Because I was forced to use the HTTP API, Cross-domain AJAX is an issue with this implementation. To use, you will need to either A) Disable web security (Chrome) or B) Proxy local URLs to the Kerbal API endpoint. On my local, I just disabled Chrome web security and was good to go. Obviously, getting the Telemachus websocket API functional is preferable to this solution as cross-domain issues are not a factor for websockets.

I should also note that history is not provided by the Kerbal API and that all "history" is kept in memory from the moment the page loads. Opening a new instance of Open MCT starts the history at zero. Further, Kerbal uses its own "time" which is called Universal Time. Universal Time is the number of seconds since the game was started. This time can be "warped" which means one second of Earth time != one second of Kerbal Universal Time. I didn't see a way to make the x axis of the plots work off of anything other than an Earth timestamp, so all data points from Kerbal are based on the Earth timestamp of when the data was received. Any suggestions on converting a plot to use a float for the x axis rather than a timestamp would be appreciated.

**Comment by BogdanAlexandru** [comment]
I think that's definitely something worth adding to a README next to the example so that the interested user is aware of the technical particularities and gotchas. Relevant: https://github.com/nasa/openmct/issues/846

So the README would essentially be the primer.

**Comment by hudsonfoo** [comment]
Kerbal time is now used instead of Earth time on the historical and real-time tables. I'm still working out how to apply Kerbal time formatting to plots.

**Comment by hudsonfoo** [comment]
Thanks to @raoulsullivan the proxy is working so disabling Chrome security is no longer necessary <3 <3 <3

**Comment by VWoeltjen** [comment]
This is great, I was very excited to see this PR! At around 1:00 into that video, Jebediah Kerman and I shared the same facial expression.

Eventually, I think this will make more sense as a plugin hosted in a separate repository; maintaining it alongside Open MCT itself could be a bit problematic. Would you be interested in acting as maintainer for this plugin? If not, I certainly think there is enough value here to keep this in among our examples until we find a more permanent home.

One thing I think this does need is at least a short description (e.g. `examples/kerbal/README.md`) of how to use it - what the dependencies are, how they need to be configured, etc.

Also, are the changes in RangeColumn necessary? Could boolean values be converted to strings in the plugin instead? It would be preferable to keep changes in the scope of the examples.

Thanks!

**Comment by hudsonfoo** [comment]
Moved into its own separate repository and added documentation: https://github.com/hudsonfoo/kerbal-openmct

The changes in RangeColumn may be due to my not understanding requirements for ranges, and on reflection, should have been put into a separate pull request. Telemachus passes boolean values for certain telemetry (SAS, RCS, etc) so I anticipated that ranges may need to support that. Without the update to RangeColumn, the display shows "NaN" instead of true or false. This update can certainly be made within the Kerbal plugin itself if, especially if boolean values are not a typical telemetry data type. I'll update the repo to detect and convert booleans to strings so the plugin will work regardless of a RangeColumn update.

Thanks for reviewing. This was a lot of fun.

**Comment by hudsonfoo** [comment]
Oh! I should add that this commit: https://github.com/nasa/openmct/pull/1146/commits/2e1b2a1f7241fc074c9d2e0edbeb3f03125567fc should probably be added to Open MCT regardless of Kerbal, as it resolves the issue of proxy URLs including query params.

**Comment by raoulsullivan** [comment]
I'll do a PR to OpenMCT for https://github.com/nasa/openmct/pull/1146/commits/2e1b2a1f7241fc074c9d2e0edbeb3f03125567fc shortly

**Comment by VWoeltjen** [comment]
> Moved into its own separate repository and added documentation: https://github.com/hudsonfoo/kerbal-openmct

Excellent, thanks for doing that!

> The changes in RangeColumn may be due to my not understanding requirements for ranges, and on reflection, should have been put into a separate pull request. Telemachus passes boolean values for certain telemetry (SAS, RCS, etc) so I anticipated that ranges may need to support that. Without the update to RangeColumn, the display shows "NaN" instead of true or false.

Ah, got it. We do see boolean values reasonably often in telemetry, but the display requirements we've had for these haven't been any different than strings/enumerations.

I'll got ahead and close this PR since it's superseded now by #1159 and #1160. Thanks again for putting this together!

**Pull request closed without merging**
