### PR TITLE
fix flaky test in dirty way

### PR DESCRIPTION
**Pull request by scottbell**
### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

### CODE REVIEW

**Comment by scottbell** [comment]
This is a dirty fix for the nondeterministic failure of a test. I have some concerns after looking at the issue:
https://github.com/nasa/openmct/issues/4462#issuecomment-971402596

**Comment by scottbell** [comment]
Though looks like a recent PR itself is having some issues:
```
adds an interceptor that returns a "My Items" model for
      ✓ missing objects (73ms)
Chrome Headless 96.0.4664.45 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Unhandled promise rejection: Object provider does not support saving thrown
```
https://github.com/nasa/openmct/pull/4471/files

**Comment by scottbell** [comment]
Blocked until https://github.com/nasa/openmct/issues/4476 is resolved

**Comment by scottbell** [comment]
It looks like @shefalijoshi basically did the same thing and bumped the mockDomainObject.modified so the mutation appears to the test like it's in the future. I still think we may have a race condition though per:
https://github.com/nasa/openmct/issues/4462#issuecomment-971402596

**Comment by shefalijoshi** [comment]
This fix looks good, however it has been already fixed in master. Closing.

**Pull request closed without merging**
