### PR TITLE
d3 selection filepath changed

### PR DESCRIPTION
**Pull request by thesamprice**
d3 changed the location of this file, npm install fails when trying new builds.

### CODE REVIEW

**Comment by thesamprice** [comment]
Weird that failed.
If you look at
https://github.com/d3/d3-selection/blob/master/package.json
You can see that d3-selection compiles to dist.

**Comment by akhenry** [comment]
@thesamprice Thanks for pushing this fix. I saw this issue during a build last night as well. 

Hard-coding the paths of node dependencies into our Require configuration is brittle. That's our bad. We need a better strategy here.

I'd like to do a little testing before we merge this because I have seen inconsistencies which possibly relate to node version. This might be what we're seeing with the CircleCI build. Stand by! And thanks again

**Comment by akhenry** [comment]
Ah, the inconsistencies appear to be to be due to package-lock

**Comment by akhenry** [comment]
Open MCT was happily building on my machine without this fix, which was due to package-lock.json specifying version 1.2 of d3-selection. This doesn't explain the circleCI failure though, which should be using a fresh checkout each time, without a package lock. More investigation required...

**Comment by akhenry** [comment]
@thesamprice Ah, the problem with circle-ci is that it runs the tests as well. d3-selection is referenced from https://github.com/nasa/openmct/blob/master/test-main.js#L69 so the test step is failing.

If you run `gulp test` it should fail right now. Try changing the path in `test-main.js`, and then run `gulp test` again verify that it's fixed.

Thanks!

**Comment by thesamprice** [comment]
I think most js packages have a package.json file in their root directory.
https://github.com/d3/d3-selection/blob/master/package.json

From there they specify their main object file
 "main": "dist/d3-selection.js",

Not sure how you would integrate that into your system though.  javascript isn't my main language.

**Comment by akhenry** [comment]
@thesamprice This looks good, thanks for pushing this fix!

>I think most js packages have a package.json file in their root directory.

Good point, this would be less brittle. To support this we would need to find a way to integrate our dependencies' package.json in our existing build tooling, or switch to another build tool that handles npm dependencies with less wiring. It raises the basic question of whether we should be blindly updating our dependencies by [using a minimum version](https://github.com/nasa/openmct/blob/master/package.json#L13) though. There are [various reasons we might not want to do this](https://github.com/nasa/openmct/issues/1291#issue-185252708). An alternative solution to the problem reported here here would be to [lock down our dependency versions](#1291) a little better.

**Comment by akhenry** [comment]
Forgoing the usual [requirement for an author checklist](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md#check-lists) because this is a fairly minor build configuration change.

## Reviewer Checklist

* Changes appear to address issue? Y
* Appropriate unit tests included? N/A Build configuration change
* Code style and in-line documentation are appropriate? Y
* Commit messages meet standards? Y

**Pull request merged**
