### PR TITLE
Bugfix/issue 3898

### LINKED ISSUE #3898: "Pausing" Imagery telemetry in Fixed Time mode shows alert styling, but shouldn't
When the Time Conductor is in real-time mode, when the user pauses the view by clicking the Pause button or clicking a thumbnail view we show an alert orange border and coloring to indicate that the view will no longer be automatically updated to show new incoming imagery:

Screen Shot 2021-05-27 at 10 34 03 AM

This is correct and expected. 
However, the same styling is being applied when the Time Conductor is in Fixed Time mode:

Screen Shot 2021-05-27 at 10 22 49 AM

This doesn't make sense: the intent of the model is that Fixed Time utilizes bounded start and end datetimes and there is _no_ expectation that the latest data will be displayed. Showing the alert styling when pausing in this mode promotes a false expectation that the user _will_ see the latest data if they unpause the view.

The Imagery view in Fixed Time mode should be changed as follows:
- Do not display the Pause button.
- Clicking a thumbnail shouldn't "pause" the view, and therefore no alert styling should ever be displayed.
- If the Time Conductor is in real-time mode, and the user pauses the view and _then_ switches to Fixed Time mode, the currently selected thumbnail should still be selected but the Pause button should be hidden and the alert styling should not be displayed.

### PR DESCRIPTION
**Pull request by khalidadil**
Fixes #3898

### Author Checklist

Check | Passed
-- | --
Change is backwards compatible | Y
Changes address original issue? | Y
Unit tests included and/or updated with changes? | N
Command line build passes? | Y
Changes have been smoke-tested? | Y
Testing instructions included in associated issue? | Y

### CODE REVIEW

**Comment by khalidadil** [comment]
@charlesh88 Let me know if this doesn't fully addresses #3898

**Comment by nikhilmandlik** [comment]
Hi @khalidadil thanks for fixing this, can you upload screen shot of result, also one concern when are in fixed time and have end time as future time, when we click on image it should keep showing new images in thumbnails also wondering what happens when thumbnails images are full does it scrolls to right `scrollToRight`?

**Comment by khalidadil** [comment]
@nikhilmandlik I'm adding a screen capture here. I don't quite understand what you mean about the scrolling. I don't see any scrolling when setting the fixed timespan end time in the future.

https://user-images.githubusercontent.com/2343076/135117142-aaebdff9-7b8e-45be-bef1-1a0a195068cf.mov

**Review by nikhilmandlik — APPROVED** [review]
LGTM

**Comment by nikhilmandlik** [comment]
### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)

**Pull request merged**
