### PR TITLE
Styling to support Plotly integration

### PR DESCRIPTION
**Pull request by charlesh88**
### Overview
- Plotly style overrides to support theming applied to Plotly plots; 
- Plot legend can display a header element, related styles;
- Remove unneeded margin from propertiesHeader mixin;
- New theme constants for plot legend header;
- Increased size of plot color swatches;
- New glyphs for spectra and command icons;
- Make selector for .hover-value-enabled less selective;

Required by https://babelfish.arc.nasa.gov/fisheye/cru/OMCTNIRVSSCLIENT-2

### Author Checklist
1. Changes address original issue? Y
1. Unit tests included and/or updated with changes? N/A
1. Command line build passes? Y
1. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by charlesh88** [comment]
Hold off reviewing please for now, more changes coming...

**Comment by charlesh88** [comment]
Ok, this branch is ready to review.

**Comment by charlesh88** [comment]
@akhenry Per request, moved plotly SCSS into its own include file.

**Comment by akhenry** [comment]
Looks good to me, thanks.

## Reviewer Checklist

* Changes appear to address issue? Y
* Appropriate unit tests included? N/A
* Code style and in-line documentation are appropriate? Y
* Commit messages meet standards? Y

**Pull request merged**
