### PR TITLE
[#5522] No Code Coverage for toggleClass utility function in src/utils/template/templateHelpers.js

### LINKED ISSUE #5522: No Code Coverage for toggleClass utility function in src/utils/template/templateHelpers.js
#### Summary
There is currently not code coverage for the `toggleClass` function in `src/utils/template/templateHelpers.js`. I would like to add tests that validate this function works as expected.
### Testing Instructions
- Navigate to the new `src/utils/template/templateHelpersSpec.js` file
- Update line 32 to the following (prepending an f to describe)(this is to ensure no other test suites are run):
```javascript
fdescribe('toggleClass', () => {
```
- Run `npm test`
- See that all the new tests pass

### PR DESCRIPTION
**Pull request by Drew-Daniels**
Closes #5522 

### Describe your changes:
I have added tests that validate the `toggleClass` function in `src/utils/template/templateHelpers.js` works as expected by validating:
- What happens when various arguments are passed to this function (i.e., when is it expected to throw/not throw)
- That a class can be _added_ to an element, under various circumstances (i.e., when the element has no classes, a single class, or multiple classes already applied).
- That a class can be _removed_ from an element, under various circumstances (i.e., when the element has no classes, a single class, or multiple classes already applied).

#### To Test:
- Navigate to the new `src/utils/template/templateHelpersSpec.js` file
- Update line 32 to the following (prepending an `f` to `describe`)(this is to ensure no other test suites are run):
```javascript
fdescribe('toggleClass', () => {
```
- Run `npm test`
- See that all the new tests pass

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [X] Changes address original issue?
* [X] Unit tests included and/or updated with changes?
* [X] Command line build passes?
* [X] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by Drew-Daniels** [comment]
I have included testing instructions in issue #5522 , but it appears that the build is not seeing them:

Any ideas on something I might be missing/should fix?

image

**Comment by ozyx** [comment]
> I have included testing instructions in issue #5522 , but it appears that the linter is not seeing them:
> 
> Any ideas on something I might be missing/should fix?
> 
> image

Hi Drew, 

No need to worry about this. It's an issue with our current PRCop config which I will be fixing shortly. I've gone ahead and edited your PR so that PRCop sees the checkbox as 'checked' (it's only detecting lower-case `x` checks e.g. `[x]`). Thanks again for contributing and we will be reviewing this soon!

**Comment by Drew-Daniels** [comment]
> > I have included testing instructions in issue #5522 , but it appears that the linter is not seeing them:
> > Any ideas on something I might be missing/should fix?
> > image
> 
> Hi Drew,
> 
> No need to worry about this. It's an issue with our current PRCop config which I will be fixing shortly. I've gone ahead and edited your PR so that PRCop sees the checkbox as 'checked' (it's only detecting lower-case `x` checks e.g. `[x]`). Thanks again for contributing and we will be reviewing this soon!

Got it, sure thing and thanks for the update Jesse!

**Comment by unlikelyzero** [comment]
Thank you @Drew-Daniels ! Let us know if you're interested in working on any more test coverage!

**Review by unlikelyzero — APPROVED** [review]

**Pull request merged**
