### PR TITLE
Review and publish Open MCT Style Guide v1

### PR DESCRIPTION
**Pull request by charlesh88**
v1 of the Style Guide is ready to be published. For #1233.

### Author Checklist

1. Changes address original issue? Y
1. Unit tests included and/or updated with changes? N/A
1. Command line build passes? Y
1. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by larkin** [comment]
Charles to reintegrate with master, and then reassign for review and merge with master.  After that, we need to open an issue to export this and publish it on the website.

**Comment by charlesh88** [comment]
@VWoeltjen Sorry, thought I'd done the merge and fix already. Will take a look now.

**Comment by charlesh88** [comment]
Woot! Circleci is happy, therefore I am happy.

**Comment by VWoeltjen** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
