### PR TITLE
[Notebook] Add active user to entries

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes: 

### Describe your changes:

Added new functionality if a user exists, to add that username to notebook entries and snapshot entries. Updated related code to work with new async user code. Updated and added test.

closes: #4599

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Review by nikhilmandlik — APPROVED** [review]
LGTM

**Comment by nikhilmandlik** [comment]
@charlesh88  @jvigliotta do we need to add sort by user to entries?

**Comment by akhenry** [comment]
@charlesh88 to review and @nikhilmandlik to merge if ok.

**Review by charlesh88 — APPROVED** [review]
LGTM; layout sanding and shimming to be done by @charlesh88 in a separate PR.

**Review by nikhilmandlik — APPROVED** [review]
LGTM

**Pull request merged**
