### PR TITLE
Gauge limits

### LINKED ISSUE #5155: [Gauge Plugin] Limits and Composition Issues
(https://github.com/nasa/openmct/issues/4896#issuecomment-1115430493)

Think this is related to #5139 as well

#### Summary

When you add a telemetry item, that does not have set limits and you do not have manually set limits on the gauge property, "NaN" will show where the min and max limits should or should not.

Also, if you remove an item from the gauge (via the tree or the elements pool), then the gauge itself will still show the value from the telemetry item. This can be fixed by navigating away and returning or refreshing.

#### Testing instructions

1. Add a telemetry item without limits provided to a gauge (note, NaN is displayed for min/max values)
2. Remove a telemetry item from a gauge (via tree or elements pool (note, the value of the telemetry is still displayed

#### Environment

Version: 2.0.3
Build Date: Mon May 02 2022 15:46:20 GMT-0700 (Pacific Daylight Time)
Revision: 663f42ad2ed1a746a548533c6811ffc25ba08cc4
Branch: release/2.0.3

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

### PR DESCRIPTION
**Pull request by nikhilmandlik**
Closes #5155 #5139

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

Screen Shot 2022-05-03 at 9 57 04 AM

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@nikhilmandlik please review the visual change and change the target branch

**Review by unlikelyzero — CHANGES_REQUESTED** [review]
@nikhilmandlik please review the visual test change and also modify the target branch to master

**Review by unlikelyzero — APPROVED** [review]

**Review by jvigliotta — CHANGES_REQUESTED** [review]
Looking nice! Can we change the `v-if`'s to check computed values instead of containing logic? That should give a little performance bump due to caching.

**Review by charlesh88 — APPROVED** [review]
LGTM

**Review by jvigliotta — APPROVED** [review]
Nice! LGTM!

**Comment by nikhilmandlik** [comment]
> Nice! LGTM!

ship it

**Pull request merged**
