### PR TITLE
Ensure time conductor mode is set when synchronizing time range

### LINKED ISSUE #7729: Synchronize time conductor feature for plots not working
#### Summary
When you pause a plot, an option appears to synchronize the time conductor to the time range of the plot. Clicking this should change the time conductor to fixed time span and set the bounds. This is not currently working.

#### Expected vs Current Behavior
Clicking the synchronize time conductor button in plot actions should change the time conductor to fixed time span and set the bounds. 

#### Steps to Reproduce
1. View any telemetry in a plot view in real time mode
2. Pause the plot by using the pause control when hovering over the plot
3. Now click the synchronize time conductor control.
4. Notice that the time conductor does not change to fixed time span with the specified bounds.

#### Environment

* Open MCT Version: 4.0.0
* Deployment Type: VIPER dev / she hulk
* OS: All
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

image

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #7729 

### Describe your changes:
Use setMode API to set the time span as well as the bounds instead of the old bounds time API.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@shefalijoshi we should add a test in the timeconductor suite

**Comment by akhenry** [comment]
Tests, please. Nothing should be pushed any more without tests.

**Review by davetsay — CHANGES_REQUESTED** [review]
Looks good. Can you write a test?

**Comment by shefalijoshi** [comment]
> @shefalijoshi we should add a test in the timeconductor suite

I'll write a test in the plots suite since this is specific to a plots control

**Comment by shefalijoshi** [comment]
Test updated.

**Review by davetsay — APPROVED** [review]
LGTM

**Review by unlikelyzero — APPROVED** [review]
LGTM

**Comment by davetsay** [comment]
@shefalijoshi , approved but looks like there are lint errors

**Pull request merged**
