### PR TITLE
Missing items

### PR DESCRIPTION
**Pull request by charlesh88**
Visual indication for domain objects that are missing due to a change in a data dictionary or other reason.

**IMPORTANT** This PR does not yet include test cases, and I'm not even sure how to functionally test this for real. Any guidance on this would be appreciated.

### Changes
- New CSS class 'is-missing';
- Normalize object type icons as a markup `*__type-icon` to support styling and positioning of `is-missing__indicator` as a markup element;
- Application to tree items, l-browse-bar in main view, Folder grid and List views, plot legends, object labels. Tabs view, Layout frames, 
- Significant improvements for cursor lock indicators in plots;
- Plot legend fixes, added overflow scrolling for collapsed and expanded legends;
- Removed commented code;

### Author Checklist
1. Changes address original issue? Y
1. Unit tests included and/or updated with changes? N/A
1. Command line build passes? Y
1. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by deeptailor** [comment]
@charlesh88 - Has a conflict, once resolved I can merge

**Comment by charlesh88** [comment]
@deeptailor Conflict resolved, thanks.

**Comment by deeptailor** [comment]
@charlesh88 - Failing linter

**Comment by charlesh88** [comment]
Fixed linting issues and merged in latest master.

**Comment by deeptailor** [comment]
## Reviewer Checklist
Changes appear to address issue? Yes
Appropriate unit tests included? N/A
Code style and in-line documentation are appropriate? Yes
Commit messages meet standards? Yes
Has associated issue been labelled unverified? (only applicable if this PR closes the issue) @charlesh88 - need to add testing notes

**Comment by akhenry** [comment]
Have created [an issue for this](https://github.com/nasa/openmct/issues/3182). Needs improving though. 

I have also provided some testing instructions for how to make objects missing, but needs more specific instructions for how to test these changes once you have a missing object.

**Comment by charlesh88** [comment]
Issue for this with testing notes is #3179.

**Pull request merged**
