### PR TITLE
Mutation API

### PR DESCRIPTION
**Pull request by akhenry**
Switched to getters and setters, and updated todo example. 

Current it converts old style objects to new style ones fairly crudely (re-requests them inside the view). This will need a bit of extra plumbing at a higher level (eg. in MctView) for a more permanent solution.

The ToDo example is not actually using event paths at the moment for listening, it's reacting to an object-wide wildcard event. It could be refactored to listen to changes on tasks. Which brings me to my last point...

We are going to have to be super careful about keeping objects in sync between views. In this case I've done it by updating the whole object whenever it changes. This may dissuade the use of using property paths for triggering view updates. A possible approach to this is to avoid using object references and define view functions so that they operate on values passed into them, rather than using objects as member variables. For example, `TodoView.render` could accept a task list, and then `show` could bind to `tasks` instead of the wildcard `*`.

### CODE REVIEW

**Comment by akhenry** [comment]
Switched to getters and setters, and updated todo example. 

Current it converts old style objects to new style ones fairly crudely (re-requests them inside the view). This will need a bit of extra plumbing at a higher level (eg. in MctView) for a more permanent solution.

The ToDo example is not actually using event paths at the moment for listening, it's reacting to an object-wide wildcard event. It could be refactored to listen to changes on tasks. Which brings me to my last point...

We are going to have to be super careful about keeping objects in sync between views. In this case I've done it by updating the whole object whenever it changes. This may dissuade the use of using property paths for triggering view updates. A possible approach to this is to avoid using object references and define view functions so that they operate on values passed into them, rather than using objects as member variables. For example, `TodoView.render` could accept a task list, and then show could bind to 'tasks' instead of the wildcard '*'.

**Comment by larkin** [comment]
Generally the developers using this system to watch for changes will be the same ones triggering the changes (e.g. I make a plot view, I make a plot options view, I expect a certain granularity of events). When we do automatic form generation that may be a bit different but will likely be well documented.

We should have some guidelines that answer questions like "when should I listen to a wildcard versus a specific child property?" or "when should I listen to an object instead of an object subproperty?  

My example for the second case:
```json
{
    "yAxis": {
        "min": undefined,
        "max": undefined,
        "autoscale": true
    }
}
```
Question here: should you listen to `yAxis` or `yAxis.min`, `yAxis.max`, and `yAxis.autoscale`?  In this case, there is a complex validation relationship between the three fields; `min` and `max` are only valid if `autoscale` is false, and if `autoscale` is false then both of them must be specified and satisfy certain constraints.  Ultimately, you expect all of them to be set at the same time thus you can get by setting/watching `plot.yAxis`.

> We are going to have to be super careful about keeping objects in sync between views. In this case I've done it by updating the whole object whenever it changes. This may dissuade the use of using property paths for triggering view updates. A possible approach to this is to avoid using object references and define view functions so that they operate on values passed into them, rather than using objects as member variables. For example, TodoView.render could accept a task list, and then show could bind to tasks instead of the wildcard *.

Agree, I think the strategy is "keep the view in sync; don't keep a copy of the object around because that may be invalid".  I think your "use the values passed to the listener, not a object reference" is a good option for that.

**Comment by akhenry** [comment]
@larkin 
> should you listen to yAxis or yAxis.min, yAxis.max, and yAxis.autoscale

Yeah this case in particular worries me actually. The approach I've taken uses the path provided to the setter to notify listeners, and we need to be careful to make sure that it's clear to developers which listener `paths` will be triggered and which will not. eg.

``` javascript
mutableObject.set("yAxis.min", 5);
```
This will trigger listeners on `yAxis.min`. Additionally, I have implemented `MutableDomainObject` such that it will also trigger on listeners of `*` and `yAxis`. But how far up the chain should we go? For deeply nested objects, should listeners be triggered on each enclosing object? Even worse, what should happen if someone does:

```javascript
mutableObject.set("yAxis", {"min":5, "max":10, "autoscale": false})
```

In the current implementation listeners on `yAxis.min` will not be notified, but listeners on `yAxis`, and `*` would be. Introspection could be used to fire listeners for each property on the object being set, but I would question how practical this is, especially in the case of nested objects. At that point we might as well be implementing object diffing.

**Comment by larkin** [comment]
> @akhenry 
> ... how far up the chain should we go? For deeply nested objects, should listeners be triggered on each enclosing object?

No, I think not.  Only trigger for the path that is specified + the wildcard "all changes" path.

>  @akhenry
> we need to be careful to make sure that it's clear to developers which listener paths will be triggered and which will not

Here's how I'd describe it:

> `set` triggers listeners for the path specified and for no other paths.  e.g. `set('yAxis.min', value)` will notify `yAxis.min` listeners but will not notify `yAxis` listeners.  It is up to the developer to `set` values at the level of granularity that makes sense for potential listeners.  When developing code for usage by others, either document the paths that are important to listen to, or instruct people to listen to all changes.

In the case of our plot, I think you set `yAxis` and you listen for `yAxis`, because all of the properties must be changed at the same time.

**Comment by akhenry** [comment]
@akhenry 
> ... how far up the chain should we go? For deeply nested objects, should listeners be triggered on each enclosing object?

@larkin
>No, I think not. Only trigger for the path that is specified + the wildcard "all changes" path.

I think this is a somewhat contentious issue. The simplicity of only triggering events for the specific path used in the setter is a compelling one. I do think that longer term however developers will not always know which exact path is used to change an object property, and should be allowed some flexibility here. I think that developers would expect a property change on an object to trigger listeners on the object itself at a minimum.

That said, I think for now it's best to stick with a minimum feature set and build on it as required, so for now events will only be triggered on the exact setter path used + the wildcard `*`. Some implementations of EventEmitter support wildcard names, but EventEmitter3 does not (possibly for performance reasons). We might consider switching to another implementation to allow more flexibility in specifying event listener paths, or we could roll our own.

**Comment by larkin** [comment]
Going to merge this for basic mutation support, let's discuss implementation and thoughts next week.

**Pull request merged**
