### PR TITLE
Upgrade moment to 2.25.3

### PR DESCRIPTION
**Pull request by akhenry**
Fixes https://github.com/nasa/openmct/issues/2999

Cannot get Open MCT to build with 2.25.0 or 2.25.1 for reasons detailed in linked issue, so have upgraded to latest working version of moment. I have also locked the version in package.json to avoid this problem in future. 

## Author Checklist

* Changes address original issue? Y
* Unit tests included and/or updated with changes? N/A - Change in dependency version
* Command line build passes? Y
* Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by shefalijoshi** [comment]
@akhenry I've tried building with moment 2.25.3 and openMCT appears to build and run without errors. Do we still want to lock the version to 2.24.0?

**Comment by akhenry** [comment]
@shefalijoshi Ah, Thanks for checking! 2.25.3 was not available when PR was pushed. I'll update to 2.25.3

**Comment by akhenry** [comment]
### Testing notes

The issue as originally reported caused the build to break. Because the CI environment is now building this is sufficient to validate that the build itself is fixed.

In addition to verifying that the build is fixed, some regression testing should be performed in places where moment is used.
eg.
1. Plots, 
2. Tables
3. LAD tables
4. The time conductor
5. Alphanumeric displays in Display Layouts

No specific compatibility issues are anticipated, however general testing should be performed using these object types to verify that no regressions have been introduced. The tester should verify that dates are being formatted correctly, and that no errors appear in the JavaScript console.

**Comment by jvigliotta** [comment]
Verified
Looks fixed in Plots, Tables, LAD Tables and Time Conductor, wasn't a 100 on how to fix it in Alphanumeric displays, but from the dates I could see, they looked to be formatted correctly.

**Comment by akhenry** [comment]
Verified fixed, 05/12/2020

**Pull request merged**
