### PR TITLE
Addresses notebook snapshot that doesn't preserve display bounds (#2915)

### PR DESCRIPTION
**Pull request by johnriedel**
* show proper x/y axis ranges at the time snapshot was taken

* apply update to both snaphot loading and previewing

* added support for stacked plots

Test single plot.....
1. Add Sine Wave Generator and Notebook objects to workspace
2. Open Notebook and start a new entry
3. Open Sine Wave Generator
4. Zoom into sine wave plot via +/- or mouse left-click lasso
5. Take a notebook snapshot of the Sine Wave Generator and (1) save to notebook entry previously created, and (2) save to notebook snapshots
6. Open notebook
7. Click snapshot **thumbnail** image to make sure x and y axes match what you took a snapshot of, including time and zoom levels
8. **Preview** your snapshot (via drop menu >> Preview) to make sure x and y axes match what you took a snapshot of, including time and zoom levels
9. **Open** your snapshot (click snapshot hyperlink) to make sure x and y axes match what you took a snapshot of, including time and zoom levels
10. Now open notebook snapshots via indicator menu at top
11. Click snapshot **thumbnail** image to make sure x and y axes match what you took a snapshot of, including time and zoom levels
12. **Preview** your snapshot (via drop menu >> Preview) to make sure x and y axes match what you took a snapshot of, including time and zoom levels
13. **Open** your snapshot (click snapshot hyperlink) to make sure x and y axes match what you took a snapshot of, including time and zoom levels

Test multi-plots.......
1. Add Sine Wave Generator, Notebook, and Stacked Plot objects to workspace
2. Open Notebook and start a new entry
3. Add two or more Sine Wave Generators to stacked plot
4. Set a random zoom level in each sine wave plot via +/- or mouse left-click lasso
5. Take a notebook snapshot of the Stacked Plot and (1) save to notebook entry previously created, and (2) save to notebook snapshots
6. Open notebook
7. Click snapshot **thumbnail** image to make sure each plot's x and y axes match what you took a snapshot of, including time and zoom levels
8. **Preview** your snapshot (via drop menu >> Preview) to make sure each plot's x and y axes match what you took a snapshot of, including time and zoom levels
9. **Open** your snapshot (click snapshot hyperlink) to make sure each plot's x and y axes match what you took a snapshot of, including time and zoom levels
10. Now open notebook snapshots via indicator menu at top
11. Click snapshot **thumbnail** image to make sure each plot's x and y axes match what you took a snapshot of, including time and zoom levels
12. **Preview** your snapshot (via drop menu >> Preview) to make sure each plot's x and y axes match what you took a snapshot of, including time and zoom levels
13. **Open** your snapshot (click snapshot hyperlink) to make sure each plot's x and y axes match what you took a snapshot of, including time and zoom levels

Author Checklist:
1. Changes address original issue? Yes
2. Unit tests included and/or updated with changes? No
3. Command line build passes? Yes
4. Changes have been smoke-tested? Yes

### CODE REVIEW

**Comment by akhenry** [comment]
Addresses #2915

**Comment by jvigliotta** [comment]
Hi @johnriedel ! This is some really nice work, I apologize that it's taken us so long to review it. I have a couple of questions. Does this solve the original issue of the "time" bounds not showing correctly in the preview? It looks like this would preserve the viewBounds (so if you're zoomed in), but I didn't see any fixes for the time bounds not showing in preview. I also tried to test this, but since so much time has passed since then, there seem to be a good bit of errors (not your fault).

@akhenry do we want @johnriedel to update this code so we can use the preserving viewBounds?

**Comment by johnriedel** [comment]
Hi @jvigliotta . Thanks for the kind words. My recollection of the work I did on this project is poor since it's been quite a while since I've worked on it. So unfortunately I'm unable to adequately answer your question(s). When my schedule allows, I'll have to git pull the latest and take a look at the code. However things are a bit busy at the moment and I won't be able to get to it right away.

**Comment by nikhilmandlik** [comment]
Hi @johnriedel Thanks for making these changes, 

@charlesh88 Need your help with validating some behavior regarding snapshots from above test cases
eg: 
8) Preview your snapshot - I think it is behaving correctly (but leave it you to answer if changes suggested here improve the behavior)
9) looks like an improvement/enhancement?

what do you think?

**Comment by akhenry** [comment]
This appears to be addressing a slightly different, but related issue that I actually don't think we're tracking right now.

The original issue related specifically to time conductor bounds not being observed in previews (although it could have been stated more clearly).

What this PR appears to be addressing is that plot zoom and pan bounds are not observed at all in snapshots, which is potentially an even bigger issue that we're not tracking right now.

I am going to create a new issue for the latter problem, and link this as a potential solution.

**Comment by akhenry** [comment]
There are two potential paths forward here:
1. Change the bounds to match the zoom bounds, and reconstitute the plot using the conductor bounds instead of zoom state
2. We embed the zoom state of the plot and _treat it as zoom_ when we reconstitute the plot. ie. instead of setting the plot axes directly (as this PR does), we load the plot and zoom into the previously zoomed extents. This would do the same thing as marquee zoom but programmatically. It would push the new zoom state onto the zoom stack, etc.

**Comment by nikhilmandlik** [comment]
@shefalijoshi little help to review way to `store/get plot bounds changes`

**Comment by shefalijoshi** [comment]
@johnriedel The Plots code here is using old Angular plots. We've ported those to Vue. Could you please rebase and resolve the conflicts here so we can re-review?
Thanks.

**Comment by nikhilmandlik** [comment]
hi @johnriedel  we have completed plot refactor and we can start with fixing plot related changes now.
I can guide you on how to proceed, let me know if you are still want to merge this pr/change.

**Comment by shefalijoshi** [comment]
@johnriedel Please let us know if you're available to go over the changes as @nikhilmandlik suggested.

**Comment by jvigliotta** [comment]
@johnriedel we're going to close this for now and put it into our development schedule, if you'd like to take a look before we get a chance let us know. Thank you for your work!

**Pull request closed without merging**
