### PR TITLE
Fixes issue #2537 Removes unused isEditing parameter for the view method of ViewProviders.

### PR DESCRIPTION
**Pull request by shefalijoshi**

### CODE REVIEW

**Comment by deeptailor** [comment]
@shefalijoshi - was this commit reverted?

**Comment by shefalijoshi** [comment]
Nope it wasn't.

**Comment by akhenry** [comment]
The revert message is very confusing. The code changes appear to be in TCR.

**Comment by akhenry** [comment]
Verified fixed 12/06/2019. Tested by creating various objects (display layout, tables, flex layouts, plots)

**Comment by charlesh88** [comment]
Testathon 12-06-19: verified fixed.

**Pull request merged**
