### PR TITLE
[Timelist] Selectively filter activities only for realtime - 5772

### PR DESCRIPTION
**Pull request by michaelrogers**
Closes  #5772 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by shefalijoshi** [comment]
@michaelrogers I tested this locally and it doesn't look like it works properly in local clock mode. Can you please retest?

**Comment by unlikelyzero** [comment]
@michaelrogers is this now good to go to re-review?

**Comment by michaelrogers** [comment]
> @michaelrogers is this now good to go to re-review?

Not yet. Looking into it now.

**Review by charlesh88 — CHANGES_REQUESTED** [review]
I was not involved with the solution discussion for this issue, and don't think the implemented solution makes sense. This should probably work the same way that the Timestrip View works, but in reality this needs more design review.

**Comment by michaelrogers** [comment]
@charlesh88 - I'll move this PR back into Draft mode until it can be updated from a design pass.

**Comment by charlesh88** [comment]
@charlesh88 talking with @shefalijoshi 2023-01-30: 
Here's the new thinking about the solution, thanks to Shefali: given that the Time List View uses its own timeframe settings (show future, current, past events) and effectively ignores the Time Conductor's bounds, in Fixed Time mode we should temporarily use the Start datetime as "now" for the Time List view (TLV). This allows the TLV to have a meaningful view in Fixed Time mode, and honors the overall model of how the TC governs time, and how the TLV works. In the future when we separate out clock (local, remote) from time span handling (real-time, fixed time) the TLV can be augmented to use the remote clock's "now" instead of having to rely on the TC's Start datetime.

**Comment by shefalijoshi** [comment]
Closing this. @michaelrogers will open a new PR as the direction for fixing this issue has changed.

**Pull request closed without merging**
