### PR TITLE
Frontend 1047

### PR DESCRIPTION
**Pull request by charlesh88**
### Notes
I'd love to get this merged soon so we can apply to new ongoing front-end related projects like the new Time Conductor. Although I've been very diligent about merging master in on a periodic basis, as has been mentioned, this is probably best squash merged. Related work has also been done in [WARP](https://developer.nasa.gov/ResourceProspector/warp/issues/204) and [VISTA](https://github.jpl.nasa.gov/MissionControl/vista/issues/388) repos; PR's should be filed there once this is merged into open master.

`getGlyph` functions were recast as `getCssClass` and their comments were all updated. We may need a followup issue to update documentation around glyphs that isn't generated from code. 

### Change Summary

- Extensive work in markup, sass, JS and tests to convert glyph approach to CSS classes. Icons for objects and actions are now defined with a "cssclass" property, using the naming pattern `.icon-*`. A full list of available icon classes can be referenced in /platform/commonUI/general/res/sass/_glyphs.scss and in the [UI Symbols Font Map](https://docs.google.com/spreadsheets/d/1078wA0N0zCQnBGZXz4Dj5PUuP_JoPgrMlIyshvkjO3s/edit#gid=273833302) spreadsheet.
- Updates and additions to symbols font glyphs to improve legibility, understandability and new icons for objects like overlay and stacked plot objects.
- New look and better markup for the pane collapse/expand controls.
- Mobile also completely updated and should be in parity.
- Class name cleanup and normalization for button and button-menu-related classes.
- New .s-icon-button and .s-toggle-icon classes.
- Timeline resource icon buttons now use .s-toggle-icon class.
- Improved sass function and classes for splitters; support for new small splitter requested for Timelines.
- .s-status-* classes updated and fixed.
- Fixed "snow" theme color issues with button hovers, other.
- Multiple other minor UI / CSS improvements and fixes.

### Author Checklist

1. Changes address original issue? Y
1. Unit tests included and/or updated with changes? Y
1. Command line build passes? Y
1. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Changes look good (love how much easier `icon-database` is to understand than `glyph: "D"`).

It looks like these changes are not backwards-compatible; will WARP/VISTA display incorrectly if this is merged to `master` until those corresponding PRs are merged? (Holding off on merge for now so that we can coordinate the timing on those if so.)

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Comment by charlesh88** [comment]
@VWoeltjen You're correct: all the symbols in WARP and VISTA will break until those PR's are merged; we should sort of do this at once. Let's talk about this timing in the 8/2/16 tagup.

**Comment by larkin** [comment]
@charlesh88 are the warp/vista branches ready to go?  I think we can just merge and push pronto and all should be fine.

**Comment by VWoeltjen** [comment]
Squash-merged in d1e1ba1c66fbb17474023e938e18f498118baf67; closing this PR

**Pull request closed without merging**
