### PR TITLE
Enter key submit dialog form

### LINKED ISSUE #2605: [Forms] Forms should be submitted on return keypress
Steps to Reproduce
1. Open a form, such as editing an objects properties
1. Focus an input
1. Press Return
1. Observe that form is not submitted and a console error is logged.

`
Uncaught TypeError: Cannot read property 'type' of undefined
    at setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)
setFieldValue	@	onloadwff.js:71
formKeydownListener	@	onloadwff.js:71
`

pressing return on field focus

### PR DESCRIPTION
**Pull request by depperm**
Fixes #2605 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

### CODE REVIEW

**Comment by nikhilmandlik** [comment]
Hi @depperm  Thanks for this change, we need to reimplement this with new form refactor code (https://github.com/nasa/openmct/pull/4478) , @depperm  ll update you and add you as author for change once its merged.

**Comment by unlikelyzero** [comment]
@depperm please take another look at this now that the blocker PR https://github.com/nasa/openmct/pull/4478 has merged!

**Comment by jvigliotta** [comment]
Hey @depperm I think, after some recent updates, that this should be done in this file: https://github.com/nasa/openmct/blob/master/src/api/forms/components/FormProperties.vue would you be able to make this change there?

**Comment by depperm** [comment]
@jvigliotta currently pretty busy, it'll be a couple of months before I can get back to this

**Comment by jvigliotta** [comment]
@depperm understandable, we appreciate the work you've contributed thus far so thank you! We may assign this to a member on the team. @akhenry @nikhilmandlik do we want to add this to upcoming sprints?

**Comment by akhenry** [comment]
Closing PR for now due to form refactor. @depperm please submit a new PR if and when you get a chance to implement this in the refactored codebase. Thank you!

**Pull request closed without merging**
