### PR TITLE
[Time Conductor] Persist Time Conductor state in URL

### PR DESCRIPTION
**Pull request by akhenry**
Currently large delta with master due to it being based on open1193 / #1287 which has not been merged yet. Should either change base to open1193 for review, or wait until #1287 is merged.

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by akhenry** [comment]
Reassigning back to me, found an issue with deltas loaded from URL not being reflected in UI.

**Comment by larkin** [comment]
@akhenry After squash-merging #1287 I went ahead and rebased this branch onto master and resolved some small conflicts.  Hope that's helpful for you, but it does mean you'll have to wipe out your local branch and checkout a new copy from origin.  If this is a pain in the butt, feel free to force-push your local version of open1231.  I also archived the old version of the branch as open1231-pre-rebase just in case.

**Comment by akhenry** [comment]
I take it back, this totally works, deltas and all. *CONFUSION INTENSIFIES*

**Comment by VWoeltjen** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
