### PR TITLE
3745 - [Imagery] Remove roll and pitch as required keys for orientation

### PR DESCRIPTION
**Pull request by mariuszr**
Resolves: #3745

### CODE REVIEW

**Comment by mariuszr** [comment]
@jvigliotta Is there another way to set up reviewers as it is unavailable for me now?

**Comment by jvigliotta** [comment]
Hi @mariuszr ! So, to contribute to Open MCT you will need to fill out a [Contributor License Agreement (CLA)](https://nasa.github.io/openmct/static/files/ind-cla-open-mct.pdf), which you can find here:  once that's signed, you can send it to arc-dl-openmct@mail.nasa.gov once we have that in our system, then you can start merging in approved changes. Also, take a look at our contribution guidelines at https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md as they'll outline standards for commit messages, PR documentation, code styles, etc.

**Comment by mariuszr** [comment]
Hi @jvigliotta ! Thank you for the clarification

**Comment by jvigliotta** [comment]
@mariuszr as you mentioned in the PR this was actually fixed by the PR #3744 sorry for the confusion. Thank you very much for contributing though and if you see anything else you'd like to work on let us know!

**Pull request closed without merging**
