### PR TITLE
Use ObjectAPI.save in Display Layout and New folder action 

### LINKED ISSUE #3371: "Create New Folder" Action throws an error in Couch DB
To recreate:
1. Using a deployment configured with Couch DB persistence, navigate to a folder.
2. Right click on the folder and select the "Add New Folder" action.
3. Notice that no new object appears
4. Open the JavaScript console and observe that the following errors appear:

```
composition-loader.js:36 Uncaught (in promise) TypeError: Cannot read property 'type' of undefined
    at s.add (composition-loader.js:36)
    at Object.n [as callback] (vue.min.js:6)
    at CompositionCollection.js:306
    at Array.forEach (<anonymous>)
    at t.emit (CompositionCollection.js:302)
    at t.add (CompositionCollection.js:192)
    at t.<anonymous> (CompositionCollection.js:270)
```

```
mct-tree.vue:432 Uncaught (in promise) TypeError: Cannot read property 'identifier' of undefined
    at s.buildTreeItem (mct-tree.vue:432)
    at s.n [as buildTreeItem] (vue.min.js:6)
    at s.addChild (mct-tree.vue:439)
    at Object.n [as callback] (vue.min.js:6)
    at CompositionCollection.js:306
    at Array.forEach (<anonymous>)
    at t.emit (CompositionCollection.js:302)
    at t.add (CompositionCollection.js:192)
    at t.<anonymous> (CompositionCollection.js:270)
```

### PR DESCRIPTION
**Pull request by deeptailor**
This PR fixes #3371 

An update to Couch DB persistence surfaced an issue where we cannot create new objects via openmct.objects.mutate(object, 'created', Date.now());

A fix for this issue involves us using the .save method that was introduced recently.

### CODE REVIEW

**Comment by deeptailor** [comment]
## Author Checklist
Changes address original issue? Yes
Unit tests included and/or updated with changes? N/A
Command line build passes? Yes
Changes have been smoke-tested? Yes
Testing instructions included? Yes in issue

**Comment by deeptailor** [comment]
## Testing Instructions:

1. With console open, right click on an editable folder, and click on the New Folder action. 
1. Save the new folder, and verify that there are no 404 errors in the console and the new folder appears. 
1. Create a new Display layout, and drag in some telemetry.
1. Select the telemetry view and convert to an overlay plot or telemetry table. 
1. Verify that there are no 404 errors in the console and the conversion completed successfully.
1. Celebrate!

**Comment by deeptailor** [comment]
@jvigliotta - Take a look at the changes here, you may run into the same issue with the Duplicate Action

**Review by jvigliotta — APPROVED** [review]
## Reviewer Checklist
Changes appear to address issue? Yes
Appropriate unit tests included? Yes Updated
Code style and in-line documentation are appropriate? Yes
Commit messages meet standards? Yes
Has associated issue been labelled unverified? (only applicable if this PR closes the issue) Yes

**Pull request merged**
