### PR TITLE
[TimeConductor] Fixes Issue #925

### PR DESCRIPTION
**Pull request by dhrubomoy**
Pressing enter in date field will update bounds properly in Safari

### Author Checklist
1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? N/A
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by dhrubomoy** [comment]
@akhenry This should also fix issue #1969

**Comment by akhenry** [comment]
@dhrubomoy Thanks for your assistance with this. Your approach makes a lot of sense here. After digging into the code a little more I see that we already had support for this, but only in fixed time conductor mode, so I'm going to suggest a slightly different approach in the interests of consistency.

The inputs are all wrapped in a form, and there is a hidden `submit` input. So hitting enter triggers the form's [submit handler](https://github.com/nasa/openmct/blob/e2217e008a1325a0f5f2fc22256b6cbe575c7859/platform/features/conductor/core/res/templates/time-conductor.html#L14). Currently the submit handler sets the model from the view for the bounds inputs, but not for the delta/offset inputs. So we simply need to add a call to `setOffsetsFromView()`. I'd be inclined to do this conditionally, based on mode, so the new submit handler might look like -
```
ng-submit="tcController.isFixed ? tcController.setBoundsFromView(boundsModel) : tcController.setOffsetsFromView(boundsModel)"
```

**Comment by dhrubomoy** [comment]
@akhenry Wow. Thanks. Thats a much much better solution. Reverted the previous commit and made the change that you mentioned. 
To make the form submit on enter in Safari, had to use `visibility: hidden` instead of `display: none` style. So changed the class from `hidden` to `off`

**Comment by akhenry** [comment]
@dhrubomoy Ah, good catch with Safari! 

@charlesh88 Some browsers will ignore submit buttons (in fact any form inputs) that are styled with `display:none`. Obviously `display: none` and `visibility: hidden` are two very different kettles of marine vertebrates, but since the `off` class includes `height: 0` and other rules that mean that the input should not effect the layout , is this approach ok?

**Pull request merged**
