### PR TITLE
tutorials: support arbitrary hosting directory

### PR DESCRIPTION
**Pull request by larkin**
This PR changes some of the build steps to support tutorial usage and general distribution and changes how bundles are loaded in the legacy registry.

First, registering a bundle no longer runs it by default.  After a bundle is registered, it must be enabled by calling legacyRegistry.enable(bundlePath).  

Second, I added a defaultRegistry that loads **_every_** bundle that is defined, and then enables a set of bundles that corresponds to the previous list of defaults.  This ensures that all required files are delivered in a single main.js, which simplifies distribution.  Application developers can then `enable`/`disable` the bundles they want/don't want to use.

Third, instead of taking the same tact and including css in the single file, I kept it separate.  This is helpful for development (easier to trace styles to their source) and also for fonts, images, and other files, where paths to font files are typically specified in CSS and are resolved relative to CSS.  To support these, I added a new constant, `ASSETS_PATH` which is prepended to all css urls so that they can be hosted in a separate directory.  This can be set by calling `MCT.setAssetsPath(path)` and helps to support distributions of Open MCT on non-root paths.

Finally, I tweaked webworkers to support loading webworkers from a blob instead of a url so that they can be embedded in the application.

@VWoeltjen @akhenry take a look, let me know what you think.

### CODE REVIEW

**Comment by larkin** [comment]
Also just added 7e0d67c which tweaks the gulpfile to do more lazy-requires.  This speeds up execution of gulp by a not-insignificant amount.  Makes me a bit happier.

Without lazy loading:
```bash
› time gulp
gulp  4.43s user 1.02s system 41% cpu 13.038 total
```

With lazy loading:
```bash
› time gulp
gulp  0.90s user 0.23s system 41% cpu 2.716 total
```

**Comment by VWoeltjen** [comment]
> First, registering a bundle no longer runs it by default.  After a bundle is registered, it must be enabled by calling legacyRegistry.enable(bundlePath).  

> Second, I added a defaultRegistry that loads **_every_** bundle that is defined, and then enables a set of bundles that corresponds to the previous list of defaults.  This ensures that all required files are delivered in a single main.js, which simplifies distribution.  Application developers can then `enable`/`disable` the bundles they want/don't want to use.

This makes sense to me as a transitional step. Ultimately don't want a "bundle" abstraction or a legacyRegistry/defaultRegistry exposed to application developers, but I think we're on the same page there.

> Third, instead of taking the same tact and including css in the single file, I kept it separate.  This is helpful for development (easier to trace styles to their source) and also for fonts, images, and other files, where paths to font files are typically specified in CSS and are resolved relative to CSS.  To support these, I added a new constant, `ASSETS_PATH` which is prepended to all css urls so that they can be hosted in a separate directory.  This can be set by calling `MCT.setAssetsPath(path)` and helps to support distributions of Open MCT on non-root paths.

I was thinking similarly, I think it's a good improvement to the asset-handling problem.

For the sake of pushing on the idea a little: Do we have enough assets that we really need this? We could alternately say "put this directory full of assets somewhere, and include this CSS file in your HTML file." That's not quite as simple as "just include this JS file, and call `setAssetsPath` if you aren't serving with our normal directory structure", but the practical difference (and benefit to developers) is pretty small. I'm questioning, a bit, whether the convenience justifies having custom API for this.

> Finally, I tweaked webworkers to support loading webworkers from a blob instead of a url so that they can be embedded in the application.

I like this approach. In terms of public API, I'm not thinking we need to expose `workerService`, but it's a good way to handle that problem internally.

**Comment by larkin** [comment]
> For the sake of pushing on the idea a little: Do we have enough assets that we really need this [...] whether the convenience justifies having custom API for this.

Good point, I intended this as a transitional API and will document as such.  It's currently only necessary due to how CSS loading works for various plugins (e.g. theme support, timelines, etc), and I expect we will change that with time.

> I like this approach. In terms of public API, I'm not thinking we need to expose workerService, but it's a good way to handle that problem internally.

Agree-- not a public API.

@VWoeltjen are you okay with me merging this into api-tutorials after I clarify documentation of setAssetPath?

**Comment by VWoeltjen** [comment]
> @VWoeltjen are you okay with me merging this into api-tutorials after I clarify documentation of setAssetPath?

Yep, looks good!

**Comment by larkin** [comment]
@VWoeltjen interesting bit of prior design I noticed when researching older plugin discussions, you had mentioned the need for a configurable assets path on January 22nd, 2016!

https://github.com/nasa/openmct/issues/458#issuecomment-174089306
> Note that Open MCT Web would need to provide a means to pass in a path to its assets, to allow for some flexibility in the directory structure of its deployment. Think it is fine to default this to node_modules/openmctweb/dist/assets (e.g. to assume it will be used in-place)

**Pull request merged**
