### PR TITLE
[Documentation] Updated copyright statement

### PR DESCRIPTION
**Pull request by akhenry**
### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? N/A
3. Command line build passes? Y
4. Changes have been smoke-tested? N/A

### CODE REVIEW

**Comment by akhenry** [comment]
Suggest we wait to merge this until #1047 as it touches a lot of files as well. Once #1047 is merged I will just rebase over master.

**Comment by VWoeltjen** [comment]
Just want to verify, has this update to copyright statement been reviewed with Technology Transfer Program?

**Comment by akhenry** [comment]
@VWoeltjen Yep, I've got an explicit ok from them to change the name in the copyright statement. Will double check the year, but I assume that's fine.

**Comment by larkin** [comment]
There is one solitary merge conflict with this branch and frontend-1047 that is trivial to resolve.  No reason to delay merging this; can resolve the merge conflict down the road.  Merging now prevents additional merge conflicts from popping up.

Review wise, For previous merges like this I've diff'd every file with small number of context lines, stripped off the file identifiers, put the diffs in a spreadsheet, and filtered them to find unique diffs.  Should be less than 10 unique diffs that need to be reviewed.

Or we can just go with a hail mary and assume that since tests pass everything is fine.

Pete

**Comment by akhenry** [comment]
Yep, number of unique diffs should be pretty low. As well as the copyright statements I did update a few files that were still referencing Open MCT Web.

**Comment by larkin** [comment]
I'll tackle a review on this.

**Comment by larkin** [comment]
# Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A (Changes are to comments and description strings only)
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
