### PR TITLE
[WIP] Fixes to User Experience & misc

### PR DESCRIPTION
**Pull request by ev1stensberg**
## Refactor & fix issue trackers 

- [x] ~~Notify the console when the express app is running~~

- [ ] Separated variable declarations?

- [ ] Make constructor functions instead on `ElementTelemetry.js`

- [ ]  We should definitely do some sketches on the conceptual parts, pure markdown is not a great way of showing of abstract thinking. 

- [ ] Reduce loading time? 

- [ ] Make an own linter ruleset? 
     - It is a lot of different code styles in the repo

- [ ] Create a actual website for the docs ( I can set up a quick site, though this will use React)
      - This will allow us to add a link it the description and remove the docs folder 

**Feel free to drop by any issues you got and I'll try give them a punch** 😄 

***

**Should we require CLA from PR's on an external page and not email?** 

Note: I'm interested in making this with React to measure perf vs angular. Is this something you want me to do?

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Note: I'll clean up, squash and so on after I've made all the changes in the thread. Consider this as a work thread

**Comment by VWoeltjen** [comment]
First off, really glad to see you're interested in this project!

A few notes on the items you've mentioned:

> Added New Dates to all copyrights

In the case of Open MCT's copyright notices, we're using language agreed upon with NASA's Technology Transfer Program. We are in the process of an update currently, and don't want to make changes in the repo until that is completed.

In the case of licensing info for dependencies, our guidance has been to use the specific copyright text (including years) associated with the license of the version of the software we are using.

> Notify the console when the express app is running

:+1: 

> Separated variable declarations?

Per discussion on #142 we'll be updating our code style to allow this. We would definitely welcome help getting code style up-to-date (as you've noticed, there are still several odd corners with an outdated style)

> Make constructor functions instead on ElementTelemetry.js

:+1:

> We should definitely do some sketches on the conceptual parts, pure markdown is not a great way of showing of abstract thinking.

Are there any specific sections of the documentation you're thinking of here?

One odd thing that we're doing in our documentation is rendering [nomnoml](http://www.nomnoml.com/) code blocks to PNG as part of the documentation build process. The intent was to simplify maintenance (compared to maintaining diagrams externally and checking in PNGs whenever they need to be updated) and while that much was successful, it also complicates the documentation generation process and makes the documents look incomplete/strange when viewing on GitHub. I think SVG diagrams might be the happier middle ground.

> Reduce loading time?

Definitely something we need to improve upon; we'd absolutely welcome help here.

> Make an own linter ruleset?
> * It is a lot of different code styles in the repo

We've done a bit of work on this in the #142 and #671. Agree that we need to wrangle our code style better; if there are additional jscs and/or jshint rules that would reduce this variation, that would be great.

> Create a actual website for the docs ( I can set up a quick site, though this will use React)

We're in the process of putting together a new web site for Open MCT (#815 et al), which will include these docs.

> Note: I'm interested in making this with React to measure perf vs angular. Is this something you want me to do? 

I'd be very interested to see that! We've hit several circumstances where using Angular (at least in a naive way) comes with a big performance cost.

Going forward, our plan is to be "framework agnostic" as far as views/templating goes. Work on that API is ongoing, but it should boil down to "give us your HTMLElements" plus lifecycle methods. Internally, we will still be using Angular for _most_ things, but that's mainly a question of priorities (there's not a pressing reason to move off of Angular, except in performance-sensitive areas.)

> Note: I'll clean up, squash and so on after I've made all the changes in the thread. Consider this as a work thread, I'll most likely split each change up in separate PR's for better overview. 

Thanks! Smaller PRs are both appreciated and preferred :smile:

**Comment by ev1stensberg** [comment]
## Re: Copyright 

Noted! Removed from checklist

## RE: Style/ constructor func 

Yes indeed. I was thinking about making an own eslint ruleset for NASA. For now, is it viable to change old ES6 with `import, const` etc? 

## RE: Docs

 I read through the docs, and as you mentioned with the compiling, I found it strange looking at docs with brackets and arrows. I'm also a designer, so let me know if you want me to dive into that as well ( however, I don't have much time these days, middle of exam periods & starting at a remote job with the Google Chromium team approx next week ) 

## RE: Website

Seems like you got that sorted out, no need for me to poke into that. 

## RE: React

I agree, would be cool to see performance differences! 

## RE: Summary

Do you mind giving me contributor access for all of these PR's? Would be convenient to add labels etc on my own, to simplify this for you. I understand if not so. Also, I mentioned in #915 that I've sent a mail, how is status on that part? 

Thanks for letting me help! 

Even

**Comment by ev1stensberg** [comment]
I'm also signing the CLA in the morning, FWIW :octocat:

**Comment by VWoeltjen** [comment]
Brief update - just want to confirm that we have received the signed CLA, still waiting for approval before merging #915.

> Do you mind giving me contributor access for all of these PR's / repo? Would be convenient to add labels etc on my own, to simplify this for you. I understand if not so.

Unfortunately, GitHub's permissions levels (Read/Write/Admin) aren't fine-grained enough to make this practical. We need to keep repository write access restricted to the internal team.

> Edit: I also think we could have benefits from adding Mocha as a Unit test 

What are the benefits you're thinking of? I've found Mocha a bit easier to use/configure than Karma+Jasmine on some spare-time projects, but haven't had a strong motivation to make the switch here.

**Comment by ev1stensberg** [comment]
@VWoeltjen Think you said what needed to be said. Mocha is easy to configure, and allows Unit Testing faster & more clean ( in my eyes ). Also, having checkpoints, loading time and passed+failed checks logging in terminal with Karma+Mocha is pretty neat. 

About the GitHub thing. I understand. Some tips on handling PR's and such is having more labels such as "Needs Review",  "Needs CLA signed" and so on. I'll try getting some work down in June-August although I must focus on my job mainly, as you hopefully understand :smile:

**Comment by larkin** [comment]
Jasmine is great because of the built in stub/mocking support (aka `spys`).  Mocha doesn't include this (we'd have to go sinon or similar) and generally we'd like to minimize the number of dependencies, not increase.  The amount of tests that would need to be rewritten to replace jasmine.createSpy and jasmine.createSpyObject would be substantial.

Regarding "clean" testing-- I agree that some of the jasmine 1.x constructs (especially around asynchronous tests) are gross.  However, Jasmine 2.0 handles these the same way mocha does (via done callback), and we have a ticket in place for that upgrade already: https://github.com/nasa/openmct/issues/548.  Do you want to look into that?

**Comment by ev1stensberg** [comment]
@larkin I can add it to the list, although @VWoeltjen has this covered. An option could be Sinon, although you want as little dependencies as possible, I get that! Generally I don't want to dive into other peoples WIP, as they can handle that better themselves better off than me involving ( in my eyes ).

**Comment by ev1stensberg** [comment]
@larkin Sorry for being a bit inactive lately, but wouldn't `expect` + `mocha` solve this? In that case, yay/nay?

**Comment by ev1stensberg** [comment]
@VWoeltjen  I'm visiting SF in August. Do you know if there's anyone at NASA doing front-end there that I could visit?

**Pull request closed without merging**
