### PR TITLE
PascalCase files

### LINKED ISSUE #5216: [Linting] Fix casesensitive filename imports once and for all
#### Summary
We've lost a lot of manhours due to casesensitivity import bugs. In this ticket, let's rip off the bandaid and fix it once and for all with a new PR which

- [ ] Defines best practices for filename imports with Vue and JS imports
- [ ] Renames our existing files to match the best practice
- [ ] Adds a linter to our filenames to enforce all files match the case sensitive format of choice
- [ ] Add a linter for import statements

Light reading:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/filename-case.md
https://v2.vuejs.org/v2/guide/single-file-components.html

### PR DESCRIPTION
**Pull request by depperm**
Closes #5216 

### Describe your changes:
Added linting rule for files to be pascal case as referenced.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by ozyx** [comment]
Thanks for this! Could you please fix the failing tests? Let us know if you have any questions.

**Comment by depperm** [comment]
@ozyx I can't reproduce the error that circleci is showing. Am I doing something wrong?
image

**Comment by ozyx** [comment]
> @ozyx I can't reproduce the error that circleci is showing. Am I doing something wrong?
> 
> image
> 
> 

No, I think circleci is cacheing something. Will look into it today. The tests seem to pass locally and all looks good!

**Comment by unlikelyzero** [comment]
@ozyx @depperm please let me know if this is clear: https://github.com/nasa/openmct/pull/6988

**Comment by ozyx** [comment]
@depperm Now with the cacheing issue resolved (thank you @unlikelyzero :)), we're seeing this error:

```
> openmct@3.1.0-next test:e2e:stable
> npx playwright test --config=e2e/playwright-ci.config.js --project=chrome --grep-invert "@unstable|@couchdb|@generatedata" --shard=1/4

 DeploySentinel Reporter: [v0.3.4] is enabled 
[WebServer] <i> [webpack-dev-server] Project is running at:
[WebServer] <i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/root/project/dist' directory
[WebServer] <i> [webpack-dev-middleware] wait until bundle finished: /
SyntaxError: /root/project/e2e/test-data/examplePlans/ExamplePlan_Invalid.json: Unexpected token { in JSON at position 198

   at functional/planning/plan.e2e.spec.js:25

  23 | const { createPlanFromJSON } = require('../../../appActions');
  24 | const testPlan1 = require('../../../test-data/examplePlans/ExamplePlan_Small1.json');
> 25 | const testPlan2 = require('../../../test-data/examplePlans/ExamplePlan_Invalid.json');
     |                   ^
  26 | const { assertPlanActivities } = require('../../../helper/planningUtils');
  27 |
  28 | test.describe('Plan', () => {

    at Object.<anonymous> (/root/project/e2e/tests/functional/planning/plan.e2e.spec.js:25:19)


Exited with code exit status 1
```

Seems like your changes from #6954 are included in this PR. Could you please back those changes out?

**Comment by depperm** [comment]
> @ozyx @depperm please let me know if this is clear: #6988

I don't think I can schedule a re-run of tests. Clicking trigger pipeline doesn't do anything

**Comment by ozyx** [comment]
> > @ozyx @depperm please let me know if this is clear: #6988
> 
> I don't think I can schedule a re-run of tests. Clicking trigger pipeline doesn't do anything

I think only members of the @nasa organization are able to trigger builds manually. However, I did trigger a build using the instructions provided and I'm seeing the same errors, so something else is going on here @unlikelyzero .

Will investigate today and keep you posted @depperm

**Comment by ozyx** [comment]
@depperm OK.

It looks like some files were not renamed. Take a look at `src/plugins/LADTable`. We need to be careful here. When renaming files, be sure to use `git mv` so that git picks it up as a file rename. We should be okay, but there's a chance that a change like this can lose git commit history, especially given that we squash commits.

Please ensure that all files have been renamed properly and let's try again.

**Comment by depperm** [comment]
@ozyx 
> It looks like some files were not renamed. Take a look at `src/plugins/LADTable`. We need to be careful here. When renaming files, be sure to use `git mv` so that git picks it up as a file rename. We should be okay, but there's a chance that a change like this can lose git commit history, especially given that we squash commits.

Do you mean the directory name? I was under the impression this was only for Vue components not all file/dir naming convention. I can change all files. Is this the case for all naming (all .js files and directories)?

**Comment by ozyx** [comment]
> @ozyx
> 
> > It looks like some files were not renamed. Take a look at `src/plugins/LADTable`. We need to be careful here. When renaming files, be sure to use `git mv` so that git picks it up as a file rename. We should be okay, but there's a chance that a change like this can lose git commit history, especially given that we squash commits.
> 
> Do you mean the directory name? I was under the impression this was only for Vue components not all file/dir naming convention. I can change all files. Is this the case for all naming (all .js files and directories)?

Sorry, let me clarify.

[Here](https://github.com/nasa/openmct/blob/fb6c23bb91153bb19a77454ac2d10821db3edaae/src/plugins/LADTable/LADTableView.js#L23) we reference `LadTable.vue`.

But [here](https://github.com/nasa/openmct/blob/fb6c23bb91153bb19a77454ac2d10821db3edaae/src/plugins/LADTable/components/LADTable.vue) you can see that the file was never renamed, it's still `LADTable.vue`. Hence the failures when we try to bundle with webpack.

**Comment by ozyx** [comment]
Hi @depperm,

Sorry for the delay. We intend on merging this, but will need to verify that it won't impact other open PRs (difficult merge conflicts). In the past, we've had to do some of the more extensive refactorings (such as `prettier`) in stages. I need to determine if we should do the same for this PR as well.

Thanks for your patience!

**Comment by ozyx** [comment]
@depperm Could you please fix the conflict on your local repo? It seems I'm unable to fix it on the remote for some reason.

**Comment by depperm** [comment]
@ozyx merged

**Review by ozyx — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
