### PR TITLE
[Documentation] Fix code formatting

### PR DESCRIPTION
**Pull request by BogdanAlexandru**
Stumbled upon this while following the tutorial, the code block in Telemetry Adapter-Step 1 was not indented as a code block.

Is this "blocked" by this other issue, though? https://github.com/nasa/openmct/issues/1128

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Thanks for catching this! (And for drawing attention to #1128, which should have been closed.)

Before we can merge outside contributions we need a signed Contributor License Agreement; these forms, along with instructions, are available at https://nasa.github.io/openmct/contributing/

Also, for consistency with the rest of the document, could you use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) instead of indentation? Thanks again!

**Comment by BogdanAlexandru** [comment]
@VWoeltjen I can do that. I was wondering whether I should go with indent or fenced, and by looking at the document I deduced that fenced is used for diff blocks, and indent for regular code blocks. Should I update all existing indent blocks to fenced as well?

**Comment by VWoeltjen** [comment]
Ah, thanks for clarifying. I'd just update the one block; the only uses of indentation I see are for command lines, which are different enough that it doesn't strike me as inconsistent.

If you see other source code in the tutorials that is formatted differently, though, we'd be happy to see that normalized as well.

**Comment by BogdanAlexandru** [comment]
"Step 2-Expose the Telemetry Dictionary" for example also uses indent for its code blocks (not command line). I'll go through the file and see if I can find more & fix them.

Do you prefer I close this PR and make a new PR with a single commit w/ all the changes, or make an extra commit on this one?

**Comment by VWoeltjen** [comment]
Got it, I did miss that one (felt like I must be missing something :grin:). Thanks for looking through! I'd keep the same PR and just add a few commits.

**Comment by BogdanAlexandru** [comment]
Signed the CLA and sent it.

Seems it was just Step 2 that was not following the rule :smile: While at it I also made the spacing around and inside code blocks consistent throughout the document.

**Comment by VWoeltjen** [comment]
Changes look good, and thanks for taking the initiative to fix those white space issues too!

### Review Checklist

1. Changes appear to address issue? N/A (PR reports/documents issue being addressed)
2. Appropriate unit tests included? N/A (changes to documentation only)
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
