### PR TITLE
[Notebook] Example Imagery doesn't capture images #2942

### PR DESCRIPTION
**Pull request by nikhilmandlik**
resolves: https://github.com/nasa/openmct/issues/2942

Notes:
Images can be captured if, 
1. with `access-control-allow-origin` prop as * ,
1. with `access-control-allow-origin` prop has same domain (eg: if openmct is on hulk, then value should include `hulk.ndc.nasa.gov` etc)

images:
Space force: https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Seal_of_the_United_States_Space_Force.svg/1200px-Seal_of_the_United_States_Space_Force.svg.png

Nasa logo:
https://www.nasa.gov/sites/all/themes/custom/nasatwo/images/nasa-logo.svg

Screen Shot 2020-04-15 at 10 16 39 PM

Screen Shot 2020-04-15 at 10 56 35 PM

### CODE REVIEW

**Comment by akhenry** [comment]
@charlesh88 @nikhilmandlik What's the status of this?

**Comment by nikhilmandlik** [comment]
> @charlesh88 @nikhilmandlik What's the status of this?

As per Charles's comments
- [ ] Need to disable 'logging for debug purposes' using `logging: false` (easy fix)
- [ ] I also had same thought, to show notification on CORS images error, but html2canvas lib throws/handles that internally and does not provide CORS error as callback. (we only find error when we try `canvas.toBlob` but that can happen in a case other than CORS - *I think)
So still need more work to be done.

**Comment by charlesh88** [comment]
@nikhilmandlik I feel bad that this has been stale since May - is the code in here still needing review?

**Comment by akhenry** [comment]
@nikhilmandlik  Can you provide some more info on what the changes you've implemented do?

**Comment by nikhilmandlik** [comment]
> @nikhilmandlik Can you provide some more info on what the changes you've implemented do?

1. disabled logging by html2canvas, (was on by default ¯\_(ツ)_/¯)
2. enabled `allowTaint` (Whether to allow cross-origin images to taint the canvas)
3. enabled `useCORS` (load images from a server using CORS)

with these changes (on local) any external image with `access-control-allow-origin prop as *` snapshot can be taken.
eg: space force logo

without these `space force logo` shows blank on snapshot (try Hulk/Local)

**Comment by akhenry** [comment]
From the html2canvas docs -

> html2canvas does not get around content policy restrictions set by your browser. Drawing images that reside outside of the origin of the current page taint the canvas that they are drawn upon. If the canvas gets tainted, it cannot be read anymore. As such, html2canvas implements methods to check whether an image would taint the canvas before applying it. If you have set the allowTaint option to false, it will not draw the image.

@nikhilmandlik  Was `allowTaint` definitely `true` when this screenshot was taken? The behavior in the screenshot looks like what I was expect when `enableCORS` is `true`, but `allowTaint` is `false`.

**Comment by jvigliotta** [comment]
@nikhilmandlik @akhenry Hey guys, what's the status on this one? Can we get an update on what's needed to move forward? A review?

**Comment by akhenry** [comment]
@jvigliotta Has been reviewed and clarification was requested.

**Comment by nikhilmandlik** [comment]
> From the html2canvas docs -
> 
> > html2canvas does not get around content policy restrictions set by your browser. Drawing images that reside outside of the origin of the current page taint the canvas that they are drawn upon. If the canvas gets tainted, it cannot be read anymore. As such, html2canvas implements methods to check whether an image would taint the canvas before applying it. If you have set the allowTaint option to false, it will not draw the image.
> 
> @nikhilmandlik Was `allowTaint` definitely `true` when this screenshot was taken? The behavior in the screenshot looks like what I would expect when `useCORS` is `true`, but `allowTaint` is `false`.

yes,

```
useCORS: true,
allowTaint: true,
logging: false,
```

**Comment by nikhilmandlik** [comment]
Yes we need this can check one of display layout on, `dev/#/browse/mine/cb56f6bf-c900-43b7-b923-2e3b64b412db/bb4a3697-40ea-45e7-89f6-080b14435fdd?view=layout.view&tc.mode=local&tc.startDelta=900000&tc.endDelta=15000&tc.timeSystem=utc`

there if you take snapshot spaceforce image is not captured.

**Review by akhenry — APPROVED** [review]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A - small self contained change
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

**Review by charlesh88 — APPROVED** [review]

**Pull request merged**
