### PR TITLE
Add new glyphs for Bar Chart and Map views

### LINKED ISSUE #4193: The Map view needs an icon
New icon needed for the Map view component:

image

### PR DESCRIPTION
**Pull request by charlesh88**
Fixes #4193. Note that change here was cherry-picked from https://github.com/nasa/openmct/commits/spectral-plots-styling  4ed164c0171e1aaf4385f3c2bd28eb015330ec59

- New glyph and background classes for `icon-bar-chart` and `bg-icon-bar-chart`;
- New glyph and background classes for `icon-map` and `bg-icon-map`;

Screen Shot 2021-09-16 at 5 02 45 PM
Screen Shot 2021-09-16 at 5 06 30 PM
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes? N/A
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

### CODE REVIEW

**Review by shefalijoshi — COMMENTED** [review]
@charlesh88 The glyph sub-text says Sine Wave Generator. And the map view glyph sub-text says Telemetry Table.
Is that right?

**Comment by charlesh88** [comment]
> @charlesh88 The glyph sub-text says Sine Wave Generator. And the map view glyph sub-text says Telemetry Table.
> Is that right?

Sorry, that was an artifact of how I generated that screen shot by hacking the DOM. Please ignore the descriptive text on the folder grid items.

**Comment by davetsay** [comment]
They look great to me. Is Map View going to be used for MMGIS?

**Review by davetsay — APPROVED** [review]
LGTM

## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | N/A |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |
| Has associated issue been labelled `unverified`? | N/A |

**Pull request merged**
