### PR TITLE
Fix now marker for time system axis in timestrips and plans

### LINKED ISSUE #5628: 'Now' line in the time strip doesn't span vertically
#### Summary
The 'Now' line in the time strip should span the full height of the viewport.
Currently it only displays at the top.

#### Steps to Reproduce
1. Create a time strip
2. Change to local clock mode
3. Observe the 'Now' line.
4. It doesn't span the height of the time strip view.

#### Environment

* Open MCT Version: 2.0.6
* Deployment Type: Stable
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #5628

### Describe your changes:
Ensure the content height is correctly set for plans and time strips so that the now marker is updated to span the full height of the main view.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Review by jvigliotta — APPROVED** [review]
Looks good to me, my only suggestion would be to see if `this.$el.parentElement` would give you what you're looking for regarding parent height, but it may be nested to where that's not the case.

**Comment by ozyx** [comment]
@shefalijoshi @jvigliotta looks like this PR is bringing in an unintended version number change

**Comment by jvigliotta** [comment]
> @shefalijoshi @jvigliotta looks like this PR is bringing in an unintended version number change

Ahhhhh, gotcha. Did not realize that was unintended.

**Comment by ozyx** [comment]
> > @shefalijoshi @jvigliotta looks like this PR is bringing in an unintended version number change
> 
> 
> 
> Ahhhhh, gotcha. Did not realize that was unintended.

Looks like it's because the base was recently changed to master

**Pull request merged**
