### PR TITLE
[Plots] Gracefully handle Float32Array breaking values

### LINKED ISSUE #7137: [Plots] Very large values cause entire plot to disappear
#### Summary

When there is a very large telemetry value (in this case -7.5e+177) within the time range, the VISTA plot is blank, even though there are data points in the range. This example is for a short time range, but if you expand the time boundaries (e.g. over a week or more), you will see that the whole plot is blank. This makes it seem like data is missing, but it’s a plotting bug.

Follow up for test: https://github.com/nasa/openmct/issues/7139

#### Expected vs Current Behavior

At the very least the rest of the plot should still be plotted.

#### Steps to Reproduce

1. View a plot with values that would break a Float32Array (we have an option for this in the sine wave generator)
2. Once a value that exceeds Float32Array capabilities (Above 3.4+38, Below -3.4+38) appears in the plot, the whole thing disappears 

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available? (viewing in log mode, which is basically useless at these ranges)
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes #7137 
Related: https://github.com/NASA-AMMOS/openmct-mcws/issues/15

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes? (follow up due to deadline: https://github.com/nasa/openmct/issues/7139)
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Review by shefalijoshi — CHANGES_REQUESTED** [review]
This looks good, but found an oddity during testing.

**Comment by shefalijoshi** [comment]
Screen Shot 2023-10-12 at 12 20 44 PM

Notice that the value on the Y axis are positive > 0 but on hovering over the gap, the value shows as -ve. Seems bit odd?

**Comment by jvigliotta** [comment]
> Screen Shot 2023-10-12 at 12 20 44 PM
> Notice that the value on the Y axis are positive > 0 but on hovering over the gap, the value shows as -ve. Seems bit odd?

I agree it is odd, not really sure a way around that though, that point that's missing in that gap, is negative. if we had scaling and were able to plot it, it'd be just a straight line down.

**Review by davetsay — APPROVED** [review]
SWG game is strong

**Review by shefalijoshi — APPROVED** [review]

**Comment by ozyx** [comment]
@jvigliotta Looks like there's a [new test flake](https://app.circleci.com/pipelines/github/nasa/openmct/20178/workflows/cf9cb6e3-4ebc-47cd-9308-1759cc9264f6/jobs/84839) in Plots e2e

**Pull request merged**
