### PR TITLE
[Web Page] Allow dashes in domains

### LINKED ISSUE #1507: Web Page URL regex fails valid addresses
The current Web Page URL regex 
`"pattern": "^(ftp|https?)\\:\\/\\/\\w+(\\.\\w+)*(\\:\\d+)?(\\/\\S*)*$",`

fails this valid URL:
http://s3-us-west-1.amazonaws.com/landlords-prod/resource_prospector/index.html

and yet it should allow it. 

Do we need a regex here beyond user convenience? Are there security concerns? If not, I suggest removing the pattern statement entirely.

### PR DESCRIPTION
**Pull request by VWoeltjen**
Fixes #1507

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? N/A (changes in bundle, out of scope for unit tests)
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by larkin** [comment]
@VWoeltjen Can we just check prefix, e.g. `"^(ftp|https?)\\:\\/\\/"` and call it a day?  URL regex is deceptively time consuming.

**Comment by akhenry** [comment]
I second @larkin A valid regex for URLs is [a bit of a rabbit hole](https://mathiasbynens.be/demo/url-regex). I've been down it before.

**Comment by VWoeltjen** [comment]
Sounds good to me! Pushed up the simpler regex

**Comment by akhenry** [comment]
## Reviewer Checklist

* Changes appear to address issue? Y
* Appropriate unit tests included? N/A
* Code style and in-line documentation are appropriate? Y
* Commit messages meet standards? Y

**Pull request merged**
