### PR TITLE
Improvements to reduce repainting

### LINKED ISSUE #5247: [Performance] Inspector Repaints in Local Clock and Remote Clock Time
#### Summary
When analyzing the performance of a Display Layout, we noticed that the Inspector was being re-painted unnecessarily. We should avoid modifying or updating the Inspector unnecessarily to avoid any performance penalties associated with that repaint.

#### Expected vs Current Behavior
Expected: In Local Clock, Inspector not update or repaint unless the user interacted with an element in the object's Main view.
Current: In Local Clock, Inspector updates and repaints even on a folder with no changes.

#### Steps to Reproduce
1. Open DevTools, Enable Secondary DevTools. Enable Rendering Tab. Enable Paint Flashing.
2. Set Clock to Local Clock
3. Navigate to any object including the Root folder
Note: Inspector repaints

#### Environment
* Open MCT Version: 2.0.3
* Deployment Type: local
* OS: macOS
* Browser: Chrome 101

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?

#### Additional Information

https://user-images.githubusercontent.com/12446869/170097309-772dee09-5b64-4a52-a5d3-5a71ee642721.mov

### PR DESCRIPTION
**Pull request by charlesh88**
Closes #5247. Test instructions not yet included in the #5247 - will update there after we determine the best way to actually test these changes.

### Describe your changes:
- Removes a CSS `filter` hover effect that seemed to cause a lot of repaints; replaced with a `box-shadow` effect in buttons and simple background color changes in other elements.
- Changes usage of `transition: all` to use specific properties instead via new mixin `transition`.
- Convert `__pane-main` to use absolute positioning to isolate object view and Time Conductor from page reflowing.

### All Submissions:
* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist
* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes? N/A no functional changes.
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Review by michaelrogers — APPROVED** [review]
These changes look good to me!

**Comment by akhenry** [comment]
@michaelrogers to address any broken tests and merge.

**Comment by davetsay** [comment]
@michaelrogers to fix tests and merge

**Comment by ozyx** [comment]
From the failed e2e tests traces, it looks like the "Edit & Save" button is disappeared?

**Comment by unlikelyzero** [comment]
This one needs some additional work. We should move it back into draft

**Review by unlikelyzero — APPROVED** [review]

**Pull request merged**
