### PR TITLE
MCT 3930

### LINKED ISSUE #3930: Clocks and Timers don't apply and persist Style settings properly
Set styles in Display Layout. In this example the text color is set to a red; should be applied to all text but is only affecting the non-dynamic text:
Screen Shot 2021-06-08 at 11 09 37 AM

Save, nav away and back.
Screen Shot 2021-06-08 at 11 09 59 AM

Clock settings are persisted, but Timers don't retain anything.

### PR DESCRIPTION
**Pull request by depperm**
Fixes #3930 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [ ] Has this been smoke tested?
* [x] Testing instructions included in the associated issue?

### CODE REVIEW

**Comment by jvigliotta** [comment]
@charlesh88 How''s this look?

**Comment by akhenry** [comment]
@charlesh88 CSS change only, you happy with these changes?

**Review by charlesh88 — APPROVED** [review]
Sorry all, thought I'd reviewed and approved this more than a week ago. LGTM.

**Review by unlikelyzero — CHANGES_REQUESTED** [review]
Note: This is not applying styles to the timer element. Just the controls. @charlesh88 has a screenshot of this problem

**Comment by charlesh88** [comment]
On further review, this PR is not ready for merge yet:

image

1. The font size and style should affect the direction indicator (+) as well as the value.
2. The color is only affecting the direction indicator, but should affect the text as well, which it current isn't.

**Review by charlesh88 — CHANGES_REQUESTED** [review]
On further review, this PR is not ready for merge yet:

image

1. The font size and style should affect the direction indicator (+) as well as the value.
2. The text color is only affecting the direction indicator, but should also affect the text as well.

**Comment by depperm** [comment]
If the font size affects the direction indicator it looks a bit too big (IMO)
image

Is this ok (half size)?
image
 
Or this (70%)?
image

**Comment by unlikelyzero** [comment]
@depperm Sorry! I pulled down your changes to review and ended up pushing a partial test into your branch. I've updated your branch and should be merging the completed test into master tonight.

**Comment by depperm** [comment]
@unlikelyzero while you're here are you not seeing the color change with this MR?

**Comment by unlikelyzero** [comment]
@depperm I see it, but don't have enough experience with the intended design to approve it. I'll remove myself from the review. You should expect to see a visual test which covers this component tomorrow.

**Comment by jvigliotta** [comment]
@charlesh88 @unlikelyzero  Just wanted to bump this up.

**Comment by akhenry** [comment]
@charlesh88 to re-review

**Comment by jvigliotta** [comment]
@charlesh88 to take a look

**Review by charlesh88 — APPROVED** [review]
Reviewed locally, looks great to me. Thanks!

**Review by unlikelyzero — APPROVED** [review]

**Review by unlikelyzero — APPROVED** [review]

**Pull request merged**
