### PR TITLE
Fixes issue #2484 - When searching, user looses context of main tree

### PR DESCRIPTION
**Pull request by deeptailor**
## Fixes issue #2484

Separate search div from main tree, show search div when search value is present, else show main tree

### CODE REVIEW

**Comment by akhenry** [comment]
@deeptailor This looks great, nice simple solution, thanks!

## Reviewer Checklist

* Changes appear to address issue? Y
* Appropriate unit tests included? N/A
* Code style and in-line documentation are appropriate? Y
* Commit messages meet standards? Y

**Comment by deeptailor** [comment]
## Testing Notes

1. Expand a few tree items, and navigate to a non-root domain object (anything you have created in the past)
2. Click in the search bar (above the navigation tree)
3. Enter a few search terms
4. Click on the cancel (x) button in the search bar
5. Verify that the tree is still as you left it before you entered the search terms.

**Comment by JoelMcKinnon** [comment]
Thanks Deep. This will really help me as a new openmct user. Nothing more frustrating than being asked to test something you have little idea how to use.

**Comment by charlesh88** [comment]
Verified fixed 12-06-19.

**Comment by charlesh88** [comment]
#2484 verified fixed 12-06-19.

**Pull request merged**
