### PR TITLE
Image thumbs autoscroll resumption functionality

### LINKED ISSUE #3740: [Imagery] Cant scroll historical images when not paused
When imagery is not paused, users cant scroll the historical images strip. We should be able to scroll back even when not paused. We do something similar in telemetry tables.

### PR DESCRIPTION
**Pull request by charlesh88**
Fixes #3740. 

### Changes by @charlesh88 
- Refined look and feel of the approach;
- CSS classes now assigned at the wrapper level;
- Markup changed to allow wrapping of scroll area and button;

### CODE REVIEW

**Comment by charlesh88** [comment]
@kobe1104 There's a problem that needs to be fixed: resizing the main view area either by dragging pane edges, or resizing the browser window, causes the scroll area to "scroll" and disable auto-scrolling. 

Image thumbs resize problem #3740 2

This should be prevented.

**Comment by kobe1104** [comment]
Hi @jvigliotta @charlesh88 should we include the window resizing issue mentioned above in this issue or create a separate one for it?

**Comment by jvigliotta** [comment]
@kobe1104 I would include it in this one, it's related.

**Comment by kobe1104** [comment]
@jvigliotta Got it! Thanks.

**Comment by kobe1104** [comment]
@nikhilmandlik @unlikelyzero this is ready for review. 
@jvigliotta thanks for all the helps!
@charlesh88 Please let me know if anything is not expected. Thanks!

**Comment by kobe1104** [comment]
### Author Checklist

* [x ] Changes address original issue?
* [x ] Unit tests included and/or updated with changes?
* [x ] Command line build passes?
* [x ] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

Steps to reproduce:
1. Open an imagery that has enough images with a scroll bar showing.
2. Scroll the scroll bar to the left while it's not paused.
3. Notice the scroll bar is not scrollable.

**Review by kobe1104 — APPROVED** [review]
@akhenry I've reviewed the code and made a tiny change of removing some variables I created, but never used.

**Pull request merged**
