### PR TITLE
Handle empty namespaces in import

### LINKED ISSUE #7617: Import from JSON action does not work in anything other than the default namespace
#### Summary
Marking as blocker as it blocks an important downstream workflow for viper ops, with no workaround.

#### Steps to Reproduce
1. Configure Open MCT for multiple couch databases, [per the instructions on this ticket](https://github.com/nasa/openmct/issues/7359#issuecomment-1909750435)
2. Export a folder from the default namespace to JSON
3. Import the resulting file into the second database
4. Observe that a missing object appears in the second database
5. Refresh the browser, and observe that the objects initially appear in the second database
6. Click on one of the objects in the second database
7. Observe that Open MCT reports the object as missing.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #7617 

### Describe your changes:

When importing a JSON dump that came from a setup without a namespace set, the regex we use in the ImportJsonAction was setting the key to `namespace:key`, instead of properly separating the two. Now we detect corrupted keys, and repair them during the import.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

**Comment by scottbell** [comment]
This is pretty tricky to write an e2e test because we need to test with a namespace'd couchdb server, which I don't think we have.

**Review by ozyx — COMMENTED** [review]
Looks good! Just needs some kind of test

**Comment by akhenry** [comment]
Tested locally and it looks good. Filed a followup for the test - https://github.com/nasa/openmct/issues/7621

**Comment by scottbell** [comment]
> Tested locally and it looks good. Filed a followup for the test - #7621

Added a test to this PR FWIW

**Review by akhenry — APPROVED** [review]

**Comment by akhenry** [comment]
> > Tested locally and it looks good. Filed a followup for the test - #7621
> 
> @akhenry Added a test to this PR FWIW

Then I'll go ahead and close the followup :) Thanks!

**Pull request merged**
