### PR TITLE
[Notebook] Create Snapshot directly from any frame in a layout #3300

### PR DESCRIPTION
**Pull request by nikhilmandlik**
### TODOs:
- snapshot options should include into three dot menu.

### Notes:
- based of branch `three-dot-menu-proto`

### Author Checklist:
Check | Passed
-- | --
Changes address original issue? | Y
Unit tests included and/or updated with changes? | N/A
Command line build passes? | Y
Changes have been smoke-tested? | Y

### Screenshots:
Screen Shot 2020-10-15 at 11 52 09 AM

Screen Shot 2020-10-15 at 11 52 25 AM

### CODE REVIEW

**Comment by deeptailor** [comment]
@nikhilmandlik - Can we update this PR and change the base to three-dot-menu-proto

**Comment by deeptailor** [comment]
@nikhilmandlik - resolve conflicts and ill merge it

**Comment by jvigliotta** [comment]
@nikhilmandlik still relevant?

**Comment by nikhilmandlik** [comment]
> @nikhilmandlik still relevant?

yes but gonna close this and create new one, rebase ll be more work than implementing new one 😝

**Pull request closed without merging**
