### PR TITLE
d3 implementation of progress pie chart

### LINKED ISSUE #7377: Allow compact view for time list for Situational Awareness dashboards
**Describe the solution you'd like**
As part of the situational awareness work, we need a compact view of the time list view so it can be included in a dashboard.
This compact view will have minimum needed information and widgets for easier visualization of activities.

The design for compact view can be found on confluence page "Situational Awareness Needs and Design"

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #7377 

### Describe your changes:
Use the d3.arc API to draw pie progress
-driveby to fix some of the flaky percy tests
-driveby to add a mission percy test

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Is this a breaking change to be called out in the release notes?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?

### CODE REVIEW

**Review by charlesh88 — CHANGES_REQUESTED** [review]
The pie isn't displaying properly at 0% (yellow arrow) and 100% (orange arrow).

Screenshot 2024-02-08 at 1 47 38 PM

- At 0%, it's displaying a very thin sliver of progress, but shouldn't.
- At 100%, it's displaying a very thin sliver of "incompleteness", but shouldn't.

This may be due to not "rounding" things properly; I had to deal with this in the previous code when progress was near 100%: if the amount of remaining update (in terms of percent) was less than the percent-update-per-tick, my version was always stalling and never getting to 100%. I added a test to check if the remaining percent < the percent-update-per-tick, and if so, directly set the percentage to 100%. 

Maybe there's a related thing near 0?

**Comment by shefalijoshi** [comment]
> The pie isn't displaying properly at 0% (yellow arrow) and 100% (orange arrow).
> 
> Screenshot 2024-02-08 at 1 47 38 PM
> 
>     * At 0%, it's displaying a very thin sliver of progress, but shouldn't.
> 
>     * At 100%, it's displaying a very thin sliver of "incompleteness", but shouldn't.
> 
> 
> This may be due to not "rounding" things properly; I had to deal with this in the previous code when progress was near 100%: if the amount of remaining update (in terms of percent) was less than the percent-update-per-tick, my version was always stalling and never getting to 100%. I added a test to check if the remaining percent < the percent-update-per-tick, and if so, directly set the percentage to 100%.
> 
> Maybe there's a related thing near 0?

0% works now:

https://github.com/nasa/openmct/assets/5247066/64e67cb0-54cb-4009-98d8-1d6c19402616

and so does 100%:

https://github.com/nasa/openmct/assets/5247066/273405cc-b814-4cff-bec6-442143b51327

**Review by charlesh88 — APPROVED** [review]
0 and 100% pie issues addressed, looks great!

**Comment by unlikelyzero** [comment]
let's make sure we have coverage

**Review by unlikelyzero — CHANGES_REQUESTED** [review]
Need the simplest visual test

**Review by ozyx — APPROVED** [review]
LGTM! Great job on the tests

**Review by unlikelyzero — APPROVED** [review]

**Pull request merged**
