### PR TITLE
Add Independent Time Conductor to ImageView

### LINKED ISSUE #6434: Image view should support showing more images than the conductor bounds
**Is your feature request related to a problem? Please describe.**
Users would prefer if Imagery in the thumb strip persisted and was not removed by the Time Conductor bounds, while using a designated "now" context (local clock, remote clock). This supports the usage scenario of wanting to globally see plotted data for around 15 minutes, but imagery for much longer.

**Describe the solution you'd like**
1. A toggle switch for Imagery views, per view and enabled by default, that makes that view ignore the TC real-time bounds. "Now" would still be defined by the TC.
Discuss if Fixed Timespan mode would or would not pay attention to this setting.
1. Independent Time Conductor is another possibility, but that UX is more cumbersome to deal with for this use case; option 1 above would be preferred.

**Additional context**
For images it's good enough to just enable the independent time conductor for now.

### PR DESCRIPTION
**Pull request by scottbell**
Closes #6434 

### Describe your changes:
Adds independent time conductor to the `ImageView`. Adds time context to `TelemetryCollection`.
I also added it to `DisplayLayout`, though this can be backed out if we're worried about risk. It appears to work though!

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by scottbell** [comment]
@charlesh88 If you'd like to take a crack at styling, here's the PR 😀

**Comment by charlesh88** [comment]
Looking good, going in to do some needed finessing on the ITC.

### @charlesh88 TODOS
- [ ] Hide ITC when its view's frame is hidden in a layout.
- [ ] Make toggle switch, icon and buttons smaller.
- [ ] Better vertical alignment of elements.

**Review by charlesh88 — CHANGES_REQUESTED** [review]
Functionally this LGTM. 

That said, inclusion of the ITC as it is currently takes up a great deal of incremental space, and would have a significant negative impact on existing displays as it is. This needs a bunch of refinement in the CSS department (@charlesh88 to do) if we need this feature quickly in the short term; ideally if not, then this work should be brought over and combined with the WIP in branch `time-conductor-4975` which was shelved last year and solves for the space problem cited earlier here.

**Comment by scottbell** [comment]
I wonder if the underlying [TelemetryCollection](https://github.com/nasa/openmct/pull/6496/files#diff-75d0c62825881ea93d0c229e2df22f17dd851c865be5f3c016fa0609f15a5024R50) work can go in, and just exclude the rather [small change](https://github.com/nasa/openmct/pull/6496/files#diff-8fcb8316d14608379d1641afa918782dd62db9c6515f5efeac792f21d40edfebR34) to enable the time conductor on the various views. The[ e2e tests](https://github.com/nasa/openmct/pull/6496/files#diff-c2cd5f830eacccee9cd662d40a4a93215a5bde68c18a556c1e5a616987c7a74fR191) will probably need to remain in limbo.

**Comment by scottbell** [comment]
Closing this for the time being and making a new one to add backend work.

**Comment by akhenry** [comment]
@scottbell  Let's revive this changeset and rebase it on the new time conductor branch.

**Pull request closed without merging**
