### PR TITLE
Plot label height adjustment.

### PR DESCRIPTION
**Pull request by nikhilmandlik**
Screen Shot 2019-10-21 at 9 53 01 AM

### CODE REVIEW

**Comment by deeptailor** [comment]
@charlesh88 - please review and advice wether this is a good fix for plot labels

**Comment by charlesh88** [comment]
### Reviewer Checklist
1. Changes appear to address issue? Y
1. Appropriate unit tests included? Y
1. Code style and in-line documentation are appropriate? Y
1. Commit messages meet standards? Y

LGTM! Ship it.

**Comment by nikhilmandlik** [comment]
**Testathon:** Overlapping of X axis label with x axis tick values.

**Comment by charlesh88** [comment]
Testathon 12-06-19: verified fixed.

**Pull request merged**
