### PR TITLE
[Optimization] Reduce D3 dependency size

### PR DESCRIPTION
**Pull request by slinto**
#1224 

Size of D3 dependency was reduced from 211KB to 78KB. Not as much as I think, because d3-scale dependency need a another 8 d3 depencencies.

### Author Checklist

Changes address original issue? Y
Unit tests included and/or updated with changes? Y
Command line build passes? Y
Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by akhenry** [comment]
@slinto Thanks very much for doing this. 211KB > 78KB is not insignificant, so I appreciate the effort. Before I can merge this, would you mind [completing a Contributor License Agreement](https://nasa.github.io/openmct/contributing/) and sending it to the email address at the bottom of that document.

Thanks again

**Comment by slinto** [comment]
@akhenry ok, done. I hope to see you again in some next issue :)

**Comment by akhenry** [comment]
## Reviewer Checklist

* Changes appear to address issue? Y
* Appropriate unit tests included? N/A - dependencies
* Code style and in-line documentation are appropriate? N/A - dependencies only
* Commit messages meet standards? Y

**Comment by akhenry** [comment]
@slinto Thanks again!

**Pull request merged**
