### PR TITLE
Mct3979

### LINKED ISSUE #3979: Copyright updates for Open MCT template (and other files)
Copyright needs to be updated to include 2021 for some files.

### PR DESCRIPTION
**Pull request by depperm**
Fixes #3979 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

### CODE REVIEW

**Review by shefalijoshi — DISMISSED** [review]
### Reviewer Checklist

* [x] Changes appear to address issue?
* [ ] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled `bug`? (only applicable if this PR is for a bug fix)
* [x] List of Acceptance Tests Performed.

**Comment by depperm** [comment]
@shefalijoshi 

> @depperm please resolve conflicts. Thank you!

there is nothing to resolve. If you checkout my branch and merge master there is nothing to resolve. Where in the files are the conflicts

**Comment by jvigliotta** [comment]
@shefalijoshi any update on this? Wondering why there are conflicts...

**Comment by akhenry** [comment]
@depperm The PR checks (at the bottom of this PR) are showing file conflicts.

**Comment by depperm** [comment]
@akhenry 

> @depperm The PR checks (at the bottom of this PR) are showing file conflicts.

I'm aware, but looking at the code I pushed doesn't show any conflicts. Merging master into my branch says 'Already up to date'. I'm unaware of what the conflicts are or how to resolve them.

**Comment by jvigliotta** [comment]
@depperm Yeah, that's pretty odd, but I do know that we recently removed some of these files as we've updated them from legacy code. For instance, the UTCTimeFormat.js has been removed and the buildInfo/plugin.js has been removed. Maybe just remove any of the files in the conflict list and try again?

**Comment by unlikelyzero** [comment]
@depperm do you mind doing an interactive rebase to pull in all of the changes in `master` ?

**Comment by depperm** [comment]
@unlikelyzero I attempted to do a rebase (I've never done one before) but there still look to be issues. There is a related issue: https://github.com/nasa/openmct/issues/4532 where I sort of attempted to start a discussion on wether or not updating the copyright is necessary. If it isn't this PR can be closed. Any input?

**Comment by unlikelyzero** [comment]
hey @depperm , this might just be easier to restart with a clean slate. I think the PR commit history might be too convoluted. If you think you could get this done before next Friday (01/14/22), let us know and we'll merge review it ASAP. Otherwise we might add this to our sprint board to tackle in 1.8.4 .

**Pull request closed without merging**
