### PR TITLE
UI updates to Y axis

### LINKED ISSUE #5792: Visual treatment of multiple Y axes
**Is your feature request related to a problem? Please describe.**
Based on the design here: https://trunk.arc.nasa.gov/confluence/display/VIPERMS/Multiple+Y-Axes+for+plots
Allow showing/hiding Y axes, identifying Y axes on hover etc.

**Describe the solution you'd like**

- Layout changes to the yaxis to include color swatches and visibility toggle
- Show/Hide plots for a given y-axis

**Describe alternatives you've considered**
N/A

**Additional context**
This is step five of the Multiple Y axes implementation for Open MCT plots.

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #5792 

### Describe your changes:

**Known Issues:**
Adding/Removing series to different Y axis buckets requires navigating away and back to the overlay plot.

**Changes:**
- Move the Y axis name to the bottom of the y-axis area
- Move the gear icon below the name of the y-axis
- Add a visibility toggle to the y-axis
- Add color swatches to indicate which series are part of the y axis (no hover interaction is done for MVP)

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by shefalijoshi** [comment]
Testing Notes:
Create an overlay plot
Add multiple telemetry endpoints to the overlay plot
In edit mode, scroll to the Elements Pool and drag/drop series to different Y axis *Note: you may need to navigate away from the plot to see the changes*
Play with it - have fun!

**Comment by rukmini-bose** [comment]
UI Improvements:

**Review by rukmini-bose — CHANGES_REQUESTED** [review]
Review Comments: 
This looks great! Super duper impressive. Tested on regular overlay plots, as well as checked how it looks in a stacked plot. 

Couple of things: 

- [x] 1. The visibility toggle button seems to be faulty. Check out the video– SWG C (purple plot) seems to be re-rendering even after we hide its respective Y Axis. 

https://user-images.githubusercontent.com/48999852/213054367-0d5b2cb1-48fc-482a-9a50-6c446f360630.mov

- [x] 2. Noticing that the Y Axis 2 (furthest from the left) is always cut off in the canvas. Can we fix this? 

Screen Shot 2023-01-17 at 10 31 16 AM

- [x] 3. Something odd is happening over here with Y Axis 1 and 2. I think that the two axes are being overlapped over each other. 

Screen Shot 2023-01-17 at 4 50 07 PM

- [x] 4. For Y-Axis 3, it would be nice if we could have the ticks closer to the canvas rather than the label. That way, there is less of a space between the plot and ticks, so it is easier for users to visualize the hash lines to the ticks. Plus, it'll be more consistent with the other axes, who have the ticks next to plot. 

Screen Shot 2023-01-17 at 5 27 17 PM

- [ ] 5. Dragging and dropping elements between axes in the elements pool is difficult and unintuitive at times– specifically when you are trying to drop a new element into an axis that is already populated by another axis. We need to work on making the highlights that appear on drag more clear. **UPDATE:** After talking with @ozyx , we have decided to create a separate and new element for objects in the elements pool for multiple y-axes. This change will remove the grippy element, which is causing the issues I encountered when dragging elements between axes. 

- [ ] 6. Add instructions into the elements pool to make it clearer to users how to interact with it.

**Review by rukmini-bose — CHANGES_REQUESTED** [review]
This all looks super amazing. Everything looks great one the regular overlay plot object. 

My only observation now is that the axes do not line up properly when there are multiple y axes plots being used in a stacked plot. 
We would need to calculate which plot within the stacked plot has the maximum width, and make sure that the rest of the plots within the stacked plot take on that width as well. That'll ensure that the plots (and their x-axis) line up properly, which is important in a stacked plot.  

Screen Shot 2023-01-20 at 9 45 11 AM

**Review by rukmini-bose — APPROVED** [review]
Looks good! There's a bug with how multiple y axes looks in stacked plots, but I'll file a bug for it. Approving now. 🥳

**Pull request merged**
