### PR TITLE
[Representation] Change ng-model to mct-model

### PR DESCRIPTION
**Pull request by VWoeltjen**
For `mct-include` and `mct-representation`, use `mct-model` instead of `ng-model` as a means to pass in mutable data. 

For compatibility, `ng-model` is still supported; usages will be removed starting in #315 and ending with #366.

Note that this branch contains changed from #365 and should not be merged until that issue has been resolved.

Addresses #313.
### Author Checklist
1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Expect to pass code review? Y

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Cherry-picked increase in Require's timeout (in test script) to pass testing on CircleCI. Do not expect later merge conflicts due to this (merging the two branches is resolved without conflict locally) or, if they are present, expect resolution to be trivial.

**Comment by larkin** [comment]
@VWoeltjen This PR has not been tagged with a sprint and seems to have fallen off the radar.  I seem to remember that we had merged these changes already (refactored in another pull request?), but maybe I am remembering incorrectly?

Do you know if this still requires a review & integrate?

**Comment by VWoeltjen** [comment]
Thanks for resurrecting - status is a little muddy on this one and needs to be clarified.

This depends on #365, which is also unmerged, and still has some outstanding review feedback items. Have not worked on addressing these since performance gains of #365 are marginal, and improving support for non-Angular UI components in #463 may provide us with better solutions that make #365 obsolete.

**Comment by larkin** [comment]
Closing as "not going to imple,ent"

**Pull request closed without merging**
