### PR TITLE
Fix menu style in Snow theme

### LINKED ISSUE #5556: Menus in Snow theme have no border
#### Summary
In snow theme the menus - create, 3-dot, context - are missing some border and drop shadow styling

#### Expected vs Current Behavior
Border and drop shadow

#### Steps to Reproduce
1. open browser console
2. use `openmct.install(openmct.plugins.Snow())` and `openmct.install(openmct.plugins.Espresso())` to toggle themes
3. compare menus (create, context, 3-dot) in Snow and Espresso themes

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by charlesh88**
Closes #5556. 
- Fixed missing drop shadow in Snow theme menus.
- Found and fixed a problem in Snow theme with icon colors of hovered menu items in the Snow theme only.

Screen Shot 2022-07-25 at 2 38 41 PM

Screen Shot 2022-07-25 at 3 10 40 PM

### Describe your changes:

CSS mixin fixed.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes? **N/A**
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@charlesh88 can we make this into a visual testcase before merge so that you can get an exhaustive preview of how this will look across the app?

**Review by davetsay — APPROVED** [review]
LGTM and thanks for fixing so quickly

**Comment by unlikelyzero** [comment]
@charlesh88 let me know when you're available and we can review these changes in our new visual tests

**Review by unlikelyzero — CHANGES_REQUESTED** [review]
WAIT

**Review by unlikelyzero — APPROVED** [review]
Tests look good

**Pull request merged**
