### PR TITLE
[Time Conductor] Remove previous time conductor. Fixes #1234

### LINKED ISSUE #1234: [Time Conductor] Remove previous time conductor
The v1 time conductor is still present in the source tree. It should be removed after initial merge of V2.

### PR DESCRIPTION
**Pull request by akhenry**
Removes the previous timeline, and renames the new timeline.

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by larkin** [comment]
@akhenry some conflicts here from other merges, can you tidy this up for merge?

Also, for migration purposes, what are the bundle changes, e.g. if I was previously depending on "platform/features/conductor-v2/conductor" and "platform/features/conductor-v2/compatibility", what do I change those to?

**Comment by akhenry** [comment]
@larkin sure thing.  `platform/features/conductor-v2/conductor` would now be `platform/features/conductor/conductor`, though in the interests of avoiding repetition here I'm inclined to call it something else, like `platform/features/conductor/core`

**Comment by akhenry** [comment]
Rebased over master. Note that to reference this plugin now the paths are:
```javascript
    'platform/features/conductor/core',
    'platform/features/conductor/compatibility',
    'platform/features/conductor/utcTimeSystem'
```

**Comment by larkin** [comment]
# Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A (clean up)
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
