### PR TITLE
[Navigation] Prevent navigation to orphan objects

### PR DESCRIPTION
**Pull request by VWoeltjen**
At start-up, listen for changes to navigation and to mutation events, to detect situations where an orphan object (an object that does not exist in its parent's composition) has been navigated-to outside of edit mode. When this occurs, navigate up to its contextual parent.

This is particularly useful when a persistence failure has caused a created object not to be added to its parent container. #765 

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by akhenry** [comment]
This looks like it might be really useful, but I wonder if we should instead be focusing on better handling of persistence failures? Hitting cancel from that dialog should discard the orphaned object, and navigate you away without the need for a generic handler.

**Comment by VWoeltjen** [comment]
One of the challenges with that approach is that the orphaned object actually saved just fine - it's the modifications to the parent that failed to save.

That said, could certainly use the same logic here and apply it only after Discard was chosen. This would reduce the risk of unintended consequences from the more general approach.

**Comment by akhenry** [comment]
@VWoeltjen Agreed, it's a bit of a challenge. I prefer what you've suggested above, but I'll leave it up to you. If you want to leave it as-is let me know and I'll complete the review.

**Comment by VWoeltjen** [comment]
I'll go ahead and make those changes, I like the risk reduction

**Comment by VWoeltjen** [comment]
Looked into this a bit:

* Handling this immediately after user chooses Discard is ineffective; the navigation change hasn't occurred yet
* Handling this from the the SaveAction (or EditorCapability.save) is not practical; choosing Discard is treated as resolving the failure, so it just looks like all parts of the transaction succeeded. Treating Discard as a failure would make sense, but could have unintended consequences. (Per #408, we also want to convey persistence failures differently, which would change our solution here.)

I've reverted back to the original form of this PR. My thinking is that we should use this for now (to resolve #765) and file a followup issue to relocate this behavior after #408 has been solved. Thoughts?

**Comment by akhenry** [comment]
Fair enough, let's stick with this solution in the interim.

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
