### PR TITLE
[Date Picker] Highlight Selected Date

### PR DESCRIPTION
**Pull request by jvigliotta**
Added CSS to target "selected" class on date picker item.

closes: #3677

### Author Checklist
Check | Passed
-- | --
Changes address original issue? | Y
Unit tests included and/or updated with changes? | N/A
Command line build passes? | Y
Changes have been smoke-tested? | Y
Testing instructions included? | Y

### CODE REVIEW

**Comment by deeptailor** [comment]
@jvigliotta are we waiting on @charlesh88 to take a look?

**Comment by jvigliotta** [comment]
> @jvigliotta are we waiting on @charlesh88 to take a look?

Yessir!

**Comment by deeptailor** [comment]
@charlesh88 - Could we merge this asap? Need it for VISTA

**Review by charlesh88 — APPROVED** [review]
LGTM!

**Pull request merged**
