### PR TITLE
Make notification icon clickable

### LINKED ISSUE #1239: [Notifications] You cannot click on the notifications icon
Imgur

You have to click on the label in order to view the notifications, but this is very confusing because by default the label is hidden. I find myself hovering on the notifications icon and then trying to click on it to bring the notifications up, while the label expands. Nothing other than the icon not responding suggests that I should click on the label instead.

### PR DESCRIPTION
**Pull request by Brantron**
### Changes address original issue?

This addresses and closes #1239
### Unit tests included and/or updated with changes?

changes are out of scope for unit testing
### Command line build passes?

yes
### Changes have been smoke-tested?

yes

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Thanks for the PR! Changes look good to me; @charlesh88, since this is a markup change, can you take a look as well?

Just a couple of things needed before we can merge:

* First, a [contributor license agreement](https://nasa.github.io/openmct/contributing/) (instructions are linked)
* Second, an [author checklist](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md#author-checklist)
  * One of those checklist items is commit message standards; for our traceability purposes, could you amend that commit with an additional line like "Fixes #1239"?
  * For the question about unit tests, "changes are out of scope for unit testing" is fine

Thanks!

**Comment by Brantron** [comment]
Thanks! I've emailed it in and rebased my commit.

**Comment by Brantron** [comment]
@VWoeltjen anything else needed?

**Comment by charlesh88** [comment]
@Brantron Think this looks good, awesome work! Thanks.

**Comment by charlesh88** [comment]
Reassigning to Andrew for merge.

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A markup changes
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Comment by akhenry** [comment]
Merged. Thanks @Brantron!

**Pull request merged**
