### PR TITLE
[DateTime Field] Disabled autocorrect and spellcheck for datetime fields

### PR DESCRIPTION
**Pull request by tobiasbrown**
Added `autocorrect` and `spellcheck` attributes to the datetime-field template.  Addresses #1682.

## Author Checklist
1. Changes address original issue? Yes
2. Unit tests included and/or updated with changes? No
3. Command line build passes? Yes
4. Changes have been smoke-tested? Yes

### CODE REVIEW

**Comment by VWoeltjen** [comment]
@charlesh88 - since this is a markup change, mind giving it a quick review?

**Comment by larkin** [comment]
@VWoeltjen @charlesh88 this should be good to merge as is.

**Comment by akhenry** [comment]
Obeying the squirrel and shipping.

## Reviewer Checklist

* Changes appear to address issue? Y
* Appropriate unit tests included? N/A - Markup changes that do not justify additional unit tests
* Code style and in-line documentation are appropriate? Y
* Commit messages meet standards? Y

**Comment by akhenry** [comment]
@tobiasbrown Changes look good. Thanks for the contribution!

**Pull request merged**
