### PR TITLE
Fix main object view

### LINKED ISSUE #4623: Condition Widgets not displaying properly
#### Summary
Condition Widgets are not displaying properly in the main view:
Screen Shot 2021-12-21 at 11 34 11 AM

#### Expected vs Current Behavior
Condition Widgets should display properly in the main view:
Screen Shot 2021-12-21 at 2 57 25 PM

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug?

### PR DESCRIPTION
**Pull request by charlesh88**
Fixes #4623. See issue for change notes and testing instructions.
- New `c-object-view` class;
- Removed CSS class special-casing in ObjectView.vue;
- Removed unused `l-shell__main-object-view` class;
- Fixed CSS selector for Condition Widget display in main view;

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes? N/A
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@charlesh88 @akhenry @shefalijoshi let me add a visual test for this one

**Comment by unlikelyzero** [comment]
@charlesh88 @shefalijoshi can you merge this test in and then add the `pr:visual` label?

**Comment by unlikelyzero** [comment]
@charlesh88 @shefalijoshi @akhenry I added a visual test for this component on master. I've run the visual checks against this PR (you can see them with the 'Details' Link under checks OR see them here:

https://percy.io/b2e34b17/openmct/builds/14721395/changed/832250769?browser=edge&browser_ids=18%2C19%2C20%2C21&subcategories=approved&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280

**Review by shefalijoshi — APPROVED** [review]
### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled `bug`? (only applicable if this PR is for a bug fix)
* [ ] List of Acceptance Tests Performed.

**Pull request merged**
