### PR TITLE
Allow for ObjectProvider to specify a limitEvaluator

### PR DESCRIPTION
**Pull request by thesamprice**
Inside my object provider I was trying to specify a telemetry Limit,
Couldn't figure out how to do this unless I was allowed to override the telemetryLimiter

```

      var objectProvider = {
       get: function (identifier) {

        var GetObj = function(identifier){
            if (identifier.key === 'spacecraft') {
                return {
                    identifier: identifier,
                    name: TLM_DB_JSON.name,
                    type: 'folder',
                    location: 'ROOT',
                    children: TLM_DB_JSON.children
                };
            }
            else{
                var measurement = FLAT_DB[identifier.key];
                measurement['identifier'] = identifier;

                if (measurement.type == 'folder')
                {

                }
                else{
                    measurement.telemetry = {
                        values: measurement.values
                    }

                    if(measurement.properites.limits)
                    {
                        measurement.limitEvaluator = {
                            evaluate:function (a){
                                if(FLAT_DB[a.id].properites.limits.rh && a.value >= FLAT_DB[a.id].properites.limits.rh)
                                {
                                    return {cssClass: "s-limit-upr s-limit-red",
                                    name: "Red High"}
                                }
                                if(FLAT_DB[a.id].properites.limits.rl && a.value <= FLAT_DB[a.id].properites.limits.rl)
                                {
                                    return {cssClass: "s-limit-lwr s-limit-red",
                                    name: "Red Low"}
                                }
                                if(FLAT_DB[a.id].properites.limits.yh && a.value >= FLAT_DB[a.id].properites.limits.yh)
                                {
                                    return {cssClass: "s-limit-upr s-limit-yellow",
                                    name: "Yellow High"}
                                }
                                if(FLAT_DB[a.id].properites.limits.yl && a.value <= FLAT_DB[a.id].properites.limits.yl)
                                {
                                    return {cssClass: "s-limit-lwr s-limit-yellow",
                                    name: "Yellow Low"}
                                }

                            }}
    
                    }
    
                }

                return measurement;
            }
        }
        var p = new Promise(function(res,rej){
            var obj = GetObj(identifier)
            res(obj);
        });
        return p
    }

  };
  openmct.objects.addProvider('example.taxonomy', objectProvider);

```

Also probably need pointers on how to do a unit test

Had to do the function test as plots were not seeing the evaluate function, but fixed displays were...

### CODE REVIEW

**Comment by larkin** [comment]
@thesamprice I understand limit evaluators are a hole in the current API.  We're working on a set of changes to the telemetry API to enable custom limit evaluators, but that means we won't take this change set.  I appreciate you taking the time to put this together, and will let you know when the limit changes have landed.

**Comment by thesamprice** [comment]
Ok in the meantime im going to do this in my code as a workaround.

```
openmct.telemetry.limitEvaluator =  function () {
    if( arguments[0].limitEvaluator && typeof arguments[0].limitEvaluator.evaluate  === 'function')
    {
        return arguments[0].limitEvaluator;
    }
    else{
        return this.legacyProvider.limitEvaluator.apply(this.legacyProvider, arguments);

    }
}
```

**Comment by larkin** [comment]
@thesamprice that does seem workable.  If you want, you can also use a legacy limit evaluator, which will give you a deprecation warning when we release the new API.  That looks like:

```javascript
function MyLimitEvaluator(domainObject) {
  return {
    evaluate: function (datum, key) {
      // your logic here.
    }
  };
}

MyLimitEvaluator.appliesTo = function (domainObject) {
  // return true for objects you want to apply to.
};

openmct.legacyExtension('capabilities', {
    {
        "key": "limit",
        "implementation": MyLimitEvaluator
    }
});
```

**Comment by larkin** [comment]
@thesamprice limit evaluators are now supported (in beta) in the public API.  For an example, look at the generator plugin: https://github.com/nasa/openmct/blob/master/example/generator/SinewaveLimitProvider.js

This provider is registered with `openmct.telemetry.addProvider(new SinewaveLimitProvider());`.

**Pull request closed without merging**
