### PR TITLE
 #885 added command line option --directory -D to specify base directory

### PR DESCRIPTION
**Pull request by akhenry**
### Author Checklist

1. Changes address original issue? __Y__
2. Unit tests included and/or updated with changes? __N/A__ Change to app.js - doesn't warrant tests
3. Command line build passes? __Y__
4. Changes have been smoke-tested? __Y__

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Changes look good but to resolve #885 without regression think we also need:

1. To add `--directory dist` to the Procfile
2. To make sure CSS and other resources needed for guided tour get served (e.g. by copying them to dist in the gulp build)

An alternate approach to 2 would be to serve from multiple directories (`dist` and `.`) since we know that latter has the resources needed for the tour. If `express.static` hits a file-not-found, it will let the next middleware handle the request, e.g.:

```
app.use(express.static('dist'));
app.use(express.static('.'));
```

...serves files from `dist` if they're there, or looks in `.` if they're not.

**Comment by akhenry** [comment]
I don't believe there's a regression in master here. I implemented the procfile change in the live_demo branch. That said, there should be no harm in implementing it in this branch, so I'll go ahead and do that.

I also added the `demo` directory to the `static` paths in gulpfile.js in the live_demo branch. This resolved the missing css file in the tour. I did it here because the `demo` directory does not exist in the master branch. For this reason I'm inclined to leave this change in the live_demo branch only.

**Comment by VWoeltjen** [comment]
Ah! Got it, I just wasn't seeing the whole picture.

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Comment by akhenry** [comment]
whoa Nelly! I was going to make the procfile change in this branch :) No matter.

**Pull request merged**
