### PR TITLE
4386 - In time conductor history, show them on hover if only milliseconds have changed

### PR DESCRIPTION
**Pull request by mariuszr**
Addresses #4386 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

### CODE REVIEW

**Comment by shefalijoshi** [comment]
@akhenry Please take a look. Thanks!

**Comment by akhenry** [comment]
It looks to me as though this PR would restore milliseconds everywhere, and that what we want is something slightly more nuanced than that. 

Our users have specifically requested that milliseconds not be shown in the time conductor history because they don't care about it. We discovered in testing though that this lead to apparent duplicate entries in the conductor history when you have two historical entries that only differ by milliseconds.

I believe that the original intent of the linked issue was to _only show milliseconds when there is a duplicate entry with the same timestamp_. In retrospect, this requires the code to "look ahead" when rendering the entries to know whether there is a "duplicate" entry coming up, which is not great.

We also show the precise start and end times on hover in the `title` attribute. Perhaps the easiest way to fix this is just add milliseconds there? These sorts of duplicates _shouldn't_ happen very often, and if they do the user can just hover on the entry and look at the precise start and end times.

**Comment by mariuszr** [comment]
Thank you @akhenry for giving me additional clarification on the issue. I got your point and seems like I made an overinterpretation of the expectation :)

I've done changes in the description data formats (tooltip) to present the milliseconds there. Please check [commit](https://github.com/mariuszr/openmct/commit/87969f1a80b355ca80bd7a88be842cb1cb48be6) on the branch [openmct-4386-tooltip](https://github.com/mariuszr/openmct/tree/openmct-4386-tooltip) and let  me know your thoughts.

**Review by akhenry — APPROVED** [review]

**Comment by akhenry** [comment]
@mariuszr Thanks so much for your help with this, I've gone ahead and merged it.

**Pull request merged**
