### PR TITLE
[Plot] make plot zoom in/out consistent (#3286)

### PR DESCRIPTION
**Pull request by johnriedel**
Author Checklist:
Changes address original issue? Yes
Unit tests included and/or updated with changes? No
Command line build passes? Yes
Changes have been smoke-tested? Yes
Testing instructions included? Yes

To test:
1. Add a sine wave generator to the workspace
2. zoom in once
3. zoom out once
4. The expected zoom position of both X and Y axes should be that of the original zoom position prior to step 2 of this test.

### CODE REVIEW

**Comment by jvigliotta** [comment]
@charlesh88 is this still relevant?

**Comment by akhenry** [comment]
Addresses #3286

**Comment by akhenry** [comment]
@charlesh88 Some feedback from you needed on the [linked issue](https://github.com/nasa/openmct/issues/3286)

**Comment by akhenry** [comment]
@nikhilmandlik to take a look

**Comment by nikhilmandlik** [comment]
hi @johnriedel now plot code has been refactor we can start fixing these.
Please refer to file `openmct/src/plugins/plot/MctPlot.vue` can move changes here.

**Comment by jvigliotta** [comment]
HI @johnriedel we're going to close this for now and put it into our development pipeline. Thank you for work on this!

**Pull request closed without merging**
