### PR TITLE
[Edit Mode] #628 Remove edit related concerns from Create Action

### PR DESCRIPTION
**Pull request by akhenry**
Addresses #628 

### Changes
* Removed duplicated logic from CreateAction
* Simplified dependencies of CreateAction and CreateActionProvider
* Replaced disabled tests
* Addressed possible regression introduced by these changes in the EditActionPolicy

@VWoeltjen I'd like to discuss a couple of points before I finalize this issue
1. I have not removed all edit concerns from the CreateAction. I'd like to consider whether the CreateAction should be in browse at all. EditAction, RemoveAction, etc. are in the edit bundle. While I'm sure it's possible to remove edit concerns from the create action with some creative refactoring, I'm not sure it's worth the effort when the CreateAction is arguably in the wrong place anyway. Thoughts?
2. The following code in the EditAction Policy sucks, I know -
``` javascript
                 if (view.editable === true ||
                    (view.key === 'plot' && type.getKey() === 'telemetry.panel') ||
                    (view.key === 'table' && type.getKey() === 'table') ||
                    (view.key === 'rt-table' && type.getKey() === 'rttable')
                    ) {
```
When it was just the plot it was a bit annoying, but now it's just obnoxious. The problem here is that the view 'editable' property is a binary, and in some cases it needs to be more context sensitive. Certain views are editable, but only for certain object types, eg. table views should be editable for the table object types, but not for other object types.

It's almost as though we need a new action policy category that's sensitive to the current view?

### CODE REVIEW

**Comment by VWoeltjen** [comment]
>  1. I have not removed all edit concerns from the CreateAction. I'd like to consider whether the CreateAction should be in browse at all. EditAction, RemoveAction, etc. are in the edit bundle. While I'm sure it's possible to remove edit concerns from the create action with some creative refactoring, I'm not sure it's worth the effort when the CreateAction is arguably in the wrong place anyway. Thoughts?

Moving this to into Edit makes sense to me. Post-NEM, Create and Edit are much more closely related. 

Architecturally, it would be quite nice if Create had fewer dependencies, and the transition to Edit mode was handled by externally from the basic Create action. To your point, though, the benefit doesn't really justify the effort (and it's debatable whether or not this is really "better" - there's a lot of clarity in invoking edit mode directly.)

> 2. The following code in the EditAction Policy sucks, I know - When it was just the plot it was a bit annoying, but now it's just obnoxious. The problem here is that the view 'editable' property is a binary, and in some cases it needs to be more context sensitive. Certain views are editable, but only for certain object types, eg. table views should be editable for the table object types, but not for other object types.

Hrm. Do these need to be non-editable for other object types? Telemetry objects will typically be non-editable due to a separate policy, so the only case where I'd see this happening is Telemetry Panel (where it seems like this would be fine)

**Comment by akhenry** [comment]
> Do these need to be non-editable for other object types

It's a reasonable question. Currently they go into edit mode, but the user can't do anything, because the type doesn't support composition and the inspector region that allows selection of columns is only available for table objects. 

It comes down to the views as objects debate. The view is available to object types that don't support composition, so composition as a reason to do editing is out. They could, in principle support configuration, eg. showing and hiding columns. This would be stored as table-specific configuration on non-table objects, or could be treated as ephemeral configuration that is not persisted at all. At this point though, users should perhaps be encouraged to use a table object rather than the table view mode of the telemetry?

**Comment by VWoeltjen** [comment]
I see. It seems like a complicating factor is that we're in a transitional state moving toward the view-as-object paradigm. Inspector assumes view-as-object, but other components don't. (Put another way, if view-as-object were fully implemented, this just wouldn't be an issue.)

Given that, I think it makes sense to leave that check as-is. The "right" way to do it is to complete the view-as-object transition such that this becomes unnecessary, and that's plainly out of scope for this issue, so that leaves us with "wrong" ways. I don't see a better wrong way.

**Comment by larkin** [comment]
> Given that, I think it makes sense to leave that check as-is. The "right" way to do it is to complete the view-as-object transition such that this becomes unnecessary, and that's plainly out of scope for this issue, so that leaves us with "wrong" ways. I don't see a better wrong way.

👍

**Comment by akhenry** [comment]
### Author Checklist

1. Changes address original issue? __Y__
2. Unit tests included and/or updated with changes? __Y__
3. Command line build passes? __Y__
4. Changes have been smoke-tested? __Y__

**Comment by VWoeltjen** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Comment by akhenry** [comment]
### Note to Testers
This change is a refactoring of the Create action. Testing should be performed around the creation of new objects to verify that it is still functioning as intended.

**Pull request merged**
