### PR TITLE
[Build] Move karma test browser from PhantomJS to Chrome

### PR DESCRIPTION
**Pull request by cseale**
Issue #1387

- [x]  1. Changes address original issue?
- [x]  2. Unit tests included and/or updated with changes?
- [x]  3. Command line build passes?
- [x]  4. Changes have been smoke-tested?

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Thanks for taking care of this, and so quickly.

I don't think it's an issue with this PR necessarily, but I'm running into issues executing tests on this branch:

1. `npm test` hangs and `gulp build` hangs on the test portion if I do not have a CHROME_BIN environment variable set. I think this is just because of my local installation (I have run into this with the Chrome launcher in the past, but used to get a helpful error message)
2. When I point CHROME_BIN to my Chrome binary, `npm test` runs and completes successfully, but `gulp build` hangs. I'm speculating that this is just a problem with the way gulp configures the environment, and that it may not be an issue with other Chrome installations.

@akhenry or @larkin - can you try running this when you have a chance? If this is just a problem with my environment I can deal with it individually instead of holding up this PR

**Comment by larkin** [comment]
@VWoeltjen what npm and node version are you running?

**Comment by VWoeltjen** [comment]
npm 3.6.0 and node 5.7.1

**Comment by akhenry** [comment]
This works fine for me, @larkin did you have luck running this?

**Comment by larkin** [comment]
I don't have CHROME_BIN defined nor do I have any problems running `npm test`.

However, `gulp build` did behave quite interestingly.  I believe this is because it is attempting to run `test` and `optimize` at the same time.  `optimize` seems to block execution of all other tasks but it did eventually complete after 2.5 minutes, at which point karma detected issues launching chrome, tried to launch it a second time, and was able to execute tests successfully.

I don't think it's a problem, but we could look at removing `gulp build` if we think it's confusing.

@akhenry I think this is good to merge.

**Comment by akhenry** [comment]
@larkin Yep, I experienced the same thing with `optimize`.

I'm going to merge and keep an eye on Circle CI and Jenkins to make sure there are no build issues.

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A build configuration change
3. Code style and in-line documentation are appropriate? N/A No code changes
4. Commit messages meet standards? Y

**Comment by akhenry** [comment]
Merged. Thanks @cseale!

**Pull request merged**
