### PR TITLE
Add and Remove corresponding classes to capture higher contrast/print friendly png and jpg exports

### PR DESCRIPTION
**Pull request by dtailor90**
solves issue #2080

### CODE REVIEW

**Comment by larkin** [comment]
Needs rework now that notebook has been merged.

**Comment by charlesh88** [comment]
@dtailor90 Taking a look at this now.

**Comment by dtailor90** [comment]
@larkin - I believe this is ready for review, had to add class before cloning element, because the css styles weren't parsed.

**Comment by larkin** [comment]
@dtailor90 apply class name to cloned element works fine, and is less janky, which is highly desirable.

Consider:

janky-capture
vs
not-janky-capture

I've pushed a bcf945ed1 which applies the class only to the cloned element, will continue to R&I.

**Comment by dtailor90** [comment]
## Author Checklist
Changes address original issue? Y
Unit tests included and/or updated with changes? N/A
Command line build passes? Y
Changes have been smoke-tested? Y

**Comment by larkin** [comment]
# Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? NA
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Pull request merged**
