### PR TITLE
Refractor

### PR DESCRIPTION
**Pull request by JonanOribe**
Only some easy refractors along the code

### CODE REVIEW

**Comment by jvigliotta** [comment]
Hi @JonanOribe , if you haven't already, please checkout out our steps to be a contributor: https://github.com/nasa/openmct/discussions/3821

We'll need these steps to be completed before any outside contributions to our codebase can be made. Thanks you!

**Review by jvigliotta — CHANGES_REQUESTED** [review]
Hey @JonanOribe anything in platform/ is legacy, we're not actively updating that code unless we absolutely need to. The action collection changes look fine though, can you remove the legacy edits?

**Comment by JonanOribe** [comment]
Hi @jvigliotta , I have been drop the changes over the legacy code, so now only the update over the collection is still on the pull request. Take a look if you are agree with the current proposal.

**Review by jvigliotta — APPROVED** [review]
LGTM! Thanks @JonanOribe

**Pull request merged**
