### PR TITLE
Enable independent time conductor for stacked plot and overlay plot and bar graphs

### LINKED ISSUE #4503: Add independent time conductor to plots
**Is your feature request related to a problem? Please describe.**
Independent time conductors were recently added to [time views](https://github.com/nasa/openmct/blob/25b34311310dd2970788e6a5ab20298012510b2f/src/ui/components/ObjectView.vue#L3). To support some science use cases, these should also be added to our overlay, stacked plots and bar graphs

**Note that in order to avoid adding unnecessary boilerplate code to additional views issue https://github.com/nasa/openmct/issues/4226 must be addressed first.**

### PR DESCRIPTION
**Pull request by shefalijoshi**
Resolves #4503 

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

### CODE REVIEW

**Comment by shefalijoshi** [comment]
@charlesh88 The independent time controls are not visible since they're behind the plot action buttons. Can you take a look?

**Comment by charlesh88** [comment]
> @charlesh88 The independent time controls are not visible since they're behind the plot action buttons. Can you take a look?

@shefalijoshi I don't see this problem, here's what I do see:

**Main view**
image

**In a Display Layout**
image

**Review by charlesh88 — DISMISSED** [review]
LGTM!

**Review by charlesh88 — APPROVED** [review]
Still LGTM

**Pull request merged**
