### PR TITLE
Style Timestrip and Plan views

### PR DESCRIPTION
**Pull request by charlesh88**
### Overview
- Plan activity rects now don't use rounded corners if the width is less than the radius, and use a minimum width of 1;
- Visual refinements to time axis and swimlanes;
- Refactored CSS-related class names and file `swim-lane` to `swimlane`;
- Plan rowspans now computed dynamically - thanks @shefalijoshi;
- Now when an activity label isn't inside the rect, it uses the theme's CSS foreground text color. When it is inside, it uses a function that calculates contrast and uses white or black, depending on what the color of the activity is. Activity colors must be specified as full hex strings, like '#00FF00'.

### Author Checklist
1. Changes address original issue? Y
1. Unit tests included and/or updated with changes? N/A
1. Command line build passes? Y
1. Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by charlesh88** [comment]
@shefalijoshi I'm seeing what look like loading issues for Plans and Timestrips added to a Layout: 
Screen Shot 2021-02-26 at 2 10 14 PM

**Comment by charlesh88** [comment]
@shefalijoshi for the fix to the Layout issue mentioned above. Thx!

**Comment by charlesh88** [comment]
Seeing some issues with the time axis:
image

- Not syncing with Time Conductor in the Timestrip view when the Time Conductor is changed in Fixed mode. Navving away and back will force an update.
- In Plan view, changes to the TC update the axis immediately. This seems like the opposite of what we wanted - I thought the Timestrip was about dynamic time bounds, and the idea was for the Plan view to show the whole plan.

**Review by shefalijoshi — APPROVED** [review]
LGTM

**Review by shefalijoshi — APPROVED** [review]

**Pull request merged**
