### PR TITLE
[Common UI] Add mct-refresh directive

### PR DESCRIPTION
**Pull request by VWoeltjen**
Adds an `mct-refresh` directive, addressing the developer use cases for both #311 and #312 (since this is useful for domain objects, as shown in changes to `platform/commonUI/general/res/templates/label.html`, without having any specific knowledge of domain objects.)

See JSDoc on MCTRefresh.js for a usage summary.
### Author Checklist
1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y 
4. Expect to pass code review? Y

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Investigating CircleCI build failure:

```
[INFO] pure virtual method called
[INFO] terminate called without an active exception
[INFO] PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/572edf49-79a6-1d64-18fe8856-28a01932.dmp
[INFO] Aborted (core dumped)
```

Can't reproduce locally; suspecting this may be a transient issue unrelated to this changeset (#367 is also failing irreproducibly)

**Comment by VWoeltjen** [comment]
Also hitting load timeouts with require; increased the timeout interval in the npm test script to allow tests to run, CircleCI's checks now pass.

**Comment by larkin** [comment]
@VWoeltjen This PR has not been tagged with a sprint and seems to have fallen off the radar.  I seem to remember that we had merged these changes already (refactored in another pull request?), but maybe I am remembering incorrectly?

Do you know if this still requires a review & integrate?

**Comment by larkin** [comment]
Closing as "not going to implement"

**Pull request closed without merging**
