### PR TITLE
[Edit] Add notifications to Save & SaveAs

### PR DESCRIPTION
**Pull request by BogdanAlexandru**
This adds notifications to the Save and SaveAs actions, for success and failure. Solves #1180.

It's blocked by https://github.com/nasa/openmct/issues/1257.  It used to work before I merged in the new API changes.

Technically it's not blocked by https://github.com/nasa/openmct/pull/1222 but we probably want that in first so that success notifications don't linger.

I haven't found a way to mock promises to simulate success and failure properly in `SaveActionSpec` (my closest attempt ended up in calling both `OnSuccess` and `OnFailure` due to how `then` and `catch` are chained), so I just went with regular Promise behavior. Any thoughts on what I might've missed/done wrong there appreciated, can go back and change stuff.
## Author Checklist
-     Changes address original issue? Y
-     Unit tests included and/or updated with changes? Y
-     Command line build passes? Y
-     Changes have been smoke-tested? Y

### CODE REVIEW

**Comment by BogdanAlexandru** [comment]
This still needs a bit of work; the user manually canceling the Save As dialog is considered a save failure and he gets a "Save Failed" notification. We probably don't want that.

**Comment by BogdanAlexandru** [comment]
No more errors when the user is canceling SaveAs on his own. Compiled a gif with a demo of the notifications, manually toggling failure points: http://imgur.com/YZM6DQp

At times the Success messages feel a bit superfluous, but it might be just me. I might not get this impression in a context where saving is done remotely and takes a bit of time, here it's instant and you never expect it to fail since it's local.

Let me know if anything needs changing.

**Comment by akhenry** [comment]
@BogdanAlexandru Thanks for doing this. Also, the gif is really useful for demonstrating the new notification, thanks. I take your point about the success messages seeming a little superfluous at times.  I do think that it gives some useful feedback for "save and continue" that is otherwise missing, and if nothing else it's worth it for this. If we find users ignoring error messages because of visual noise caused by overuse of notifications then we should reconsider this approach.

**Comment by akhenry** [comment]
@BogdanAlexandru I've reviewed this and it looks good to me. Just wanted to confirm with you that you're done with it? Thought I'd double check as there were some changes made since the author checklist. If you're finished then I'll go ahead and merge it.

**Comment by BogdanAlexandru** [comment]
Yeah, it should be good to go now.

Totally agree with:

> I do think that it gives some useful feedback for "save and continue" that is otherwise missing, and if nothing else it's worth it for this. If we find users ignoring error messages because of visual noise caused by overuse of notifications then we should reconsider this approach.

**Comment by akhenry** [comment]
### Reviewer Checklist

* Changes appear to address issue? Y
* Appropriate unit tests included? Y
* Code style and in-line documentation are appropriate? Y
* Commit messages meet standards? Y

**Comment by akhenry** [comment]
@BogdanAlexandru Sorry for the delay in merging this. Thanks for your help!

**Pull request merged**
