### PR TITLE
chore: move indexTest to kebab-case

### PR DESCRIPTION
**Pull request by evenstensberg**
### Describe your changes:
kebabcase is used for the entire pwd of the root.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Review by ozyx — APPROVED** [review]
Consistency is a wonderful thing. Thanks for this!

**Comment by ozyx** [comment]
@unlikelyzero I think this is blocked for merge due to the way GHA runs against this, we lose envvars for dockerhub

**Comment by evenstensberg** [comment]
@ozyx feel free to add me to the NASA org 😆

**Comment by unlikelyzero** [comment]
@evenstensberg please rebase on master. I believe we've fixed https://github.com/nasa/openmct/issues/6890

**Comment by evenstensberg** [comment]
Rebased

**Review by unlikelyzero — APPROVED** [review]

**Pull request merged**
