### PR TITLE
4555 - Preserve the previousFocusedImage for local and fixed time

### LINKED ISSUE #4555: [Imagery] Adjusting the bounds will sometimes cause the focusedImage to shift which image is selected
#### Summary

Seems to be limited in scope to local clock; the fixed timespan flow seems to be working as expected.

#### Expected vs Current Behavior

If the index is properly matched in the updated imageHistory array, the index should be maintained and the image should not be replaced.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Navigate to example imagery
2. Adjust the time bounds of local clock
3. Observe sometimes the image will change

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

### PR DESCRIPTION
**Pull request by michaelrogers**
Closes #4555

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [ ] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

**Comment by nikhilmandlik** [comment]
hey @michaelrogers shefali has similar changes, https://github.com/nasa/openmct/pull/4591, that might fix this, can you check if shefali's pr fixes this issue? TIA

**Comment by michaelrogers** [comment]
@nikhilmandlik - testing this on the testathon release and I believe that #4591 improved it but the real time image shifting is still apparent when set to local clock.

**Comment by michaelrogers** [comment]
@shefalijoshi - not yet ready to merge. I am investigating a problem I observed after merging in master. The aspect ratio of the image stochastically changes after an imageryData -> boundsChange event is triggered.

**Comment by akhenry** [comment]
@michaelrogers  Base needs to be [`release/1.8.3`](https://github.com/nasa/openmct/tree/release/1.8.3), rather than master.

**Comment by shefalijoshi** [comment]
@michaelrogers I see what you're trying to do here. However, we should keep focusedImage code within ImageryView if possible since imageryData.js is a mixin that's used by both the ImageryTimeView and the ImageryView.
Do you think that's possible?

**Pull request closed without merging**
