### PR TITLE
Minimize production css

### PR DESCRIPTION
**Pull request by jooohhn**
## Summary
- **Results: Made CSS files ~30% smaller (right) than master (left)**
image
- Add css-minification via `OptimizeCSSAssetsPlugin`
- Explicitly set the `optimizations` property that were present before this PR
  - This is necessary since `OptimizeCSSAssetsPlugin` overrides the implicit defaults set [by the `mode` property ](https://webpack.js.org/configuration/mode/)
- Webpack documentation reference for this PR: https://webpack.js.org/plugins/mini-css-extract-plugin/#minimizing-for-production

## Author Checklist
- **Changes address original issue**: I couldn't find a Github issue related to this PR. Just thought it'd be a nice enhancement after checking out the repo
- **Unit tests included and/or updated with changes**: N
- **Command line build passes**: Y
- **Changes have been smoke-tested**: Y

### CODE REVIEW

**Comment by jvigliotta** [comment]
@charlesh88 Is this something we'd like/need? If so, can you take a look at this?

**Comment by jvigliotta** [comment]
@jooohhn I don't see a CLA on file for you. We'll need one of those to merge in any outside contributions. You can get more information here: https://github.com/nasa/openmct/discussions/3821

Thanks!

**Comment by akhenry** [comment]
This is definitely desirable, we should do some testing and try and get this merged. Thanks @jooohhn

**Comment by jvigliotta** [comment]
> This is definitely desirable, we should do some testing and try and get this merged. Thanks @jooohhn

Awesome, in that case, @jooohhn all we'll need is the CLA on file that I mentioned in the previous comment and to resolve any conflicts. Thanks!

**Review by charlesh88 — COMMENTED** [review]
Evaled locally like this:
1. Cloned the repo and switched to branch `minimize-production-css`.
2. Did `npm install`. File `dist/espressoTheme.css` size is ~ 282 Kb.
3. Ran `npm run build:prod`. File `dist/espressoTheme.css` is now ~ 229 Kb, about a 19% reduction. Confirmed that file was minified.
4. Ran Open MCT locally and confirmed that source mapping is working. 

Summary: LGTM, thanks @jooohhn! I'd like @akhenry or @nikhilmandlik to review with a more functional eye than mine.

**Comment by akhenry** [comment]
Have also tested, and this looks good to me. @jooohhn we just need [a CLA](https://nasa.github.io/openmct/static/files/ind-cla-open-mct.pdf) from you and we can merge this.

**Review by akhenry — CHANGES_REQUESTED** [review]
Have also tested, and this looks good to me. @jooohhn we just need [a CLA](https://nasa.github.io/openmct/static/files/ind-cla-open-mct.pdf) from you and we can merge this.

**Comment by jooohhn** [comment]
Thanks for the feedback, I'll have the CLA signed by tomorrow 😄

**Comment by jvigliotta** [comment]
@jooohhn they haven't received it as of yet, I'll keep checking!

**Comment by akhenry** [comment]
Closing until we can confirm that we have a signed CLA.

**Pull request closed without merging**
