### PR TITLE
chore: bump `@percy/cli` to 1.29.1 and `@percy/playwright` to 1.0.6

### PR DESCRIPTION
**Pull request by ozyx**
Closes 

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Has this been smoke tested?
* [ ] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [ ] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@ozyx this was failing some months ago.

**Comment by ozyx** [comment]
@unlikelyzero looks like it still is for some reason. playwright catching a browser error from percy in [visual-a11y tests](https://circleci.com/gh/nasa/openmct/102452):

```txt
    Error: Console error detected: [error] Failed to load resource: net::ERR_NAME_NOT_RESOLVED at (http://render.percy.local/__serialized__/_ws0muqhxi.png 0:0)
    ```

**Comment by unlikelyzero** [comment]
@ozyx let's close this

**Comment by ozyx** [comment]
> @ozyx let's close this

😔

**Pull request closed without merging**
