### PR TITLE
example imagery refactor to have configurable image urls and IMAGE_DELAY

### PR DESCRIPTION
**Pull request by nikhilmandlik**
### Resolves:
resolves: https://github.com/nasa/openmct/issues/4026
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Screenshots:
Screen Shot 2021-10-20 at 12 31 15 PM

Screen Shot 2021-10-20 at 12 30 58 PM

### CODE REVIEW

**Comment by akhenry** [comment]
@nikhilmandlik What issue is this PR addressing? Is this something that is intended to be merged?

**Comment by nikhilmandlik** [comment]
> @nikhilmandlik What issue is this PR addressing? Is this something that is intended to be merged?

@akhenry This change was (requested by @charlesh88 ) only meant for demo.
But wondering if its good idea to implement this as feature in openmct?

**Comment by jvigliotta** [comment]
@charlesh88 @akhenry Do we still want this?

**Review by charlesh88 — APPROVED** [review]
LGTM

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

**Pull request merged**
