### PR TITLE
[CLA Approved] Add openmct type hints

### PR DESCRIPTION
**Pull request by skrobchik**
Closes 

### Describe your changes:

Adds type information for the `setAssetPath` method.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by ozyx** [comment]
Thank you so much for your contribution! If you haven't already, please complete and submit a [Contributor License Agreement (CLA)](https://github.com/nasa/openmct/discussions/3821). This is required before we can approve/merge your code. That will take a little bit of time to process, so in the meantime if you'd like to add any more types in this PR please feel free to do so. Thanks again!

**Comment by skrobchik** [comment]
Hello @ozyx ,

Thank you for reviewing the PR. We're working with Open MCT and TypeScript at our rocketry club, so I will try to add type information for APIs as I go.

I emailed the Contributor License Agreement to arc-sra-team@mail.nasa.gov and kimberly.minafra@nasa.gov, hope they can review it soon.

**Comment by skrobchik** [comment]
Also added type for the TypeRegistry

**Comment by skrobchik** [comment]
@ozyx  Any updates on the CLA?

**Comment by ozyx** [comment]
@skrobchik No updates yet, I just sent a follow-up so I'll let you know once they get back to me on the CLA status. We have a few folks waiting on approval. Unfortunately this is largely a manual process and can take some time, especially during the holidays. Appreciate your patience!

**Comment by skrobchik** [comment]
I've followed up on the email to arc-sra-team@mail.nasa.gov and kimberly.minafra@nasa.gov, but still haven't received a response.

**Comment by ozyx** [comment]
> I've followed up on the email to arc-sra-team@mail.nasa.gov and kimberly.minafra@nasa.gov, but still haven't received a response.

I will also follow up and see if I can get a confirmation. Apologies again for the wait.

**Comment by ozyx** [comment]
@skrobchik Your CLA has been approved! Thank you for waiting.

**Review by ozyx — APPROVED** [review]
LGTM

**Comment by ozyx** [comment]
@skrobchik Please merge master into this branch or rebase it on top of master-- otherwise, this is good to go!

**Comment by skrobchik** [comment]
Rebased

**Comment by ozyx** [comment]
@skrobchik I don't have write access to the branch you're trying to merge from, so this is proving difficult as master continually changes. Please do one of the following:

1. Rebase on `master` again and ping me, and I'll try to get to it in time 😬 
2. (Better option) Retarget the PR to merge from a public fork of Open MCT instead

**Comment by skrobchik** [comment]
@ozyx I'm not quite sure what you mean with option 2 ?

I rebased on top of master anyway. I thought that GitHub automatically rebased pull-requests on top of master before merging if there are no merge conflicts.

**Comment by ozyx** [comment]
> @ozyx I'm not quite sure what you mean with option 2 ?
> 
> I rebased on top of master anyway. I thought that GitHub automatically rebased pull-requests on top of master before merging if there are no merge conflicts.

Yeah you're doing everything correctly, what I mean is that since the repo it's merging from is protected, if master were to change while I'm waiting for our CI checks to complete I wouldn't be able to rebase or add a merge commit because I don't have write access to your fork. Regardless-- option 1 worked :)

**Pull request merged**
