### PR TITLE
[Navigation Tree] Whole tree item clickable

### PR DESCRIPTION
**Pull request by jvigliotta**
Restarting this PR: https://github.com/nasa/openmct/pull/3632 which was accidentally merged early.

### CODE REVIEW

**Review by deeptailor — APPROVED** [review]
LGTM!

**Review by deeptailor — CHANGES_REQUESTED** [review]
Actually, just pulled down and tested, and clicking on arrows does not work anymore, and navigation is on and off as well

**Comment by jvigliotta** [comment]
> Actually, just pulled down and tested, and clicking on arrows does not work anymore, and navigation is on and off as well

I'll take care of that... rookie mistake

**Review by deeptailor — APPROVED** [review]
LGTM

**Comment by deeptailor** [comment]
Closes #3627

**Comment by deeptailor** [comment]
## Reviewer Checklist
Changes appear to address issue? Yes
Appropriate unit tests included? N/A
Code style and in-line documentation are appropriate? Yes
Commit messages meet standards? Yes
Has associated issue been labelled unverified? (only applicable if this PR closes the issue) Yes

**Pull request merged**
