### PR TITLE
Minmax should be enabled by default for plots

### PR DESCRIPTION
**Pull request by deeptailor**
While adding a fix for issue #2381, we disabled minmax unless the plots had a line style. This caused a bug where minmax requests were not made for telemetry points(plots), that did not have an option for line styles. A subsequent error was caused when there was no options object passed into the fetch function for plots (plots that are a default view for telemetry points, do not have any configurable options). 

In this fix I have enabled minmax by default and only disabled it for marker-only line styles, and a check for the options object in the fetch function.

### CODE REVIEW

**Comment by deeptailor** [comment]
## Author Checklist
Changes address original issue? Yes
Unit tests included and/or updated with changes? N/A
Command line build passes? Yes
Changes have been smoke-tested? Yes

**Comment by akhenry** [comment]
@deeptailor Based on conversation on 12/05 I think we need to provide options to `fetch`. One possibility would be to have TelemetrySeries store the last options they were invoked with so that when filters get updated they don't have to try and reconstitute all of the previous request options.

**Comment by deeptailor** [comment]
## Testing Notes

1. Add console.log(arguments); in line 79 of GeneratorProvider.js
2. Open up chrome inspector.
3. Create a sinwave generator. 
4. Look at console
5. Verify that strategy in the second argument is minMax

**Comment by charlesh88** [comment]
Testathon 12-06-19: verified fixed.

**Pull request merged**
