### PR TITLE
Defer intersection monitoring until needed to prevent race conditions

### LINKED ISSUE #7277: Plots sometimes do not render on load
#### Summary
Ocassionally plots will not load when embedded in a tabbed display. This appears to be a race condition related to the intersection observer that dynamically allocates and deallocates webgl contexts to plots.

#### Steps to Reproduce
1. Load openmct-yamcs quickstart
2. Start the Yamcs Quickstart server and Python Simulator
3. Import [the attached display](https://github.com/nasa/openmct/files/13562597/Unnamed.Tabs.View.json)
4. Navigate to the imported display
5. In Chrome dev tools, add a breakpoint to [this line of code](https://github.com/nasa/openmct/blob/2d9c0414f72c583e2894d81cc80ab1bad09e06c6/src/plugins/plot/chart/MctChart.vue#L284).
6. Refresh the display
7. Hit continue every time the break point is triggered
8. Observe that the plots are empty

https://github.com/nasa/openmct/assets/4215777/0a418bae-22eb-46c0-8009-a00c0727d573

#### Environment
* Open MCT Version: 3.3.0
* Deployment Type: openmct-yamcs / yamcs quickstart

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #7277 

### Describe your changes:

- Wait to start observing for intersections (i.e., visibility) until `renderWhenVisible` is called once. This prevents every View needing to subscribe to intersection events, and prevents a race condition where the view isn't quite built yet.
- Wait to start observing canvas for visibility until we've called `draw` once. Prevents similar race condition as above.
- Update API documentation. 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by scottbell** [comment]
Before:

https://github.com/nasa/openmct/assets/9853862/f5f8f013-1c98-4f35-869f-8fa1df73acc6

After:

https://github.com/nasa/openmct/assets/9853862/d9abbc20-087a-44f7-a0a5-ae7e0dff4901

**Review by ozyx — APPROVED** [review]
LGTM

**Comment by scottbell** [comment]
@akhenry please let me know if there's anything else we need to test here

**Comment by scottbell** [comment]
> @akhenry please let me know if there's anything else we need to test here

Merging for the interim, but can revert if we need.

**Pull request merged**
