### PR TITLE
[CLA on File] style: added padding to object & icon button labels

### LINKED ISSUE #3822: Icon button labels are being clipped
Icon buttons that have a text label are being clipped, sometimes hiding the characters descenders. Look at the bottom of the "g" (text changed to illustrate the effect):

Screen Shot 2021-04-20 at 2 39 26 PM

Adding `padding: 1px 0` to the label fixes the problem:

Screen Shot 2021-04-20 at 2 39 59 PM

### PR DESCRIPTION
**Pull request by taintedbones**
Closes #3822 #3568 

### Describe your changes:
 Added 1px padding to the top and bottom of object & icon button labels. This fixes issues with labels being clipped on the bottom.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by akhenry** [comment]
@taintedbones Thanks for taking a look at this! The fix works @ 100% zoom, which is awesome. Problem is still occurring at other zoom levels though.

eg.

Chrome @ 100% ✅ 
Screen Shot 2022-12-19 at 10 27 29 AM

Chrome @ 110% ❌ 
Screen Shot 2022-12-19 at 10 27 48 AM

**Comment by taintedbones** [comment]
@akhenry Thank you for the feedback! So I went back to check on this and couldn't replicate the issue on my branch. However, when I swapped over to master branch, the issue existed there. 

Chrome 100% 
openmct100

Chrome 110%
openmct110

**Comment by akhenry** [comment]
@taintedbones OK, let me take another look! Thanks.

**Comment by akhenry** [comment]
Have retested and this looks good to me. Sorry, I don't know what I did last time :)

@charlesh88 This look good to you?

**Review by akhenry — APPROVED** [review]

**Comment by ozyx** [comment]
> Not sure why this branch is changing plot images in the e2e tests folder... CSS changes look good, and this is good to go once we clarify what's going on with e2e images.

Hi, these changes were from me. Needed to update our e2e snapshots due to visual change on the main view.

**Pull request merged**
