### PR TITLE
[proxyUrl] pass URL parameters to proxied URL

### PR DESCRIPTION
**Pull request by raoulsullivan**
Addresses issue #1158

- [x] Changes address original issue?
- [x] Unit tests included and/or updated with changes?
- [x] Command line build passes?
- [x] Changes have been smoke-tested?

Doesn't impact/require any tests that I can see...

### CODE REVIEW

**Comment by VWoeltjen** [comment]
Changes look good and will help us close #1146 - thanks! 

Before we can merge open source contributions, we need a contributor license agreement on file; this document along with instructions can be found at https://nasa.github.io/openmct/contributing/

**Comment by VWoeltjen** [comment]
CLA received, proceeding with merge. Thanks again!

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A (changes to dev server only)
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Comment by larkin** [comment]
This is an incorrect fix; the urls described in #1158 are improperly encoded and thus invalid.  They should be encoded with `encodeURIComponent` which prevents #1158 from occuring.

I'd like to revert this changeset.  @VWoeltjen do you concur?

**Comment by VWoeltjen** [comment]
Agree that this is not a correct fix (good spotting the URI encoding on #1158, I should have noticed that.)

I'm given a little pause on just reverting because the [usage](https://github.com/hudsonfoo/kerbal-openmct/blob/f9f90725c7feca62426da6ed64688b1fe9025d75/src/KerbalTelemetryServerAdapter.js#L15-L22) is very sensible: It doesn't expect to be using `proxyUrl`, so it just makes a straightforward call to `$http`, providing params and letting it assemble the actual URL. Requiring `encodeURIComponent` would prevent that kind of usage and break the `kerbal-openmct` plugin.

Part of the issue here is that the development server (and functionality only ever intended to support the live demo) is getting repurposed. Really, we expect other deployments to provide their own HTTP server.

Given that, I think the best thing to do here is revert this change, but also do a PR to the `kerbal-openmct` to get it to function as a standalone app (we do need an example of how to do that). At minimum, if we break that plugin I think we should file an issue with some guidance on fixing it.

**Comment by hudsonfoo** [comment]
Good catch. URI now encoded. Everything five by five.

**Comment by larkin** [comment]
Thanks @hudsonfoo 

As https://github.com/hudsonfoo/kerbal-openmct/commit/bc40556d0d4990c1e2b23a6a328fc0b2ec393a4a adds URI encoding, I will revert this.

**Pull request merged**
