### PR TITLE
Inspector tabs

### LINKED ISSUE #6118: inspector views tabs
**Summary**
Inspector views are getting more complex and there are more of them. We need a better way to organize them.

**Describe the solution you'd like**
TABS!

**Describe alternatives you've considered**
Accordions

**Testing Instructions**
1. put the inspector through its paces
    2. select different objects in the tree and see that the inspector displays context for the selection
    3. select different tabs and see that the inspector view changes appropriately
    4. go into and out of edit mode (both saving and exiting without saving)
    5. tabs should only be visible for intended selections and in correct state (edit mode, stylable, etc.)
1. some more specific tests
    2. plots have different view / edit inspector views
    3. folders and non-persistables should not display a styles tab
1. things to keep an eye out for
    2. wacky or super long tab names
    3. empty inspector views

### PR DESCRIPTION
**Pull request by davetsay**
Closes #6118

### Describe your changes:
* register all hardcoded inspector views with inspectorViewRegistry
* views get their own tabs
* tabs have logic to hide/show based on `selection` and `isEditing` (only for now)

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by davetsay** [comment]
@charlesh88 when you have a moment i'd like to show you the inspector tabs

**Comment by akhenry** [comment]
@charlesh88 to review implementation.

**Comment by akhenry** [comment]
@davetsay To review tests.

**Comment by ozyx** [comment]
I'm seeing an issue where the Properties tab isn't populated on mount:

https://user-images.githubusercontent.com/9259993/212996491-5d09354a-ed42-4c81-8dcb-c9316c103657.mov

**Comment by davetsay** [comment]
see #6137

**Pull request closed without merging**
