### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by HollowMan6**
transtion -> transition

### CODE REVIEW

**Comment by DusterTheFirst** [comment]
Small changes like these are unlikely to be merged since they add very little to the project as a whole. If you wanted to contribute spell-checking, try and batch a bunch of spelling checks into this PR. Yes, it of course sucks that this word is misspelled, but this change doesn't *really* add much.

**Comment by HollowMan6** [comment]
I guess there should be no more typos in docs: https://github.com/nasa/openmct/tree/master/docs

**Comment by jvigliotta** [comment]
Hello @HollowMan6 we will need a CLA on file before we can merge in any changes. Please follow the process here: https://github.com/nasa/openmct/discussions/3821

**Comment by HollowMan6** [comment]
Hi @jvigliotta, thanks for the reply. Have signed the CLA and sent the document to the specified email addresses.

**Comment by jvigliotta** [comment]
@HollowMan6 we've finally got your CLA on file, we'll merge this one in. Thanks!

**Review by jvigliotta — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
