### PR TITLE
[Summary Widget] support enum fields

### PR DESCRIPTION
**Pull request by psarram**
Displays a drop-down menu with available options when an enum field is selected in a condition. 

Fixes an existing issue where condition didn't get evaluated properly when operation was switched from `isDefined` to something like `equalTo` and back to `isDefined`. 

Also, fixes issue #2405.

### CODE REVIEW

**Comment by akhenry** [comment]
This looks great! Nice work

**Comment by akhenry** [comment]
## Reviewer Checklist

* Changes appear to address issue? Y
* Appropriate unit tests included? N/A
* Code style and in-line documentation are appropriate? Y
* Commit messages meet standards? Y

**Comment by psarram** [comment]
**Testing Notes:**
1. Create a Summary Widget and add a telemetry that includes an enum field.
2. Add a rule and select the telemetry.
3. Select the enum field and test each comparison by selecting them from the Comparison drop-down.
4. When `is` or `is not` comparison is selected, a drop-down is displayed with String representation of available enum values.

**Comment by akhenry** [comment]
Verified fixed 05/24/2019

**Pull request merged**
