### PR TITLE
[WIP] ES6 Syntax

### PR DESCRIPTION
**Pull request by gkal19**

### CODE REVIEW

**Comment by larkin** [comment]
@gkal19 Before you go too far down this path, this conversion is something the internal team will be undertaking, and for procedural reasons we can't accept this changeset from a third party.

**Comment by gkal19** [comment]
I understood! Sorry

**Comment by larkin** [comment]
@gkal19 No problem, We have many other issues tagged `help-wanted`, feel free to look at those and try your hand on them!

**Comment by gkal19** [comment]
Nice! I'll do it

**Pull request closed without merging**
