### PR TITLE
Fix JavaScript syntax in example

### PR DESCRIPTION
**Pull request by inad9300**

### CODE REVIEW

**Comment by ozyx** [comment]
Thank you so much for your contribution! If you haven't already, please complete and submit a [Contributor License Agreement (CLA)](https://github.com/nasa/openmct/discussions/3821). This is required before we can approve/merge your code.  Thanks again, we will be taking a look at this shortly!

**Comment by davetsay** [comment]
@inad9300 , in order for us to review this we need
1. an issue that is closed by this pr
2. a CLA on file (just please let us know if you have submitted one yet)

**Comment by inad9300** [comment]
I'm sorry, but that's too much overhead for me, so please allow me to respectfully decline. You'll have to fix the typo yourselves :wink:

**Comment by inad9300** [comment]
Have you finally fixed the typo by yourselves, created a ticket to follow it up, or something of the sort? Just honestly curious to know a bit more of the level of care with which you develop this library.

**Pull request closed without merging**
