### PR TITLE
Fix Notebook enter key 6354

### LINKED ISSUE #6354: Allow Enter key in Notebook entry to add new lines by default
**Is your feature request related to a problem? Please describe.**
Line breaks by default from the Enter key was the initial design approach, but that was changed after some user requests at that time. However, after an extended period of Notebook usage by multiple constituents, it's become clear that there is a strong desire to allow line breaks in Notebook entries as the default action. This will become even more important when we go after entry formatting, that allows bulleted lists and tables. 

From VIPER user requests 225.

**Describe alternatives you've considered**
To support this but try to retain some of the Enter key's streamlining, we should do the following:
- Remap the Enter back to its original usage of adding lines in entries.
- Allow a key modifier like Cmd+Enter (or Windows key+Enter) to close an entry.
- Keep the "tab out" function which currently closes the entry.
- Add commit and (ideally) cancel buttons to the edit mode of the entry. It's not clear we need a "cancel" button, which could be significantly more effort - the expectation would be to revert all changes to the entry.

**Additional context**

### PR DESCRIPTION
**Pull request by charlesh88**
Closes #6354
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by charlesh88** [comment]
@davetsay I'd like to understand why Notebook entry input seems to need to be `disabled` when it's not actively being edited. Removing this property gives us the "must click twice to edit" flow that I'm looking for, but `disabled` isn't the right attribute to be using in this case.

**Comment by charlesh88** [comment]
Todo: 
- [ ] Write testing notes.
- [ ] Change this PR from draft to actual.

**Review by jvigliotta — CHANGES_REQUESTED** [review]
This looks good and I'm sure it's going to make editing notebooks much easier! One issue I found was that we no longer can click links in notebook entries. It looks like the disabled attribute keeps the mouseover event from firing? But this prevents the check for if you are over a link and you can't navigate using the link unless it's click on once (bringing it to edit mode).

**Comment by davetsay** [comment]
> This looks good and I'm sure it's going to make editing notebooks much easier! One issue I found was that we no longer can click links in notebook entries. It looks like the disabled attribute keeps the mouseover event from firing? But this prevents the check for if you are over a link and you can't navigate using the link unless it's click on once (bringing it to edit mode).

Fixed this without using `disabled` @jvigliotta , @charlesh88 . Ready for re-review.

**Review by jvigliotta — APPROVED** [review]
This is GOOD TO GO!

Nice work!

**Comment by davetsay** [comment]
i think something is seriously borked here...
you can get into weird states where the new entry doesn't get focused, and then clicking on the input to focus it makes the entry go away.

separate issue is that if you try to delete a new entry, you get an error since the new entry isn't yet persisted

**Pull request merged**
