### PR TITLE
[INSPECT] add offsets to trackPosition

### LINKED ISSUE #1830: Info Bubbles appear then disappear immediately
eg.
tooltip

Steps to reproduce:
1. Hover over any object in the tree on testathon build.
2. Observe info bubble appearing briefly before disappearing.

### PR DESCRIPTION
**Pull request by ev1stensberg**
fixes #1830 

Author Checklist
Changes address original issue?
Y

Unit tests included and/or updated with changes?
N/A

Command line build passes?
Y

Changes have been smoke-tested?
Y

### CODE REVIEW

**Comment by dtailor90** [comment]
@ev1stensberg Thanks for the PR, please fix the failing tests and I can re-review.

**Comment by dtailor90** [comment]
@ev1stensberg - Your approach fixes the issue of the callback triggering twice when the bubble is displayed to the right of the mouse, but when the bubble is displayed to the left of the mouse the problem persists. I would suggest finding an absolute way of adding a margin to the bubble so the hover callback is not triggered twice while the mouse is in the same position. 

After some investigation, if you take a look at popup service, it accepts an options object where you could specify an offset and it will be offset by that number in all directions. 

Let me know if you have any questions.

**Comment by ev1stensberg** [comment]
Did some testing, and adding a 5 pixel offset when tracking its position lets the bubble be within the hover area without having an offset that makes it too far away to seem "right".

Using `options.OffsetX/Y`:

skjermbilde 2018-01-06 kl 07 29 41

add offset in tracking:


skjermbilde 2018-01-06 kl 07 30 52

**Comment by ev1stensberg** [comment]
@dtailor90 PTAL

**Comment by dtailor90** [comment]
@ev1stensberg - Thanks for your contribution. Your solution works, but tackling this problem by adding an offset to the x position when instantiating the popUp service seems to be a more straight forward solution. Check PR #1868.

**Comment by ev1stensberg** [comment]
@dtailor90 Couldn't you just have requested changes instead? Showed you two scenarios, was happy to change to offset :)

**Pull request closed without merging**
