### PR TITLE
Reviewer to smoke test PRs before merge

### PR DESCRIPTION
**Pull request by akhenry**
Closes https://github.com/nasa/openmct/issues/5770

### Describe your changes:
Adds an item to the reviewer checklist to smoke-test the new functionality.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Review by khalidadil — APPROVED** [review]

**Comment by ozyx** [comment]
Overall this looks good, and I think it's a good idea to codify this into the reviewer checklist.

I'd like to suggest pruning "Commit messages meet standards?", since we squash commits anyway and I haven't encountered a situation thus far where I've had to block a PR on commit messages.

I think we should also edit the language "Appropriate ~unit~ tests included?" so it's clear that it could mean unit and/or e2e tests

**Comment by scottbell** [comment]
> Overall this looks good, and I think it's a good idea to codify this into the reviewer checklist.
> 
> I'd like to suggest pruning "Commit messages meet standards?", since we squash commits anyway and I haven't encountered a situation thus far where I've had to block a PR on commit messages.
> 
> I think we should also edit the language "Appropriate ~unit~ tests included?" so it's clear that it could mean unit and/or e2e tests

I like these suggestion too.

**Review by jvigliotta — APPROVED** [review]
Makes sense to me.

**Review by rukmini-bose — APPROVED** [review]

**Review by scottbell — APPROVED** [review]

**Review by shefalijoshi — APPROVED** [review]
Good idea!

**Review by charlesh88 — APPROVED** [review]
I very often do this anyway, so am in full support.

**Pull request merged**
